syntax = "proto3";

package api.admin.log.v1;

option go_package = "github.com/OmnTeam/ppanel-pro/api/admin/log/v1;v1";
option java_multiple_files = true;
option java_package = "api.admin.log.v1";

import "google/api/annotations.proto";

service LogService {
  rpc FilterBalanceLog(FilterBalanceLogRequest) returns (FilterBalanceLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/balance/list"
    };
  }

  rpc FilterCommissionLog(FilterCommissionLogRequest) returns (FilterCommissionLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/commission/list"
    };
  }

  rpc FilterEmailLog(FilterEmailLogRequest) returns (FilterEmailLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/email/list"
    };
  }

  rpc FilterGiftLog(FilterGiftLogRequest) returns (FilterGiftLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/gift/list"
    };
  }

  rpc FilterLoginLog(FilterLoginLogRequest) returns (FilterLoginLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/login/list"
    };
  }

  rpc GetMessageLogList(GetMessageLogListRequest) returns (GetMessageLogListReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/message/list"
    };
  }

  rpc FilterMobileLog(FilterMobileLogRequest) returns (FilterMobileLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/mobile/list"
    };
  }

  rpc FilterRegisterLog(FilterRegisterLogRequest) returns (FilterRegisterLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/register/list"
    };
  }

  rpc FilterServerTrafficLog(FilterServerTrafficLogRequest) returns (FilterServerTrafficLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/server/traffic/list"
    };
  }

  rpc FilterSubscribeLog(FilterSubscribeLogRequest) returns (FilterSubscribeLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/subscribe/list"
    };
  }

  rpc FilterResetSubscribeLog(FilterResetSubscribeLogRequest) returns (FilterResetSubscribeLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/subscribe/reset/list"
    };
  }

  rpc FilterUserSubscribeTrafficLog(FilterUserSubscribeTrafficLogRequest) returns (FilterUserSubscribeTrafficLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/subscribe/traffic/list"
    };
  }

  rpc FilterTrafficLogDetails(FilterTrafficLogDetailsRequest) returns (FilterTrafficLogDetailsReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/traffic/details"
    };
  }

  rpc GetLogSetting(GetLogSettingRequest) returns (GetLogSettingReply) {
    option (google.api.http) = {
      get: "/v1/admin/log/setting"
    };
  }

  rpc UpdateLogSetting(UpdateLogSettingRequest) returns (UpdateLogSettingReply) {
    option (google.api.http) = {
      post: "/v1/admin/log/setting"
      body: "*"
    };
  }
}

message FilterLogParams {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string search = 5;
}

message FilterBalanceLogRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string user_id = 5;
}

message BalanceLog {
  int32 type = 1;
  string user_id = 2;
  string amount = 3;
  string order_no = 4;
  string balance = 5;
  string timestamp = 6;
}

message FilterBalanceLogData {
  int32 total = 1;
  repeated BalanceLog list = 2;
}

message FilterBalanceLogReply {
  int32 code = 1;
  string message = 2;
  FilterBalanceLogData data = 3;
}

message FilterCommissionLogRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string user_id = 5;
}

message CommissionLog {
  int32 type = 1;
  string user_id = 2;
  string amount = 3;
  string order_no = 4;
  string timestamp = 5;
}

message FilterCommissionLogData {
  int32 total = 1;
  repeated CommissionLog list = 2;
}

message FilterCommissionLogReply {
  int32 code = 1;
  string message = 2;
  FilterCommissionLogData data = 3;
}

message FilterEmailLogRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string search = 5;
}

message EmailLog {
  string id = 1;
  int32 type = 2;
  string platform = 3;
  string to = 4;
  string subject = 5;
  string content = 6;
  int32 status = 7;
  string created_at = 8;
}

message FilterEmailLogData {
  int32 total = 1;
  repeated EmailLog list = 2;
}

message FilterEmailLogReply {
  int32 code = 1;
  string message = 2;
  FilterEmailLogData data = 3;
}

message FilterGiftLogRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string user_id = 5;
}

message GiftLog {
  int32 type = 1;
  string user_id = 2;
  string order_no = 3;
  string subscribe_id = 4;
  string amount = 5;
  string balance = 6;
  string remark = 7;
  string timestamp = 8;
}

message FilterGiftLogData {
  int32 total = 1;
  repeated GiftLog list = 2;
}

message FilterGiftLogReply {
  int32 code = 1;
  string message = 2;
  FilterGiftLogData data = 3;
}

message FilterLoginLogRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string user_id = 5;
}

message LoginLog {
  string user_id = 1;
  string method = 2;
  string login_ip = 3;
  string user_agent = 4;
  bool success = 5;
  string timestamp = 6;
}

message FilterLoginLogData {
  int32 total = 1;
  repeated LoginLog list = 2;
}

message FilterLoginLogReply {
  int32 code = 1;
  string message = 2;
  FilterLoginLogData data = 3;
}

message GetMessageLogListRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  int32 type = 4;
  string search = 5;
}

message MessageLog {
  string id = 1;
  int32 type = 2;
  string platform = 3;
  string to = 4;
  string subject = 5;
  string content = 6;
  int32 status = 7;
  string created_at = 8;
}

message GetMessageLogListData {
  int32 total = 1;
  repeated MessageLog list = 2;
}

message GetMessageLogListReply {
  int32 code = 1;
  string message = 2;
  GetMessageLogListData data = 3;
}

message FilterMobileLogRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string search = 5;
}

message MobileLog {
  string id = 1;
  int32 type = 2;
  string platform = 3;
  string to = 4;
  string subject = 5;
  string content = 6;
  int32 status = 7;
  string created_at = 8;
}

message FilterMobileLogData {
  int32 total = 1;
  repeated MobileLog list = 2;
}

message FilterMobileLogReply {
  int32 code = 1;
  string message = 2;
  FilterMobileLogData data = 3;
}

message FilterRegisterLogRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string user_id = 5;
}

message RegisterLog {
  string user_id = 1;
  string auth_method = 2;
  string identifier = 3;
  string register_ip = 4;
  string user_agent = 5;
  string timestamp = 6;
}

message FilterRegisterLogData {
  int32 total = 1;
  repeated RegisterLog list = 2;
}

message FilterRegisterLogReply {
  int32 code = 1;
  string message = 2;
  FilterRegisterLogData data = 3;
}

message FilterServerTrafficLogRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string server_id = 5;
}

message ServerTrafficLog {
  string server_id = 1;
  string upload = 2;
  string download = 3;
  string timestamp = 4;
}

message FilterServerTrafficLogData {
  int32 total = 1;
  repeated ServerTrafficLog list = 2;
}

message FilterServerTrafficLogReply {
  int32 code = 1;
  string message = 2;
  FilterServerTrafficLogData data = 3;
}

message FilterSubscribeLogRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string user_id = 5;
}

message SubscribeLog {
  string user_id = 1;
  string token = 2;
  string user_agent = 3;
  string client_ip = 4;
  int32 user_subscribe_id = 5;
  string timestamp = 6;
}

message FilterSubscribeLogData {
  int32 total = 1;
  repeated SubscribeLog list = 2;
}

message FilterSubscribeLogReply {
  int32 code = 1;
  string message = 2;
  FilterSubscribeLogData data = 3;
}

message FilterResetSubscribeLogRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string user_id = 5;
}

message ResetSubscribeLog {
  int32 type = 1;
  string user_id = 2;
  int32 user_subscribe_id = 3;
  string order_no = 4;
  string timestamp = 5;
}

message FilterResetSubscribeLogData {
  int32 total = 1;
  repeated ResetSubscribeLog list = 2;
}

message FilterResetSubscribeLogReply {
  int32 code = 1;
  string message = 2;
  FilterResetSubscribeLogData data = 3;
}

message FilterUserSubscribeTrafficLogRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string date = 4;
  string user_id = 5;
  string subscribe_id = 6;
}

message UserSubscribeTrafficLog {
  string user_id = 1;
  string subscribe_id = 2;
  string upload = 3;
  string download = 4;
  string timestamp = 5;
}

message FilterUserSubscribeTrafficLogData {
  int32 total = 1;
  repeated UserSubscribeTrafficLog list = 2;
}

message FilterUserSubscribeTrafficLogReply {
  int32 code = 1;
  string message = 2;
  FilterUserSubscribeTrafficLogData data = 3;
}

message FilterTrafficLogDetailsRequest {
  reserved 1;
  int32 page = 2;
  int32 size = 3;
  string server_id = 4;
  string user_id = 5;
  string subscribe_id = 6;
  string start_time = 7;
  int32 end_time = 8;
}

message TrafficLogDetail {
  string id = 1;
  string server_id = 2;
  string user_id = 3;
  string subscribe_id = 4;
  string download = 5;
  string upload = 6;
  string timestamp = 7;
}

message FilterTrafficLogDetailsData {
  int32 total = 1;
  repeated TrafficLogDetail list = 2;
}

message FilterTrafficLogDetailsReply {
  int32 code = 1;
  string message = 2;
  FilterTrafficLogDetailsData data = 3;
}

message GetLogSettingRequest {}

message LogSetting {
  bool auto_clear = 1;
  int32 clear_days = 2;
}

message GetLogSettingReply {
  int32 code = 1;
  string message = 2;
  LogSetting data = 3;
}

message UpdateLogSettingRequest {
  bool auto_clear = 1;
  int32 clear_days = 2;
}

message UpdateLogSettingReply {
  int32 code = 1;
  string message = 2;
}
