// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.19.4
// source: admin/log/v1/log.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLogServiceFilterBalanceLog = "/api.admin.log.v1.LogService/FilterBalanceLog"
const OperationLogServiceFilterCommissionLog = "/api.admin.log.v1.LogService/FilterCommissionLog"
const OperationLogServiceFilterEmailLog = "/api.admin.log.v1.LogService/FilterEmailLog"
const OperationLogServiceFilterGiftLog = "/api.admin.log.v1.LogService/FilterGiftLog"
const OperationLogServiceFilterLoginLog = "/api.admin.log.v1.LogService/FilterLoginLog"
const OperationLogServiceFilterMobileLog = "/api.admin.log.v1.LogService/FilterMobileLog"
const OperationLogServiceFilterRegisterLog = "/api.admin.log.v1.LogService/FilterRegisterLog"
const OperationLogServiceFilterResetSubscribeLog = "/api.admin.log.v1.LogService/FilterResetSubscribeLog"
const OperationLogServiceFilterServerTrafficLog = "/api.admin.log.v1.LogService/FilterServerTrafficLog"
const OperationLogServiceFilterSubscribeLog = "/api.admin.log.v1.LogService/FilterSubscribeLog"
const OperationLogServiceFilterTrafficLogDetails = "/api.admin.log.v1.LogService/FilterTrafficLogDetails"
const OperationLogServiceFilterUserSubscribeTrafficLog = "/api.admin.log.v1.LogService/FilterUserSubscribeTrafficLog"
const OperationLogServiceGetLogSetting = "/api.admin.log.v1.LogService/GetLogSetting"
const OperationLogServiceGetMessageLogList = "/api.admin.log.v1.LogService/GetMessageLogList"
const OperationLogServiceUpdateLogSetting = "/api.admin.log.v1.LogService/UpdateLogSetting"

type LogServiceHTTPServer interface {
	// FilterBalanceLog System Log APIs (proxy_system_log table)
	FilterBalanceLog(context.Context, *FilterBalanceLogRequest) (*FilterBalanceLogReply, error)
	FilterCommissionLog(context.Context, *FilterCommissionLogRequest) (*FilterCommissionLogReply, error)
	FilterEmailLog(context.Context, *FilterEmailLogRequest) (*FilterEmailLogReply, error)
	FilterGiftLog(context.Context, *FilterGiftLogRequest) (*FilterGiftLogReply, error)
	FilterLoginLog(context.Context, *FilterLoginLogRequest) (*FilterLoginLogReply, error)
	FilterMobileLog(context.Context, *FilterMobileLogRequest) (*FilterMobileLogReply, error)
	FilterRegisterLog(context.Context, *FilterRegisterLogRequest) (*FilterRegisterLogReply, error)
	FilterResetSubscribeLog(context.Context, *FilterResetSubscribeLogRequest) (*FilterResetSubscribeLogReply, error)
	FilterServerTrafficLog(context.Context, *FilterServerTrafficLogRequest) (*FilterServerTrafficLogReply, error)
	FilterSubscribeLog(context.Context, *FilterSubscribeLogRequest) (*FilterSubscribeLogReply, error)
	// FilterTrafficLogDetails Traffic Log APIs (proxy_traffic_log table)
	FilterTrafficLogDetails(context.Context, *FilterTrafficLogDetailsRequest) (*FilterTrafficLogDetailsReply, error)
	FilterUserSubscribeTrafficLog(context.Context, *FilterUserSubscribeTrafficLogRequest) (*FilterUserSubscribeTrafficLogReply, error)
	// GetLogSetting Log Setting APIs (proxy_system table)
	GetLogSetting(context.Context, *GetLogSettingRequest) (*GetLogSettingReply, error)
	GetMessageLogList(context.Context, *GetMessageLogListRequest) (*GetMessageLogListReply, error)
	UpdateLogSetting(context.Context, *UpdateLogSettingRequest) (*UpdateLogSettingReply, error)
}

func RegisterLogServiceHTTPServer(s *http.Server, srv LogServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/admin/log/balance/list", _LogService_FilterBalanceLog0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/commission/list", _LogService_FilterCommissionLog0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/email/list", _LogService_FilterEmailLog0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/gift/list", _LogService_FilterGiftLog0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/login/list", _LogService_FilterLoginLog0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/message/list", _LogService_GetMessageLogList0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/mobile/list", _LogService_FilterMobileLog0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/register/list", _LogService_FilterRegisterLog0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/server/traffic/list", _LogService_FilterServerTrafficLog0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/subscribe/list", _LogService_FilterSubscribeLog0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/subscribe/reset/list", _LogService_FilterResetSubscribeLog0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/subscribe/traffic/list", _LogService_FilterUserSubscribeTrafficLog0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/traffic/details", _LogService_FilterTrafficLogDetails0_HTTP_Handler(srv))
	r.GET("/v1/admin/log/setting", _LogService_GetLogSetting0_HTTP_Handler(srv))
	r.POST("/v1/admin/log/setting", _LogService_UpdateLogSetting0_HTTP_Handler(srv))
}

func _LogService_FilterBalanceLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterBalanceLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterBalanceLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterBalanceLog(ctx, req.(*FilterBalanceLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterBalanceLogReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_FilterCommissionLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterCommissionLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterCommissionLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterCommissionLog(ctx, req.(*FilterCommissionLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterCommissionLogReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_FilterEmailLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterEmailLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterEmailLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterEmailLog(ctx, req.(*FilterEmailLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterEmailLogReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_FilterGiftLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterGiftLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterGiftLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterGiftLog(ctx, req.(*FilterGiftLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterGiftLogReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_FilterLoginLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterLoginLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterLoginLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterLoginLog(ctx, req.(*FilterLoginLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterLoginLogReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_GetMessageLogList0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMessageLogListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceGetMessageLogList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMessageLogList(ctx, req.(*GetMessageLogListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMessageLogListReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_FilterMobileLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterMobileLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterMobileLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterMobileLog(ctx, req.(*FilterMobileLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterMobileLogReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_FilterRegisterLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterRegisterLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterRegisterLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterRegisterLog(ctx, req.(*FilterRegisterLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterRegisterLogReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_FilterServerTrafficLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterServerTrafficLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterServerTrafficLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterServerTrafficLog(ctx, req.(*FilterServerTrafficLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterServerTrafficLogReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_FilterSubscribeLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterSubscribeLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterSubscribeLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterSubscribeLog(ctx, req.(*FilterSubscribeLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterSubscribeLogReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_FilterResetSubscribeLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterResetSubscribeLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterResetSubscribeLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterResetSubscribeLog(ctx, req.(*FilterResetSubscribeLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterResetSubscribeLogReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_FilterUserSubscribeTrafficLog0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterUserSubscribeTrafficLogRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterUserSubscribeTrafficLog)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterUserSubscribeTrafficLog(ctx, req.(*FilterUserSubscribeTrafficLogRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterUserSubscribeTrafficLogReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_FilterTrafficLogDetails0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FilterTrafficLogDetailsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceFilterTrafficLogDetails)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FilterTrafficLogDetails(ctx, req.(*FilterTrafficLogDetailsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FilterTrafficLogDetailsReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_GetLogSetting0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLogSettingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceGetLogSetting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLogSetting(ctx, req.(*GetLogSettingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLogSettingReply)
		return ctx.Result(200, reply)
	}
}

func _LogService_UpdateLogSetting0_HTTP_Handler(srv LogServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateLogSettingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogServiceUpdateLogSetting)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateLogSetting(ctx, req.(*UpdateLogSettingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateLogSettingReply)
		return ctx.Result(200, reply)
	}
}

type LogServiceHTTPClient interface {
	// FilterBalanceLog System Log APIs (proxy_system_log table)
	FilterBalanceLog(ctx context.Context, req *FilterBalanceLogRequest, opts ...http.CallOption) (rsp *FilterBalanceLogReply, err error)
	FilterCommissionLog(ctx context.Context, req *FilterCommissionLogRequest, opts ...http.CallOption) (rsp *FilterCommissionLogReply, err error)
	FilterEmailLog(ctx context.Context, req *FilterEmailLogRequest, opts ...http.CallOption) (rsp *FilterEmailLogReply, err error)
	FilterGiftLog(ctx context.Context, req *FilterGiftLogRequest, opts ...http.CallOption) (rsp *FilterGiftLogReply, err error)
	FilterLoginLog(ctx context.Context, req *FilterLoginLogRequest, opts ...http.CallOption) (rsp *FilterLoginLogReply, err error)
	FilterMobileLog(ctx context.Context, req *FilterMobileLogRequest, opts ...http.CallOption) (rsp *FilterMobileLogReply, err error)
	FilterRegisterLog(ctx context.Context, req *FilterRegisterLogRequest, opts ...http.CallOption) (rsp *FilterRegisterLogReply, err error)
	FilterResetSubscribeLog(ctx context.Context, req *FilterResetSubscribeLogRequest, opts ...http.CallOption) (rsp *FilterResetSubscribeLogReply, err error)
	FilterServerTrafficLog(ctx context.Context, req *FilterServerTrafficLogRequest, opts ...http.CallOption) (rsp *FilterServerTrafficLogReply, err error)
	FilterSubscribeLog(ctx context.Context, req *FilterSubscribeLogRequest, opts ...http.CallOption) (rsp *FilterSubscribeLogReply, err error)
	// FilterTrafficLogDetails Traffic Log APIs (proxy_traffic_log table)
	FilterTrafficLogDetails(ctx context.Context, req *FilterTrafficLogDetailsRequest, opts ...http.CallOption) (rsp *FilterTrafficLogDetailsReply, err error)
	FilterUserSubscribeTrafficLog(ctx context.Context, req *FilterUserSubscribeTrafficLogRequest, opts ...http.CallOption) (rsp *FilterUserSubscribeTrafficLogReply, err error)
	// GetLogSetting Log Setting APIs (proxy_system table)
	GetLogSetting(ctx context.Context, req *GetLogSettingRequest, opts ...http.CallOption) (rsp *GetLogSettingReply, err error)
	GetMessageLogList(ctx context.Context, req *GetMessageLogListRequest, opts ...http.CallOption) (rsp *GetMessageLogListReply, err error)
	UpdateLogSetting(ctx context.Context, req *UpdateLogSettingRequest, opts ...http.CallOption) (rsp *UpdateLogSettingReply, err error)
}

type LogServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewLogServiceHTTPClient(client *http.Client) LogServiceHTTPClient {
	return &LogServiceHTTPClientImpl{client}
}

// FilterBalanceLog System Log APIs (proxy_system_log table)
func (c *LogServiceHTTPClientImpl) FilterBalanceLog(ctx context.Context, in *FilterBalanceLogRequest, opts ...http.CallOption) (*FilterBalanceLogReply, error) {
	var out FilterBalanceLogReply
	pattern := "/v1/admin/log/balance/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterBalanceLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) FilterCommissionLog(ctx context.Context, in *FilterCommissionLogRequest, opts ...http.CallOption) (*FilterCommissionLogReply, error) {
	var out FilterCommissionLogReply
	pattern := "/v1/admin/log/commission/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterCommissionLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) FilterEmailLog(ctx context.Context, in *FilterEmailLogRequest, opts ...http.CallOption) (*FilterEmailLogReply, error) {
	var out FilterEmailLogReply
	pattern := "/v1/admin/log/email/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterEmailLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) FilterGiftLog(ctx context.Context, in *FilterGiftLogRequest, opts ...http.CallOption) (*FilterGiftLogReply, error) {
	var out FilterGiftLogReply
	pattern := "/v1/admin/log/gift/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterGiftLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) FilterLoginLog(ctx context.Context, in *FilterLoginLogRequest, opts ...http.CallOption) (*FilterLoginLogReply, error) {
	var out FilterLoginLogReply
	pattern := "/v1/admin/log/login/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterLoginLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) FilterMobileLog(ctx context.Context, in *FilterMobileLogRequest, opts ...http.CallOption) (*FilterMobileLogReply, error) {
	var out FilterMobileLogReply
	pattern := "/v1/admin/log/mobile/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterMobileLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) FilterRegisterLog(ctx context.Context, in *FilterRegisterLogRequest, opts ...http.CallOption) (*FilterRegisterLogReply, error) {
	var out FilterRegisterLogReply
	pattern := "/v1/admin/log/register/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterRegisterLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) FilterResetSubscribeLog(ctx context.Context, in *FilterResetSubscribeLogRequest, opts ...http.CallOption) (*FilterResetSubscribeLogReply, error) {
	var out FilterResetSubscribeLogReply
	pattern := "/v1/admin/log/subscribe/reset/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterResetSubscribeLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) FilterServerTrafficLog(ctx context.Context, in *FilterServerTrafficLogRequest, opts ...http.CallOption) (*FilterServerTrafficLogReply, error) {
	var out FilterServerTrafficLogReply
	pattern := "/v1/admin/log/server/traffic/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterServerTrafficLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) FilterSubscribeLog(ctx context.Context, in *FilterSubscribeLogRequest, opts ...http.CallOption) (*FilterSubscribeLogReply, error) {
	var out FilterSubscribeLogReply
	pattern := "/v1/admin/log/subscribe/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterSubscribeLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// FilterTrafficLogDetails Traffic Log APIs (proxy_traffic_log table)
func (c *LogServiceHTTPClientImpl) FilterTrafficLogDetails(ctx context.Context, in *FilterTrafficLogDetailsRequest, opts ...http.CallOption) (*FilterTrafficLogDetailsReply, error) {
	var out FilterTrafficLogDetailsReply
	pattern := "/v1/admin/log/traffic/details"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterTrafficLogDetails))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) FilterUserSubscribeTrafficLog(ctx context.Context, in *FilterUserSubscribeTrafficLogRequest, opts ...http.CallOption) (*FilterUserSubscribeTrafficLogReply, error) {
	var out FilterUserSubscribeTrafficLogReply
	pattern := "/v1/admin/log/subscribe/traffic/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceFilterUserSubscribeTrafficLog))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetLogSetting Log Setting APIs (proxy_system table)
func (c *LogServiceHTTPClientImpl) GetLogSetting(ctx context.Context, in *GetLogSettingRequest, opts ...http.CallOption) (*GetLogSettingReply, error) {
	var out GetLogSettingReply
	pattern := "/v1/admin/log/setting"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceGetLogSetting))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) GetMessageLogList(ctx context.Context, in *GetMessageLogListRequest, opts ...http.CallOption) (*GetMessageLogListReply, error) {
	var out GetMessageLogListReply
	pattern := "/v1/admin/log/message/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLogServiceGetMessageLogList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LogServiceHTTPClientImpl) UpdateLogSetting(ctx context.Context, in *UpdateLogSettingRequest, opts ...http.CallOption) (*UpdateLogSettingReply, error) {
	var out UpdateLogSettingReply
	pattern := "/v1/admin/log/setting"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLogServiceUpdateLogSetting))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
