// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.19.4
// source: public/redemption/v1/redemption.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRedemptionServiceRedeemCode = "/api.public.redemption.v1.RedemptionService/RedeemCode"

type RedemptionServiceHTTPServer interface {
	// RedeemCode RedeemCode 兑换兑换码
	RedeemCode(context.Context, *RedeemCodeRequest) (*RedeemCodeReply, error)
}

func RegisterRedemptionServiceHTTPServer(s *http.Server, srv RedemptionServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/public/redemption", _RedemptionService_RedeemCode0_HTTP_Handler(srv))
}

func _RedemptionService_RedeemCode0_HTTP_Handler(srv RedemptionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RedeemCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRedemptionServiceRedeemCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RedeemCode(ctx, req.(*RedeemCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RedeemCodeReply)
		return ctx.Result(200, reply)
	}
}

type RedemptionServiceHTTPClient interface {
	// RedeemCode RedeemCode 兑换兑换码
	RedeemCode(ctx context.Context, req *RedeemCodeRequest, opts ...http.CallOption) (rsp *RedeemCodeReply, err error)
}

type RedemptionServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRedemptionServiceHTTPClient(client *http.Client) RedemptionServiceHTTPClient {
	return &RedemptionServiceHTTPClientImpl{client}
}

// RedeemCode RedeemCode 兑换兑换码
func (c *RedemptionServiceHTTPClientImpl) RedeemCode(ctx context.Context, in *RedeemCodeRequest, opts ...http.CallOption) (*RedeemCodeReply, error) {
	var out RedeemCodeReply
	pattern := "/v1/public/redemption"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRedemptionServiceRedeemCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
