// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.19.4
// source: admin/application/v1/application.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSubscribeApplicationServiceCreateSubscribeApplication = "/api.admin.application.v1.SubscribeApplicationService/CreateSubscribeApplication"
const OperationSubscribeApplicationServiceDeleteSubscribeApplication = "/api.admin.application.v1.SubscribeApplicationService/DeleteSubscribeApplication"
const OperationSubscribeApplicationServiceGetSubscribeApplicationList = "/api.admin.application.v1.SubscribeApplicationService/GetSubscribeApplicationList"
const OperationSubscribeApplicationServicePreviewSubscribeTemplate = "/api.admin.application.v1.SubscribeApplicationService/PreviewSubscribeTemplate"
const OperationSubscribeApplicationServiceUpdateSubscribeApplication = "/api.admin.application.v1.SubscribeApplicationService/UpdateSubscribeApplication"

type SubscribeApplicationServiceHTTPServer interface {
	// CreateSubscribeApplication 创建订阅应用配置
	CreateSubscribeApplication(context.Context, *CreateSubscribeApplicationRequest) (*SubscribeApplicationReply, error)
	// DeleteSubscribeApplication 删除订阅应用配置
	DeleteSubscribeApplication(context.Context, *DeleteSubscribeApplicationRequest) (*DeleteSubscribeApplicationReply, error)
	// GetSubscribeApplicationList 获取订阅应用配置列表
	GetSubscribeApplicationList(context.Context, *GetSubscribeApplicationListRequest) (*GetSubscribeApplicationListReply, error)
	// PreviewSubscribeTemplate 预览订阅模板
	PreviewSubscribeTemplate(context.Context, *PreviewSubscribeTemplateRequest) (*PreviewSubscribeTemplateReply, error)
	// UpdateSubscribeApplication 更新订阅应用配置
	UpdateSubscribeApplication(context.Context, *UpdateSubscribeApplicationRequest) (*SubscribeApplicationReply, error)
}

func RegisterSubscribeApplicationServiceHTTPServer(s *http.Server, srv SubscribeApplicationServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/admin/application", _SubscribeApplicationService_CreateSubscribeApplication0_HTTP_Handler(srv))
	r.GET("/v1/admin/application/preview", _SubscribeApplicationService_PreviewSubscribeTemplate0_HTTP_Handler(srv))
	r.PUT("/v1/admin/application/subscribe_application", _SubscribeApplicationService_UpdateSubscribeApplication0_HTTP_Handler(srv))
	r.DELETE("/v1/admin/application/subscribe_application", _SubscribeApplicationService_DeleteSubscribeApplication0_HTTP_Handler(srv))
	r.GET("/v1/admin/application/subscribe_application_list", _SubscribeApplicationService_GetSubscribeApplicationList0_HTTP_Handler(srv))
}

func _SubscribeApplicationService_CreateSubscribeApplication0_HTTP_Handler(srv SubscribeApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSubscribeApplicationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscribeApplicationServiceCreateSubscribeApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSubscribeApplication(ctx, req.(*CreateSubscribeApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubscribeApplicationReply)
		return ctx.Result(200, reply)
	}
}

func _SubscribeApplicationService_PreviewSubscribeTemplate0_HTTP_Handler(srv SubscribeApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PreviewSubscribeTemplateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscribeApplicationServicePreviewSubscribeTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreviewSubscribeTemplate(ctx, req.(*PreviewSubscribeTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreviewSubscribeTemplateReply)
		return ctx.Result(200, reply)
	}
}

func _SubscribeApplicationService_UpdateSubscribeApplication0_HTTP_Handler(srv SubscribeApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSubscribeApplicationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscribeApplicationServiceUpdateSubscribeApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSubscribeApplication(ctx, req.(*UpdateSubscribeApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubscribeApplicationReply)
		return ctx.Result(200, reply)
	}
}

func _SubscribeApplicationService_DeleteSubscribeApplication0_HTTP_Handler(srv SubscribeApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSubscribeApplicationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscribeApplicationServiceDeleteSubscribeApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSubscribeApplication(ctx, req.(*DeleteSubscribeApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSubscribeApplicationReply)
		return ctx.Result(200, reply)
	}
}

func _SubscribeApplicationService_GetSubscribeApplicationList0_HTTP_Handler(srv SubscribeApplicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSubscribeApplicationListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSubscribeApplicationServiceGetSubscribeApplicationList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSubscribeApplicationList(ctx, req.(*GetSubscribeApplicationListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSubscribeApplicationListReply)
		return ctx.Result(200, reply)
	}
}

type SubscribeApplicationServiceHTTPClient interface {
	// CreateSubscribeApplication 创建订阅应用配置
	CreateSubscribeApplication(ctx context.Context, req *CreateSubscribeApplicationRequest, opts ...http.CallOption) (rsp *SubscribeApplicationReply, err error)
	// DeleteSubscribeApplication 删除订阅应用配置
	DeleteSubscribeApplication(ctx context.Context, req *DeleteSubscribeApplicationRequest, opts ...http.CallOption) (rsp *DeleteSubscribeApplicationReply, err error)
	// GetSubscribeApplicationList 获取订阅应用配置列表
	GetSubscribeApplicationList(ctx context.Context, req *GetSubscribeApplicationListRequest, opts ...http.CallOption) (rsp *GetSubscribeApplicationListReply, err error)
	// PreviewSubscribeTemplate 预览订阅模板
	PreviewSubscribeTemplate(ctx context.Context, req *PreviewSubscribeTemplateRequest, opts ...http.CallOption) (rsp *PreviewSubscribeTemplateReply, err error)
	// UpdateSubscribeApplication 更新订阅应用配置
	UpdateSubscribeApplication(ctx context.Context, req *UpdateSubscribeApplicationRequest, opts ...http.CallOption) (rsp *SubscribeApplicationReply, err error)
}

type SubscribeApplicationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSubscribeApplicationServiceHTTPClient(client *http.Client) SubscribeApplicationServiceHTTPClient {
	return &SubscribeApplicationServiceHTTPClientImpl{client}
}

// CreateSubscribeApplication 创建订阅应用配置
func (c *SubscribeApplicationServiceHTTPClientImpl) CreateSubscribeApplication(ctx context.Context, in *CreateSubscribeApplicationRequest, opts ...http.CallOption) (*SubscribeApplicationReply, error) {
	var out SubscribeApplicationReply
	pattern := "/v1/admin/application"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscribeApplicationServiceCreateSubscribeApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSubscribeApplication 删除订阅应用配置
func (c *SubscribeApplicationServiceHTTPClientImpl) DeleteSubscribeApplication(ctx context.Context, in *DeleteSubscribeApplicationRequest, opts ...http.CallOption) (*DeleteSubscribeApplicationReply, error) {
	var out DeleteSubscribeApplicationReply
	pattern := "/v1/admin/application/subscribe_application"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscribeApplicationServiceDeleteSubscribeApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSubscribeApplicationList 获取订阅应用配置列表
func (c *SubscribeApplicationServiceHTTPClientImpl) GetSubscribeApplicationList(ctx context.Context, in *GetSubscribeApplicationListRequest, opts ...http.CallOption) (*GetSubscribeApplicationListReply, error) {
	var out GetSubscribeApplicationListReply
	pattern := "/v1/admin/application/subscribe_application_list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscribeApplicationServiceGetSubscribeApplicationList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PreviewSubscribeTemplate 预览订阅模板
func (c *SubscribeApplicationServiceHTTPClientImpl) PreviewSubscribeTemplate(ctx context.Context, in *PreviewSubscribeTemplateRequest, opts ...http.CallOption) (*PreviewSubscribeTemplateReply, error) {
	var out PreviewSubscribeTemplateReply
	pattern := "/v1/admin/application/preview"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSubscribeApplicationServicePreviewSubscribeTemplate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateSubscribeApplication 更新订阅应用配置
func (c *SubscribeApplicationServiceHTTPClientImpl) UpdateSubscribeApplication(ctx context.Context, in *UpdateSubscribeApplicationRequest, opts ...http.CallOption) (*SubscribeApplicationReply, error) {
	var out SubscribeApplicationReply
	pattern := "/v1/admin/application/subscribe_application"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSubscribeApplicationServiceUpdateSubscribeApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
