// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: api/public/subscribe/v1/subscribe.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Subscribe_QuerySubscribeList_FullMethodName = "/api.public.subscribe.v1.Subscribe/QuerySubscribeList"
)

// SubscribeClient is the client API for Subscribe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Public Subscribe service
// 公共订阅服务（需要认证）
type SubscribeClient interface {
	// QuerySubscribeList 查询订阅列表
	QuerySubscribeList(ctx context.Context, in *QuerySubscribeListRequest, opts ...grpc.CallOption) (*SubscribeListReply, error)
}

type subscribeClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscribeClient(cc grpc.ClientConnInterface) SubscribeClient {
	return &subscribeClient{cc}
}

func (c *subscribeClient) QuerySubscribeList(ctx context.Context, in *QuerySubscribeListRequest, opts ...grpc.CallOption) (*SubscribeListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeListReply)
	err := c.cc.Invoke(ctx, Subscribe_QuerySubscribeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscribeServer is the server API for Subscribe service.
// All implementations must embed UnimplementedSubscribeServer
// for forward compatibility.
//
// Public Subscribe service
// 公共订阅服务（需要认证）
type SubscribeServer interface {
	// QuerySubscribeList 查询订阅列表
	QuerySubscribeList(context.Context, *QuerySubscribeListRequest) (*SubscribeListReply, error)
	mustEmbedUnimplementedSubscribeServer()
}

// UnimplementedSubscribeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscribeServer struct{}

func (UnimplementedSubscribeServer) QuerySubscribeList(context.Context, *QuerySubscribeListRequest) (*SubscribeListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QuerySubscribeList not implemented")
}
func (UnimplementedSubscribeServer) mustEmbedUnimplementedSubscribeServer() {}
func (UnimplementedSubscribeServer) testEmbeddedByValue()                   {}

// UnsafeSubscribeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscribeServer will
// result in compilation errors.
type UnsafeSubscribeServer interface {
	mustEmbedUnimplementedSubscribeServer()
}

func RegisterSubscribeServer(s grpc.ServiceRegistrar, srv SubscribeServer) {
	// If the following call panics, it indicates UnimplementedSubscribeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Subscribe_ServiceDesc, srv)
}

func _Subscribe_QuerySubscribeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySubscribeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscribeServer).QuerySubscribeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscribe_QuerySubscribeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscribeServer).QuerySubscribeList(ctx, req.(*QuerySubscribeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Subscribe_ServiceDesc is the grpc.ServiceDesc for Subscribe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subscribe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.public.subscribe.v1.Subscribe",
	HandlerType: (*SubscribeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuerySubscribeList",
			Handler:    _Subscribe_QuerySubscribeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/public/subscribe/v1/subscribe.proto",
}
