syntax = "proto3";

package api.public.subscribe.v1;

option go_package = "github.com/OmnTeam/ppanel-pro/api/public/subscribe/v1;v1";

import "google/api/annotations.proto";

// Public Subscribe service
// 公共订阅服务（需要认证）
service Subscribe {
  // QuerySubscribeList 查询订阅列表
  rpc QuerySubscribeList (QuerySubscribeListRequest) returns (SubscribeListReply) {
    option (google.api.http) = {
      get: "/v1/public/subscribe/list"
    };
  }

  // QueryUserSubscribeNodeList 查询当前用户订阅节点列表
  rpc QueryUserSubscribeNodeList (QueryUserSubscribeNodeListRequest) returns (QueryUserSubscribeNodeListReply) {
    option (google.api.http) = {
      get: "/v1/public/subscribe/node/list"
    };
  }
}

// QuerySubscribeListRequest 查询订阅列表请求
message QuerySubscribeListRequest {
  string language = 1;  // 语言
}

// SubscribeListData 订阅列表数据
message SubscribeListData {
  repeated SubscribeItem list = 1;
  int32 total = 2;
}

// SubscribeListReply 查询订阅列表响应
message SubscribeListReply {
  int32 code = 1;              // 状态码
  string message = 2;          // 消息内容
  SubscribeListData data = 3;  // 响应数据
}

// SubscribeItem 订阅项
message SubscribeItem {
  string id = 1;
  string name = 2;
  string language = 3;
  string description = 4;
  string unit_price = 5;
  string unit_time = 6;
  repeated SubscribeDiscount discount = 7;
  string replacement = 8;
  string inventory = 9;
  string traffic = 10;
  string speed_limit = 11;
  string device_limit = 12;
  string quota = 13;
  repeated int32 nodes = 14;
  repeated string node_tags = 15;
  bool show = 16;
  bool sell = 17;
  string sort = 18;
  string deduction_ratio = 19;
  bool allow_deduction = 20;
  int32 reset_cycle = 21;
  string created_at = 22;
  string updated_at = 23;
}

// SubscribeDiscount 订阅折扣
message SubscribeDiscount {
  int32 quantity = 1;
  int32 percentage = 2;
}

message QueryUserSubscribeNodeListRequest {}

message QueryUserSubscribeNodeListData {
  repeated UserSubscribeInfo list = 1;
}

message QueryUserSubscribeNodeListReply {
  int32 code = 1;
  string message = 2;
  QueryUserSubscribeNodeListData data = 3;
}

message UserSubscribeInfo {
  string id = 1;
  string user_id = 2;
  string order_id = 3;
  string subscribe_id = 4;
  int64 start_time = 5;
  int64 expire_time = 6;
  int64 finished_at = 7;
  int64 reset_time = 8;
  int64 traffic = 9;
  int64 download = 10;
  int64 upload = 11;
  string token = 12;
  int32 status = 13;
  int64 created_at = 14;
  int64 updated_at = 15;
  bool is_try_out = 16;
  repeated UserSubscribeNodeInfo nodes = 17;
}

message UserSubscribeNodeInfo {
  string id = 1;
  string name = 2;
  string uuid = 3;
  string protocol = 4;
  string protocols = 5;
  uint32 port = 6;
  string address = 7;
  repeated string tags = 8;
  string country = 9;
  string city = 10;
  string longitude = 11;
  string latitude = 12;
  string latitude_center = 13;
  string longitude_center = 14;
  int64 created_at = 15;
}
