syntax = "proto3";

package api.admin.tool.v1;

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";

option go_package = "github.com/OmnTeam/npanel-pro/api/admin/tool/v1;v1";
option java_multiple_files = true;
option java_package = "api.admin.tool.v1";

service Tool {
  // GetSystemLog 获取系统日志
  rpc GetSystemLog (GetSystemLogRequest) returns (GetSystemLogReply) {
    option (google.api.http) = {
      get: "/v1/admin/tool/log"
    };
  }

  // RestartSystem 重启系统
  rpc RestartSystem (RestartSystemRequest) returns (RestartSystemReply) {
    option (google.api.http) = {
      get: "/v1/admin/tool/restart"
    };
  }

  // GetVersion 获取版本信息
  rpc GetVersion (GetVersionRequest) returns (GetVersionReply) {
    option (google.api.http) = {
      get: "/v1/admin/tool/version"
    };
  }

  // QueryIPLocation 查询IP地理位置
  rpc QueryIPLocation (QueryIPLocationRequest) returns (QueryIPLocationReply) {
    option (google.api.http) = {
      get: "/v1/admin/tool/ip/location"
    };
  }
}

// ==================== Messages ====================

// GetSystemLogRequest 获取系统日志请求
message GetSystemLogRequest {}

message LogResponse {
  repeated google.protobuf.Struct list = 1;
}

// GetSystemLogReply 获取系统日志响应
message GetSystemLogReply {
  int32 code = 1;
  string message = 2;
  LogResponse data = 3;
}

// RestartSystemRequest 重启系统请求
message RestartSystemRequest {}

// RestartSystemReply 重启系统响应
message RestartSystemReply {
  int32 code = 1;
  string message = 2;
}

// GetVersionRequest 获取版本信息请求
message GetVersionRequest {}

message VersionResponse {
  string version = 1;
}

// GetVersionReply 获取版本信息响应
message GetVersionReply {
  int32 code = 1;
  string message = 2;
  VersionResponse data = 3;
}

// QueryIPLocationRequest 查询IP地理位置请求
message QueryIPLocationRequest {
  string ip = 1;
}

message QueryIPLocationResponse {
  string country = 1;
  string region = 2;
  string city = 3;
}

message QueryIPLocationReply {
  int32 code = 1;
  string message = 2;
  QueryIPLocationResponse data = 3;
}
