// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: public/document/v1/document.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Document_QueryDocumentList_FullMethodName   = "/api.public.document.v1.Document/QueryDocumentList"
	Document_QueryDocumentDetail_FullMethodName = "/api.public.document.v1.Document/QueryDocumentDetail"
)

// DocumentClient is the client API for Document service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Public Document service
// 公共文档服务（需要认证）
type DocumentClient interface {
	// QueryDocumentList 查询文档列表
	QueryDocumentList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DocumentListReply, error)
	// QueryDocumentDetail 查询文档详情
	QueryDocumentDetail(ctx context.Context, in *QueryDocumentDetailRequest, opts ...grpc.CallOption) (*DocumentDetailReply, error)
}

type documentClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentClient(cc grpc.ClientConnInterface) DocumentClient {
	return &documentClient{cc}
}

func (c *documentClient) QueryDocumentList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DocumentListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentListReply)
	err := c.cc.Invoke(ctx, Document_QueryDocumentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentClient) QueryDocumentDetail(ctx context.Context, in *QueryDocumentDetailRequest, opts ...grpc.CallOption) (*DocumentDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentDetailReply)
	err := c.cc.Invoke(ctx, Document_QueryDocumentDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServer is the server API for Document service.
// All implementations must embed UnimplementedDocumentServer
// for forward compatibility.
//
// Public Document service
// 公共文档服务（需要认证）
type DocumentServer interface {
	// QueryDocumentList 查询文档列表
	QueryDocumentList(context.Context, *emptypb.Empty) (*DocumentListReply, error)
	// QueryDocumentDetail 查询文档详情
	QueryDocumentDetail(context.Context, *QueryDocumentDetailRequest) (*DocumentDetailReply, error)
	mustEmbedUnimplementedDocumentServer()
}

// UnimplementedDocumentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentServer struct{}

func (UnimplementedDocumentServer) QueryDocumentList(context.Context, *emptypb.Empty) (*DocumentListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDocumentList not implemented")
}
func (UnimplementedDocumentServer) QueryDocumentDetail(context.Context, *QueryDocumentDetailRequest) (*DocumentDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDocumentDetail not implemented")
}
func (UnimplementedDocumentServer) mustEmbedUnimplementedDocumentServer() {}
func (UnimplementedDocumentServer) testEmbeddedByValue()                  {}

// UnsafeDocumentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentServer will
// result in compilation errors.
type UnsafeDocumentServer interface {
	mustEmbedUnimplementedDocumentServer()
}

func RegisterDocumentServer(s grpc.ServiceRegistrar, srv DocumentServer) {
	// If the following call pancis, it indicates UnimplementedDocumentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Document_ServiceDesc, srv)
}

func _Document_QueryDocumentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).QueryDocumentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Document_QueryDocumentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).QueryDocumentList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Document_QueryDocumentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDocumentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServer).QueryDocumentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Document_QueryDocumentDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServer).QueryDocumentDetail(ctx, req.(*QueryDocumentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Document_ServiceDesc is the grpc.ServiceDesc for Document service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Document_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.public.document.v1.Document",
	HandlerType: (*DocumentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDocumentList",
			Handler:    _Document_QueryDocumentList_Handler,
		},
		{
			MethodName: "QueryDocumentDetail",
			Handler:    _Document_QueryDocumentDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/document/v1/document.proto",
}
