// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: public/portal/v1/portal.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Portal_GetSubscription_FullMethodName            = "/api.public.portal.v1.Portal/GetSubscription"
	Portal_PrePurchaseOrder_FullMethodName           = "/api.public.portal.v1.Portal/PrePurchaseOrder"
	Portal_Purchase_FullMethodName                   = "/api.public.portal.v1.Portal/Purchase"
	Portal_GetAvailablePaymentMethods_FullMethodName = "/api.public.portal.v1.Portal/GetAvailablePaymentMethods"
	Portal_PurchaseCheckout_FullMethodName           = "/api.public.portal.v1.Portal/PurchaseCheckout"
	Portal_QueryPurchaseOrder_FullMethodName         = "/api.public.portal.v1.Portal/QueryPurchaseOrder"
)

// PortalClient is the client API for Portal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortalClient interface {
	GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionReply, error)
	PrePurchaseOrder(ctx context.Context, in *PrePurchaseOrderRequest, opts ...grpc.CallOption) (*PrePurchaseOrderReply, error)
	Purchase(ctx context.Context, in *PurchaseRequest, opts ...grpc.CallOption) (*PurchaseReply, error)
	GetAvailablePaymentMethods(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAvailablePaymentMethodsReply, error)
	PurchaseCheckout(ctx context.Context, in *PurchaseCheckoutRequest, opts ...grpc.CallOption) (*PurchaseCheckoutReply, error)
	QueryPurchaseOrder(ctx context.Context, in *QueryPurchaseOrderRequest, opts ...grpc.CallOption) (*QueryPurchaseOrderReply, error)
}

type portalClient struct {
	cc grpc.ClientConnInterface
}

func NewPortalClient(cc grpc.ClientConnInterface) PortalClient {
	return &portalClient{cc}
}

func (c *portalClient) GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubscriptionReply)
	err := c.cc.Invoke(ctx, Portal_GetSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portalClient) PrePurchaseOrder(ctx context.Context, in *PrePurchaseOrderRequest, opts ...grpc.CallOption) (*PrePurchaseOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrePurchaseOrderReply)
	err := c.cc.Invoke(ctx, Portal_PrePurchaseOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portalClient) Purchase(ctx context.Context, in *PurchaseRequest, opts ...grpc.CallOption) (*PurchaseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseReply)
	err := c.cc.Invoke(ctx, Portal_Purchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portalClient) GetAvailablePaymentMethods(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAvailablePaymentMethodsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailablePaymentMethodsReply)
	err := c.cc.Invoke(ctx, Portal_GetAvailablePaymentMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portalClient) PurchaseCheckout(ctx context.Context, in *PurchaseCheckoutRequest, opts ...grpc.CallOption) (*PurchaseCheckoutReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurchaseCheckoutReply)
	err := c.cc.Invoke(ctx, Portal_PurchaseCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portalClient) QueryPurchaseOrder(ctx context.Context, in *QueryPurchaseOrderRequest, opts ...grpc.CallOption) (*QueryPurchaseOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPurchaseOrderReply)
	err := c.cc.Invoke(ctx, Portal_QueryPurchaseOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortalServer is the server API for Portal service.
// All implementations must embed UnimplementedPortalServer
// for forward compatibility.
type PortalServer interface {
	GetSubscription(context.Context, *GetSubscriptionRequest) (*GetSubscriptionReply, error)
	PrePurchaseOrder(context.Context, *PrePurchaseOrderRequest) (*PrePurchaseOrderReply, error)
	Purchase(context.Context, *PurchaseRequest) (*PurchaseReply, error)
	GetAvailablePaymentMethods(context.Context, *emptypb.Empty) (*GetAvailablePaymentMethodsReply, error)
	PurchaseCheckout(context.Context, *PurchaseCheckoutRequest) (*PurchaseCheckoutReply, error)
	QueryPurchaseOrder(context.Context, *QueryPurchaseOrderRequest) (*QueryPurchaseOrderReply, error)
	mustEmbedUnimplementedPortalServer()
}

// UnimplementedPortalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortalServer struct{}

func (UnimplementedPortalServer) GetSubscription(context.Context, *GetSubscriptionRequest) (*GetSubscriptionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedPortalServer) PrePurchaseOrder(context.Context, *PrePurchaseOrderRequest) (*PrePurchaseOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrePurchaseOrder not implemented")
}
func (UnimplementedPortalServer) Purchase(context.Context, *PurchaseRequest) (*PurchaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Purchase not implemented")
}
func (UnimplementedPortalServer) GetAvailablePaymentMethods(context.Context, *emptypb.Empty) (*GetAvailablePaymentMethodsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailablePaymentMethods not implemented")
}
func (UnimplementedPortalServer) PurchaseCheckout(context.Context, *PurchaseCheckoutRequest) (*PurchaseCheckoutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchaseCheckout not implemented")
}
func (UnimplementedPortalServer) QueryPurchaseOrder(context.Context, *QueryPurchaseOrderRequest) (*QueryPurchaseOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPurchaseOrder not implemented")
}
func (UnimplementedPortalServer) mustEmbedUnimplementedPortalServer() {}
func (UnimplementedPortalServer) testEmbeddedByValue()                {}

// UnsafePortalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortalServer will
// result in compilation errors.
type UnsafePortalServer interface {
	mustEmbedUnimplementedPortalServer()
}

func RegisterPortalServer(s grpc.ServiceRegistrar, srv PortalServer) {
	// If the following call pancis, it indicates UnimplementedPortalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Portal_ServiceDesc, srv)
}

func _Portal_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portal_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalServer).GetSubscription(ctx, req.(*GetSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portal_PrePurchaseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrePurchaseOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalServer).PrePurchaseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portal_PrePurchaseOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalServer).PrePurchaseOrder(ctx, req.(*PrePurchaseOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portal_Purchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalServer).Purchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portal_Purchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalServer).Purchase(ctx, req.(*PurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portal_GetAvailablePaymentMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalServer).GetAvailablePaymentMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portal_GetAvailablePaymentMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalServer).GetAvailablePaymentMethods(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portal_PurchaseCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalServer).PurchaseCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portal_PurchaseCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalServer).PurchaseCheckout(ctx, req.(*PurchaseCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portal_QueryPurchaseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPurchaseOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalServer).QueryPurchaseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Portal_QueryPurchaseOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalServer).QueryPurchaseOrder(ctx, req.(*QueryPurchaseOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Portal_ServiceDesc is the grpc.ServiceDesc for Portal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Portal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.public.portal.v1.Portal",
	HandlerType: (*PortalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscription",
			Handler:    _Portal_GetSubscription_Handler,
		},
		{
			MethodName: "PrePurchaseOrder",
			Handler:    _Portal_PrePurchaseOrder_Handler,
		},
		{
			MethodName: "Purchase",
			Handler:    _Portal_Purchase_Handler,
		},
		{
			MethodName: "GetAvailablePaymentMethods",
			Handler:    _Portal_GetAvailablePaymentMethods_Handler,
		},
		{
			MethodName: "PurchaseCheckout",
			Handler:    _Portal_PurchaseCheckout_Handler,
		},
		{
			MethodName: "QueryPurchaseOrder",
			Handler:    _Portal_QueryPurchaseOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/portal/v1/portal.proto",
}
