syntax = "proto3";

package api.admin.payment.v1;

import "google/api/annotations.proto";
import "google/protobuf/struct.proto";
import "validate/validate.proto";

option go_package = "github.com/OmnTeam/npanel-pro/api/admin/payment/v1;v1";

service PaymentService {
  rpc CreatePaymentMethod(CreatePaymentMethodRequest) returns (CreatePaymentMethodReply) {
    option (google.api.http) = {
      post: "/v1/admin/payment"
      body: "*"
    };
  }

  rpc UpdatePaymentMethod(UpdatePaymentMethodRequest) returns (UpdatePaymentMethodReply) {
    option (google.api.http) = {
      put: "/v1/admin/payment"
      body: "*"
    };
  }

  rpc DeletePaymentMethod(DeletePaymentMethodRequest) returns (DeletePaymentMethodReply) {
    option (google.api.http) = {
      delete: "/v1/admin/payment"
    };
  }

  rpc GetPaymentMethodList(GetPaymentMethodListRequest) returns (GetPaymentMethodListReply) {
    option (google.api.http) = {
      get: "/v1/admin/payment/list"
    };
  }

  rpc GetPaymentPlatform(GetPaymentPlatformRequest) returns (GetPaymentPlatformReply) {
    option (google.api.http) = {
      get: "/v1/admin/payment/platform"
    };
  }
}

message PaymentConfig {
  int64 id = 1;
  string name = 2;
  string platform = 3;
  string description = 4;
  string icon = 5;
  string domain = 6;
  google.protobuf.Struct config = 7;
  uint32 fee_mode = 8;
  int64 fee_percent = 9;
  int64 fee_amount = 10;
  int32 sort = 11;
  optional bool enable = 12;
}

message PaymentMethodDetail {
  int64 id = 1;
  string name = 2;
  string platform = 3;
  string description = 4;
  string icon = 5;
  string domain = 6;
  google.protobuf.Struct config = 7;
  uint32 fee_mode = 8;
  int64 fee_percent = 9;
  int64 fee_amount = 10;
  int32 sort = 11;
  bool enable = 12;
  string notify_url = 13;
}

message PaymentPlatform {
  string platform = 1 [json_name = "platform"];
  string platform_url = 2 [json_name = "platform_url"];
  map<string, string> platform_field_description = 3 [json_name = "platform_field_description"];
}

message CreatePaymentMethodRequest {
  string name = 1 [(validate.rules).string.min_len = 1];
  string platform = 2 [(validate.rules).string.min_len = 1];
  string description = 3;
  string icon = 4;
  string domain = 5;
  google.protobuf.Struct config = 6;
  uint32 fee_mode = 7;
  int64 fee_percent = 8;
  int64 fee_amount = 9;
  int32 sort = 10;
  optional bool enable = 11;
}

message CreatePaymentMethodReply {
  int32 code = 1;
  string message = 2;
  PaymentConfig data = 3;
}

message UpdatePaymentMethodRequest {
  int64 id = 1 [(validate.rules).int64.gt = 0];
  string name = 2 [(validate.rules).string.min_len = 1];
  string platform = 3 [(validate.rules).string.min_len = 1];
  string description = 4;
  string icon = 5;
  string domain = 6;
  google.protobuf.Struct config = 7;
  uint32 fee_mode = 8;
  int64 fee_percent = 9;
  int64 fee_amount = 10;
  int32 sort = 11;
  optional bool enable = 12;
}

message UpdatePaymentMethodReply {
  int32 code = 1;
  string message = 2;
  PaymentConfig data = 3;
}

message DeletePaymentMethodRequest {
  int64 id = 1 [(validate.rules).int64.gt = 0];
}

message DeletePaymentMethodReply {
  int32 code = 1;
  string message = 2;
}

message GetPaymentMethodListRequest {
  int32 page = 1;
  int32 size = 2;
  string platform = 3;
  string search = 4;
  optional bool enable = 5;
}

message GetPaymentMethodListData {
  int32 total = 1;
  repeated PaymentMethodDetail list = 2;
}

message GetPaymentMethodListReply {
  int32 code = 1;
  string message = 2;
  GetPaymentMethodListData data = 3;
}

message GetPaymentPlatformRequest {}

message GetPaymentPlatformData {
  repeated PaymentPlatform list = 1 [json_name = "list"];
}

message GetPaymentPlatformReply {
  int32 code = 1;
  string message = 2;
  GetPaymentPlatformData data = 3;
}

