// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/npanel-pro/ent/predicate"
	"github.com/OmnTeam/npanel-pro/ent/proxyannouncement"
)

// ProxyAnnouncementDelete is the builder for deleting a ProxyAnnouncement entity.
type ProxyAnnouncementDelete struct {
	config
	hooks    []Hook
	mutation *ProxyAnnouncementMutation
}

// Where appends a list predicates to the ProxyAnnouncementDelete builder.
func (_d *ProxyAnnouncementDelete) Where(ps ...predicate.ProxyAnnouncement) *ProxyAnnouncementDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProxyAnnouncementDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyAnnouncementDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProxyAnnouncementDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(proxyannouncement.Table, sqlgraph.NewFieldSpec(proxyannouncement.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProxyAnnouncementDeleteOne is the builder for deleting a single ProxyAnnouncement entity.
type ProxyAnnouncementDeleteOne struct {
	_d *ProxyAnnouncementDelete
}

// Where appends a list predicates to the ProxyAnnouncementDelete builder.
func (_d *ProxyAnnouncementDeleteOne) Where(ps ...predicate.ProxyAnnouncement) *ProxyAnnouncementDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProxyAnnouncementDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{proxyannouncement.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyAnnouncementDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
