// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/npanel-pro/ent/proxydocument"
)

// ProxyDocumentCreate is the builder for creating a ProxyDocument entity.
type ProxyDocumentCreate struct {
	config
	mutation *ProxyDocumentMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *ProxyDocumentCreate) SetTitle(v string) *ProxyDocumentCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *ProxyDocumentCreate) SetNillableTitle(v *string) *ProxyDocumentCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *ProxyDocumentCreate) SetContent(v string) *ProxyDocumentCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *ProxyDocumentCreate) SetNillableContent(v *string) *ProxyDocumentCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *ProxyDocumentCreate) SetTags(v string) *ProxyDocumentCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_c *ProxyDocumentCreate) SetNillableTags(v *string) *ProxyDocumentCreate {
	if v != nil {
		_c.SetTags(*v)
	}
	return _c
}

// SetShow sets the "show" field.
func (_c *ProxyDocumentCreate) SetShow(v bool) *ProxyDocumentCreate {
	_c.mutation.SetShow(v)
	return _c
}

// SetNillableShow sets the "show" field if the given value is not nil.
func (_c *ProxyDocumentCreate) SetNillableShow(v *bool) *ProxyDocumentCreate {
	if v != nil {
		_c.SetShow(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyDocumentCreate) SetCreatedAt(v time.Time) *ProxyDocumentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyDocumentCreate) SetNillableCreatedAt(v *time.Time) *ProxyDocumentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyDocumentCreate) SetUpdatedAt(v time.Time) *ProxyDocumentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyDocumentCreate) SetNillableUpdatedAt(v *time.Time) *ProxyDocumentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProxyDocumentCreate) SetID(v int64) *ProxyDocumentCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProxyDocumentMutation object of the builder.
func (_c *ProxyDocumentCreate) Mutation() *ProxyDocumentMutation {
	return _c.mutation
}

// Save creates the ProxyDocument in the database.
func (_c *ProxyDocumentCreate) Save(ctx context.Context) (*ProxyDocument, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyDocumentCreate) SaveX(ctx context.Context) *ProxyDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyDocumentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyDocumentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyDocumentCreate) defaults() {
	if _, ok := _c.mutation.Title(); !ok {
		v := proxydocument.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Tags(); !ok {
		v := proxydocument.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.Show(); !ok {
		v := proxydocument.DefaultShow
		_c.mutation.SetShow(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxydocument.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxydocument.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyDocumentCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ProxyDocument.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := proxydocument.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ProxyDocument.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "ProxyDocument.tags"`)}
	}
	if v, ok := _c.mutation.Tags(); ok {
		if err := proxydocument.TagsValidator(v); err != nil {
			return &ValidationError{Name: "tags", err: fmt.Errorf(`ent: validator failed for field "ProxyDocument.tags": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Show(); !ok {
		return &ValidationError{Name: "show", err: errors.New(`ent: missing required field "ProxyDocument.show"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyDocument.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyDocument.updated_at"`)}
	}
	return nil
}

func (_c *ProxyDocumentCreate) sqlSave(ctx context.Context) (*ProxyDocument, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyDocumentCreate) createSpec() (*ProxyDocument, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyDocument{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxydocument.Table, sqlgraph.NewFieldSpec(proxydocument.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(proxydocument.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(proxydocument.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(proxydocument.FieldTags, field.TypeString, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Show(); ok {
		_spec.SetField(proxydocument.FieldShow, field.TypeBool, value)
		_node.Show = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxydocument.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxydocument.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ProxyDocumentCreateBulk is the builder for creating many ProxyDocument entities in bulk.
type ProxyDocumentCreateBulk struct {
	config
	err      error
	builders []*ProxyDocumentCreate
}

// Save creates the ProxyDocument entities in the database.
func (_c *ProxyDocumentCreateBulk) Save(ctx context.Context) ([]*ProxyDocument, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyDocument, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyDocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyDocumentCreateBulk) SaveX(ctx context.Context) []*ProxyDocument {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyDocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyDocumentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
