// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/OmnTeam/ppanel-pro/ent/proxygrouphistory"
)

// ProxyGroupHistory is the model entity for the ProxyGroupHistory schema.
type ProxyGroupHistory struct {
	config `json:"-"`
	// ID of the ent.
	// 历史记录ID
	ID int64 `json:"id,omitempty"`
	// 分组模式: user/node
	GroupMode string `json:"group_mode,omitempty"`
	// 触发类型: manual/auto
	TriggerType string `json:"trigger_type,omitempty"`
	// 状态: pending/running/completed/failed
	Status string `json:"status,omitempty"`
	// 进度
	Progress int `json:"progress,omitempty"`
	// 总数
	Total int `json:"total,omitempty"`
	// 结果详情JSON
	Result string `json:"result,omitempty"`
	// 错误信息
	Error string `json:"error,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyGroupHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxygrouphistory.FieldID, proxygrouphistory.FieldProgress, proxygrouphistory.FieldTotal:
			values[i] = new(sql.NullInt64)
		case proxygrouphistory.FieldGroupMode, proxygrouphistory.FieldTriggerType, proxygrouphistory.FieldStatus, proxygrouphistory.FieldResult, proxygrouphistory.FieldError:
			values[i] = new(sql.NullString)
		case proxygrouphistory.FieldCreatedAt, proxygrouphistory.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyGroupHistory fields.
func (_m *ProxyGroupHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxygrouphistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxygrouphistory.FieldGroupMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_mode", values[i])
			} else if value.Valid {
				_m.GroupMode = value.String
			}
		case proxygrouphistory.FieldTriggerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_type", values[i])
			} else if value.Valid {
				_m.TriggerType = value.String
			}
		case proxygrouphistory.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case proxygrouphistory.FieldProgress:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field progress", values[i])
			} else if value.Valid {
				_m.Progress = int(value.Int64)
			}
		case proxygrouphistory.FieldTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total", values[i])
			} else if value.Valid {
				_m.Total = int(value.Int64)
			}
		case proxygrouphistory.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = value.String
			}
		case proxygrouphistory.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case proxygrouphistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxygrouphistory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyGroupHistory.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyGroupHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProxyGroupHistory.
// Note that you need to call ProxyGroupHistory.Unwrap() before calling this method if this ProxyGroupHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyGroupHistory) Update() *ProxyGroupHistoryUpdateOne {
	return NewProxyGroupHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyGroupHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyGroupHistory) Unwrap() *ProxyGroupHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyGroupHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyGroupHistory) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyGroupHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_mode=")
	builder.WriteString(_m.GroupMode)
	builder.WriteString(", ")
	builder.WriteString("trigger_type=")
	builder.WriteString(_m.TriggerType)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("progress=")
	builder.WriteString(fmt.Sprintf("%v", _m.Progress))
	builder.WriteString(", ")
	builder.WriteString("total=")
	builder.WriteString(fmt.Sprintf("%v", _m.Total))
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(_m.Result)
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProxyGroupHistories is a parsable slice of ProxyGroupHistory.
type ProxyGroupHistories []*ProxyGroupHistory
