// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/ppanel-pro/ent/predicate"
	"github.com/OmnTeam/ppanel-pro/ent/proxysystem"
)

// ProxySystemUpdate is the builder for updating ProxySystem entities.
type ProxySystemUpdate struct {
	config
	hooks    []Hook
	mutation *ProxySystemMutation
}

// Where appends a list predicates to the ProxySystemUpdate builder.
func (_u *ProxySystemUpdate) Where(ps ...predicate.ProxySystem) *ProxySystemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCategory sets the "category" field.
func (_u *ProxySystemUpdate) SetCategory(v string) *ProxySystemUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ProxySystemUpdate) SetNillableCategory(v *string) *ProxySystemUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *ProxySystemUpdate) SetKey(v string) *ProxySystemUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ProxySystemUpdate) SetNillableKey(v *string) *ProxySystemUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ProxySystemUpdate) SetValue(v string) *ProxySystemUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ProxySystemUpdate) SetNillableValue(v *string) *ProxySystemUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ProxySystemUpdate) SetType(v string) *ProxySystemUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ProxySystemUpdate) SetNillableType(v *string) *ProxySystemUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *ProxySystemUpdate) SetDesc(v string) *ProxySystemUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *ProxySystemUpdate) SetNillableDesc(v *string) *ProxySystemUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProxySystemUpdate) SetCreatedAt(v time.Time) *ProxySystemUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProxySystemUpdate) SetNillableCreatedAt(v *time.Time) *ProxySystemUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *ProxySystemUpdate) ClearCreatedAt() *ProxySystemUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySystemUpdate) SetUpdatedAt(v time.Time) *ProxySystemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ProxySystemUpdate) ClearUpdatedAt() *ProxySystemUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the ProxySystemMutation object of the builder.
func (_u *ProxySystemUpdate) Mutation() *ProxySystemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxySystemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySystemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxySystemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySystemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySystemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := proxysystem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySystemUpdate) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := proxysystem.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ProxySystem.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := proxysystem.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ProxySystem.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := proxysystem.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ProxySystem.type": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxySystemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysystem.Table, proxysystem.Columns, sqlgraph.NewFieldSpec(proxysystem.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(proxysystem.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(proxysystem.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(proxysystem.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(proxysystem.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(proxysystem.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(proxysystem.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(proxysystem.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysystem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(proxysystem.FieldUpdatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysystem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxySystemUpdateOne is the builder for updating a single ProxySystem entity.
type ProxySystemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxySystemMutation
}

// SetCategory sets the "category" field.
func (_u *ProxySystemUpdateOne) SetCategory(v string) *ProxySystemUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ProxySystemUpdateOne) SetNillableCategory(v *string) *ProxySystemUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *ProxySystemUpdateOne) SetKey(v string) *ProxySystemUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ProxySystemUpdateOne) SetNillableKey(v *string) *ProxySystemUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ProxySystemUpdateOne) SetValue(v string) *ProxySystemUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ProxySystemUpdateOne) SetNillableValue(v *string) *ProxySystemUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ProxySystemUpdateOne) SetType(v string) *ProxySystemUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ProxySystemUpdateOne) SetNillableType(v *string) *ProxySystemUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *ProxySystemUpdateOne) SetDesc(v string) *ProxySystemUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *ProxySystemUpdateOne) SetNillableDesc(v *string) *ProxySystemUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProxySystemUpdateOne) SetCreatedAt(v time.Time) *ProxySystemUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProxySystemUpdateOne) SetNillableCreatedAt(v *time.Time) *ProxySystemUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *ProxySystemUpdateOne) ClearCreatedAt() *ProxySystemUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxySystemUpdateOne) SetUpdatedAt(v time.Time) *ProxySystemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ProxySystemUpdateOne) ClearUpdatedAt() *ProxySystemUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the ProxySystemMutation object of the builder.
func (_u *ProxySystemUpdateOne) Mutation() *ProxySystemMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxySystemUpdate builder.
func (_u *ProxySystemUpdateOne) Where(ps ...predicate.ProxySystem) *ProxySystemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxySystemUpdateOne) Select(field string, fields ...string) *ProxySystemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxySystem entity.
func (_u *ProxySystemUpdateOne) Save(ctx context.Context) (*ProxySystem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxySystemUpdateOne) SaveX(ctx context.Context) *ProxySystem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxySystemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxySystemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxySystemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := proxysystem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxySystemUpdateOne) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := proxysystem.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ProxySystem.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := proxysystem.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ProxySystem.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := proxysystem.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ProxySystem.type": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxySystemUpdateOne) sqlSave(ctx context.Context) (_node *ProxySystem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxysystem.Table, proxysystem.Columns, sqlgraph.NewFieldSpec(proxysystem.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxySystem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxysystem.FieldID)
		for _, f := range fields {
			if !proxysystem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxysystem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(proxysystem.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(proxysystem.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(proxysystem.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(proxysystem.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(proxysystem.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(proxysystem.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(proxysystem.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysystem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(proxysystem.FieldUpdatedAt, field.TypeTime)
	}
	_node = &ProxySystem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxysystem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
