// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/OmnTeam/ppanel-pro/ent/proxyuserdevice"
)

// ProxyUserDevice is the model entity for the ProxyUserDevice schema.
type ProxyUserDevice struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID int `json:"id,omitempty"`
	// 用户ID
	UserID int `json:"user_id,omitempty"`
	// 订阅ID
	SubscribeID *int `json:"subscribe_id,omitempty"`
	// 设备IP
	IP *string `json:"ip,omitempty"`
	// 设备标识符
	Identifier *string `json:"identifier,omitempty"`
	// 设备User Agent
	UserAgent *string `json:"user_agent,omitempty"`
	// 是否在线
	Online bool `json:"online,omitempty"`
	// 是否启用
	Enabled bool `json:"enabled,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyUserDevice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxyuserdevice.FieldOnline, proxyuserdevice.FieldEnabled:
			values[i] = new(sql.NullBool)
		case proxyuserdevice.FieldID, proxyuserdevice.FieldUserID, proxyuserdevice.FieldSubscribeID:
			values[i] = new(sql.NullInt64)
		case proxyuserdevice.FieldIP, proxyuserdevice.FieldIdentifier, proxyuserdevice.FieldUserAgent:
			values[i] = new(sql.NullString)
		case proxyuserdevice.FieldCreatedAt, proxyuserdevice.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyUserDevice fields.
func (_m *ProxyUserDevice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxyuserdevice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case proxyuserdevice.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case proxyuserdevice.FieldSubscribeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscribe_id", values[i])
			} else if value.Valid {
				_m.SubscribeID = new(int)
				*_m.SubscribeID = int(value.Int64)
			}
		case proxyuserdevice.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = new(string)
				*_m.IP = value.String
			}
		case proxyuserdevice.FieldIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identifier", values[i])
			} else if value.Valid {
				_m.Identifier = new(string)
				*_m.Identifier = value.String
			}
		case proxyuserdevice.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = new(string)
				*_m.UserAgent = value.String
			}
		case proxyuserdevice.FieldOnline:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field online", values[i])
			} else if value.Valid {
				_m.Online = value.Bool
			}
		case proxyuserdevice.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case proxyuserdevice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxyuserdevice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyUserDevice.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyUserDevice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProxyUserDevice.
// Note that you need to call ProxyUserDevice.Unwrap() before calling this method if this ProxyUserDevice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyUserDevice) Update() *ProxyUserDeviceUpdateOne {
	return NewProxyUserDeviceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyUserDevice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyUserDevice) Unwrap() *ProxyUserDevice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyUserDevice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyUserDevice) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyUserDevice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.SubscribeID; v != nil {
		builder.WriteString("subscribe_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IP; v != nil {
		builder.WriteString("ip=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Identifier; v != nil {
		builder.WriteString("identifier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserAgent; v != nil {
		builder.WriteString("user_agent=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("online=")
	builder.WriteString(fmt.Sprintf("%v", _m.Online))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProxyUserDevices is a parsable slice of ProxyUserDevice.
type ProxyUserDevices []*ProxyUserDevice
