// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/npanel-pro/ent/proxyads"
)

// ProxyAdsCreate is the builder for creating a ProxyAds entity.
type ProxyAdsCreate struct {
	config
	mutation *ProxyAdsMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *ProxyAdsCreate) SetTitle(v string) *ProxyAdsCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *ProxyAdsCreate) SetNillableTitle(v *string) *ProxyAdsCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ProxyAdsCreate) SetType(v string) *ProxyAdsCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ProxyAdsCreate) SetNillableType(v *string) *ProxyAdsCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *ProxyAdsCreate) SetContent(v string) *ProxyAdsCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *ProxyAdsCreate) SetNillableContent(v *string) *ProxyAdsCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProxyAdsCreate) SetDescription(v string) *ProxyAdsCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ProxyAdsCreate) SetNillableDescription(v *string) *ProxyAdsCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetTargetURL sets the "target_url" field.
func (_c *ProxyAdsCreate) SetTargetURL(v string) *ProxyAdsCreate {
	_c.mutation.SetTargetURL(v)
	return _c
}

// SetNillableTargetURL sets the "target_url" field if the given value is not nil.
func (_c *ProxyAdsCreate) SetNillableTargetURL(v *string) *ProxyAdsCreate {
	if v != nil {
		_c.SetTargetURL(*v)
	}
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *ProxyAdsCreate) SetStartTime(v time.Time) *ProxyAdsCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *ProxyAdsCreate) SetEndTime(v time.Time) *ProxyAdsCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProxyAdsCreate) SetStatus(v int) *ProxyAdsCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProxyAdsCreate) SetNillableStatus(v *int) *ProxyAdsCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyAdsCreate) SetCreatedAt(v time.Time) *ProxyAdsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyAdsCreate) SetNillableCreatedAt(v *time.Time) *ProxyAdsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyAdsCreate) SetUpdatedAt(v time.Time) *ProxyAdsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyAdsCreate) SetNillableUpdatedAt(v *time.Time) *ProxyAdsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProxyAdsCreate) SetID(v int64) *ProxyAdsCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProxyAdsMutation object of the builder.
func (_c *ProxyAdsCreate) Mutation() *ProxyAdsMutation {
	return _c.mutation
}

// Save creates the ProxyAds in the database.
func (_c *ProxyAdsCreate) Save(ctx context.Context) (*ProxyAds, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyAdsCreate) SaveX(ctx context.Context) *ProxyAds {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyAdsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyAdsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyAdsCreate) defaults() {
	if _, ok := _c.mutation.Title(); !ok {
		v := proxyads.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := proxyads.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.TargetURL(); !ok {
		v := proxyads.DefaultTargetURL
		_c.mutation.SetTargetURL(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := proxyads.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxyads.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxyads.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyAdsCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ProxyAds.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := proxyads.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ProxyAds.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ProxyAds.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := proxyads.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ProxyAds.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetURL(); !ok {
		return &ValidationError{Name: "target_url", err: errors.New(`ent: missing required field "ProxyAds.target_url"`)}
	}
	if v, ok := _c.mutation.TargetURL(); ok {
		if err := proxyads.TargetURLValidator(v); err != nil {
			return &ValidationError{Name: "target_url", err: fmt.Errorf(`ent: validator failed for field "ProxyAds.target_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "ProxyAds.start_time"`)}
	}
	if _, ok := _c.mutation.EndTime(); !ok {
		return &ValidationError{Name: "end_time", err: errors.New(`ent: missing required field "ProxyAds.end_time"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ProxyAds.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyAds.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyAds.updated_at"`)}
	}
	return nil
}

func (_c *ProxyAdsCreate) sqlSave(ctx context.Context) (*ProxyAds, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyAdsCreate) createSpec() (*ProxyAds, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyAds{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxyads.Table, sqlgraph.NewFieldSpec(proxyads.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(proxyads.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(proxyads.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(proxyads.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(proxyads.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.TargetURL(); ok {
		_spec.SetField(proxyads.FieldTargetURL, field.TypeString, value)
		_node.TargetURL = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(proxyads.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(proxyads.FieldEndTime, field.TypeTime, value)
		_node.EndTime = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(proxyads.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxyads.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyads.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ProxyAdsCreateBulk is the builder for creating many ProxyAds entities in bulk.
type ProxyAdsCreateBulk struct {
	config
	err      error
	builders []*ProxyAdsCreate
}

// Save creates the ProxyAds entities in the database.
func (_c *ProxyAdsCreateBulk) Save(ctx context.Context) ([]*ProxyAds, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyAds, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyAdsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyAdsCreateBulk) SaveX(ctx context.Context) []*ProxyAds {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyAdsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyAdsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
