// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/ppanel-pro/ent/predicate"
	"github.com/OmnTeam/ppanel-pro/ent/proxyuser"
)

// ProxyUserDelete is the builder for deleting a ProxyUser entity.
type ProxyUserDelete struct {
	config
	hooks    []Hook
	mutation *ProxyUserMutation
}

// Where appends a list predicates to the ProxyUserDelete builder.
func (_d *ProxyUserDelete) Where(ps ...predicate.ProxyUser) *ProxyUserDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProxyUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyUserDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProxyUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(proxyuser.Table, sqlgraph.NewFieldSpec(proxyuser.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProxyUserDeleteOne is the builder for deleting a single ProxyUser entity.
type ProxyUserDeleteOne struct {
	_d *ProxyUserDelete
}

// Where appends a list predicates to the ProxyUserDelete builder.
func (_d *ProxyUserDeleteOne) Where(ps ...predicate.ProxyUser) *ProxyUserDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProxyUserDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{proxyuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyUserDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
