// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/ppanel-pro/ent/predicate"
	"github.com/OmnTeam/ppanel-pro/ent/proxyuserauthmethod"
)

// ProxyUserAuthMethodUpdate is the builder for updating ProxyUserAuthMethod entities.
type ProxyUserAuthMethodUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyUserAuthMethodMutation
}

// Where appends a list predicates to the ProxyUserAuthMethodUpdate builder.
func (_u *ProxyUserAuthMethodUpdate) Where(ps ...predicate.ProxyUserAuthMethod) *ProxyUserAuthMethodUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ProxyUserAuthMethodUpdate) SetUserID(v int) *ProxyUserAuthMethodUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProxyUserAuthMethodUpdate) SetNillableUserID(v *int) *ProxyUserAuthMethodUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ProxyUserAuthMethodUpdate) AddUserID(v int) *ProxyUserAuthMethodUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ProxyUserAuthMethodUpdate) SetTenantID(v int64) *ProxyUserAuthMethodUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ProxyUserAuthMethodUpdate) SetNillableTenantID(v *int64) *ProxyUserAuthMethodUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *ProxyUserAuthMethodUpdate) AddTenantID(v int64) *ProxyUserAuthMethodUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetAuthType sets the "auth_type" field.
func (_u *ProxyUserAuthMethodUpdate) SetAuthType(v string) *ProxyUserAuthMethodUpdate {
	_u.mutation.SetAuthType(v)
	return _u
}

// SetNillableAuthType sets the "auth_type" field if the given value is not nil.
func (_u *ProxyUserAuthMethodUpdate) SetNillableAuthType(v *string) *ProxyUserAuthMethodUpdate {
	if v != nil {
		_u.SetAuthType(*v)
	}
	return _u
}

// SetAuthIdentifier sets the "auth_identifier" field.
func (_u *ProxyUserAuthMethodUpdate) SetAuthIdentifier(v string) *ProxyUserAuthMethodUpdate {
	_u.mutation.SetAuthIdentifier(v)
	return _u
}

// SetNillableAuthIdentifier sets the "auth_identifier" field if the given value is not nil.
func (_u *ProxyUserAuthMethodUpdate) SetNillableAuthIdentifier(v *string) *ProxyUserAuthMethodUpdate {
	if v != nil {
		_u.SetAuthIdentifier(*v)
	}
	return _u
}

// SetVerified sets the "verified" field.
func (_u *ProxyUserAuthMethodUpdate) SetVerified(v bool) *ProxyUserAuthMethodUpdate {
	_u.mutation.SetVerified(v)
	return _u
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_u *ProxyUserAuthMethodUpdate) SetNillableVerified(v *bool) *ProxyUserAuthMethodUpdate {
	if v != nil {
		_u.SetVerified(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUserAuthMethodUpdate) SetUpdatedAt(v time.Time) *ProxyUserAuthMethodUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxyUserAuthMethodMutation object of the builder.
func (_u *ProxyUserAuthMethodUpdate) Mutation() *ProxyUserAuthMethodMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyUserAuthMethodUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUserAuthMethodUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyUserAuthMethodUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUserAuthMethodUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyUserAuthMethodUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyuserauthmethod.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUserAuthMethodUpdate) check() error {
	if v, ok := _u.mutation.AuthType(); ok {
		if err := proxyuserauthmethod.AuthTypeValidator(v); err != nil {
			return &ValidationError{Name: "auth_type", err: fmt.Errorf(`ent: validator failed for field "ProxyUserAuthMethod.auth_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthIdentifier(); ok {
		if err := proxyuserauthmethod.AuthIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "auth_identifier", err: fmt.Errorf(`ent: validator failed for field "ProxyUserAuthMethod.auth_identifier": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyUserAuthMethodUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyuserauthmethod.Table, proxyuserauthmethod.Columns, sqlgraph.NewFieldSpec(proxyuserauthmethod.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(proxyuserauthmethod.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(proxyuserauthmethod.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(proxyuserauthmethod.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(proxyuserauthmethod.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AuthType(); ok {
		_spec.SetField(proxyuserauthmethod.FieldAuthType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthIdentifier(); ok {
		_spec.SetField(proxyuserauthmethod.FieldAuthIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.Verified(); ok {
		_spec.SetField(proxyuserauthmethod.FieldVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyuserauthmethod.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyuserauthmethod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyUserAuthMethodUpdateOne is the builder for updating a single ProxyUserAuthMethod entity.
type ProxyUserAuthMethodUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyUserAuthMethodMutation
}

// SetUserID sets the "user_id" field.
func (_u *ProxyUserAuthMethodUpdateOne) SetUserID(v int) *ProxyUserAuthMethodUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProxyUserAuthMethodUpdateOne) SetNillableUserID(v *int) *ProxyUserAuthMethodUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ProxyUserAuthMethodUpdateOne) AddUserID(v int) *ProxyUserAuthMethodUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ProxyUserAuthMethodUpdateOne) SetTenantID(v int64) *ProxyUserAuthMethodUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ProxyUserAuthMethodUpdateOne) SetNillableTenantID(v *int64) *ProxyUserAuthMethodUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *ProxyUserAuthMethodUpdateOne) AddTenantID(v int64) *ProxyUserAuthMethodUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetAuthType sets the "auth_type" field.
func (_u *ProxyUserAuthMethodUpdateOne) SetAuthType(v string) *ProxyUserAuthMethodUpdateOne {
	_u.mutation.SetAuthType(v)
	return _u
}

// SetNillableAuthType sets the "auth_type" field if the given value is not nil.
func (_u *ProxyUserAuthMethodUpdateOne) SetNillableAuthType(v *string) *ProxyUserAuthMethodUpdateOne {
	if v != nil {
		_u.SetAuthType(*v)
	}
	return _u
}

// SetAuthIdentifier sets the "auth_identifier" field.
func (_u *ProxyUserAuthMethodUpdateOne) SetAuthIdentifier(v string) *ProxyUserAuthMethodUpdateOne {
	_u.mutation.SetAuthIdentifier(v)
	return _u
}

// SetNillableAuthIdentifier sets the "auth_identifier" field if the given value is not nil.
func (_u *ProxyUserAuthMethodUpdateOne) SetNillableAuthIdentifier(v *string) *ProxyUserAuthMethodUpdateOne {
	if v != nil {
		_u.SetAuthIdentifier(*v)
	}
	return _u
}

// SetVerified sets the "verified" field.
func (_u *ProxyUserAuthMethodUpdateOne) SetVerified(v bool) *ProxyUserAuthMethodUpdateOne {
	_u.mutation.SetVerified(v)
	return _u
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_u *ProxyUserAuthMethodUpdateOne) SetNillableVerified(v *bool) *ProxyUserAuthMethodUpdateOne {
	if v != nil {
		_u.SetVerified(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUserAuthMethodUpdateOne) SetUpdatedAt(v time.Time) *ProxyUserAuthMethodUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxyUserAuthMethodMutation object of the builder.
func (_u *ProxyUserAuthMethodUpdateOne) Mutation() *ProxyUserAuthMethodMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxyUserAuthMethodUpdate builder.
func (_u *ProxyUserAuthMethodUpdateOne) Where(ps ...predicate.ProxyUserAuthMethod) *ProxyUserAuthMethodUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyUserAuthMethodUpdateOne) Select(field string, fields ...string) *ProxyUserAuthMethodUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyUserAuthMethod entity.
func (_u *ProxyUserAuthMethodUpdateOne) Save(ctx context.Context) (*ProxyUserAuthMethod, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUserAuthMethodUpdateOne) SaveX(ctx context.Context) *ProxyUserAuthMethod {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyUserAuthMethodUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUserAuthMethodUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyUserAuthMethodUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyuserauthmethod.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUserAuthMethodUpdateOne) check() error {
	if v, ok := _u.mutation.AuthType(); ok {
		if err := proxyuserauthmethod.AuthTypeValidator(v); err != nil {
			return &ValidationError{Name: "auth_type", err: fmt.Errorf(`ent: validator failed for field "ProxyUserAuthMethod.auth_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthIdentifier(); ok {
		if err := proxyuserauthmethod.AuthIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "auth_identifier", err: fmt.Errorf(`ent: validator failed for field "ProxyUserAuthMethod.auth_identifier": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyUserAuthMethodUpdateOne) sqlSave(ctx context.Context) (_node *ProxyUserAuthMethod, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyuserauthmethod.Table, proxyuserauthmethod.Columns, sqlgraph.NewFieldSpec(proxyuserauthmethod.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyUserAuthMethod.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxyuserauthmethod.FieldID)
		for _, f := range fields {
			if !proxyuserauthmethod.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxyuserauthmethod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(proxyuserauthmethod.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(proxyuserauthmethod.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(proxyuserauthmethod.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(proxyuserauthmethod.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AuthType(); ok {
		_spec.SetField(proxyuserauthmethod.FieldAuthType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthIdentifier(); ok {
		_spec.SetField(proxyuserauthmethod.FieldAuthIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.Verified(); ok {
		_spec.SetField(proxyuserauthmethod.FieldVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyuserauthmethod.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ProxyUserAuthMethod{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyuserauthmethod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
