// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/ppanel-pro/ent/proxysubscribeapplication"
)

// ProxySubscribeApplicationCreate is the builder for creating a ProxySubscribeApplication entity.
type ProxySubscribeApplicationCreate struct {
	config
	mutation *ProxySubscribeApplicationMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *ProxySubscribeApplicationCreate) SetTenantID(v int64) *ProxySubscribeApplicationCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ProxySubscribeApplicationCreate) SetNillableTenantID(v *int64) *ProxySubscribeApplicationCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ProxySubscribeApplicationCreate) SetName(v string) *ProxySubscribeApplicationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIcon sets the "icon" field.
func (_c *ProxySubscribeApplicationCreate) SetIcon(v string) *ProxySubscribeApplicationCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *ProxySubscribeApplicationCreate) SetNillableIcon(v *string) *ProxySubscribeApplicationCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProxySubscribeApplicationCreate) SetDescription(v string) *ProxySubscribeApplicationCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ProxySubscribeApplicationCreate) SetNillableDescription(v *string) *ProxySubscribeApplicationCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetScheme sets the "scheme" field.
func (_c *ProxySubscribeApplicationCreate) SetScheme(v string) *ProxySubscribeApplicationCreate {
	_c.mutation.SetScheme(v)
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *ProxySubscribeApplicationCreate) SetUserAgent(v string) *ProxySubscribeApplicationCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *ProxySubscribeApplicationCreate) SetIsDefault(v bool) *ProxySubscribeApplicationCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *ProxySubscribeApplicationCreate) SetNillableIsDefault(v *bool) *ProxySubscribeApplicationCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetSubscribeTemplate sets the "subscribe_template" field.
func (_c *ProxySubscribeApplicationCreate) SetSubscribeTemplate(v string) *ProxySubscribeApplicationCreate {
	_c.mutation.SetSubscribeTemplate(v)
	return _c
}

// SetNillableSubscribeTemplate sets the "subscribe_template" field if the given value is not nil.
func (_c *ProxySubscribeApplicationCreate) SetNillableSubscribeTemplate(v *string) *ProxySubscribeApplicationCreate {
	if v != nil {
		_c.SetSubscribeTemplate(*v)
	}
	return _c
}

// SetOutputFormat sets the "output_format" field.
func (_c *ProxySubscribeApplicationCreate) SetOutputFormat(v string) *ProxySubscribeApplicationCreate {
	_c.mutation.SetOutputFormat(v)
	return _c
}

// SetNillableOutputFormat sets the "output_format" field if the given value is not nil.
func (_c *ProxySubscribeApplicationCreate) SetNillableOutputFormat(v *string) *ProxySubscribeApplicationCreate {
	if v != nil {
		_c.SetOutputFormat(*v)
	}
	return _c
}

// SetDownloadLink sets the "download_link" field.
func (_c *ProxySubscribeApplicationCreate) SetDownloadLink(v string) *ProxySubscribeApplicationCreate {
	_c.mutation.SetDownloadLink(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxySubscribeApplicationCreate) SetCreatedAt(v time.Time) *ProxySubscribeApplicationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxySubscribeApplicationCreate) SetNillableCreatedAt(v *time.Time) *ProxySubscribeApplicationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxySubscribeApplicationCreate) SetUpdatedAt(v time.Time) *ProxySubscribeApplicationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxySubscribeApplicationCreate) SetNillableUpdatedAt(v *time.Time) *ProxySubscribeApplicationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProxySubscribeApplicationCreate) SetID(v int64) *ProxySubscribeApplicationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProxySubscribeApplicationMutation object of the builder.
func (_c *ProxySubscribeApplicationCreate) Mutation() *ProxySubscribeApplicationMutation {
	return _c.mutation
}

// Save creates the ProxySubscribeApplication in the database.
func (_c *ProxySubscribeApplicationCreate) Save(ctx context.Context) (*ProxySubscribeApplication, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxySubscribeApplicationCreate) SaveX(ctx context.Context) *ProxySubscribeApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxySubscribeApplicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxySubscribeApplicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxySubscribeApplicationCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := proxysubscribeapplication.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := proxysubscribeapplication.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.OutputFormat(); !ok {
		v := proxysubscribeapplication.DefaultOutputFormat
		_c.mutation.SetOutputFormat(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxysubscribeapplication.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxysubscribeapplication.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxySubscribeApplicationCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ProxySubscribeApplication.tenant_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProxySubscribeApplication.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := proxysubscribeapplication.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribeApplication.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := proxysubscribeapplication.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribeApplication.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scheme(); !ok {
		return &ValidationError{Name: "scheme", err: errors.New(`ent: missing required field "ProxySubscribeApplication.scheme"`)}
	}
	if v, ok := _c.mutation.Scheme(); ok {
		if err := proxysubscribeapplication.SchemeValidator(v); err != nil {
			return &ValidationError{Name: "scheme", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribeApplication.scheme": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "ProxySubscribeApplication.user_agent"`)}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := proxysubscribeapplication.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribeApplication.user_agent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "ProxySubscribeApplication.is_default"`)}
	}
	if _, ok := _c.mutation.OutputFormat(); !ok {
		return &ValidationError{Name: "output_format", err: errors.New(`ent: missing required field "ProxySubscribeApplication.output_format"`)}
	}
	if v, ok := _c.mutation.OutputFormat(); ok {
		if err := proxysubscribeapplication.OutputFormatValidator(v); err != nil {
			return &ValidationError{Name: "output_format", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribeApplication.output_format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DownloadLink(); !ok {
		return &ValidationError{Name: "download_link", err: errors.New(`ent: missing required field "ProxySubscribeApplication.download_link"`)}
	}
	if v, ok := _c.mutation.DownloadLink(); ok {
		if err := proxysubscribeapplication.DownloadLinkValidator(v); err != nil {
			return &ValidationError{Name: "download_link", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribeApplication.download_link": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxySubscribeApplication.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxySubscribeApplication.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := proxysubscribeapplication.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ProxySubscribeApplication.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ProxySubscribeApplicationCreate) sqlSave(ctx context.Context) (*ProxySubscribeApplication, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxySubscribeApplicationCreate) createSpec() (*ProxySubscribeApplication, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxySubscribeApplication{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxysubscribeapplication.Table, sqlgraph.NewFieldSpec(proxysubscribeapplication.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(proxysubscribeapplication.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(proxysubscribeapplication.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(proxysubscribeapplication.FieldIcon, field.TypeString, value)
		_node.Icon = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(proxysubscribeapplication.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Scheme(); ok {
		_spec.SetField(proxysubscribeapplication.FieldScheme, field.TypeString, value)
		_node.Scheme = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(proxysubscribeapplication.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(proxysubscribeapplication.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.SubscribeTemplate(); ok {
		_spec.SetField(proxysubscribeapplication.FieldSubscribeTemplate, field.TypeString, value)
		_node.SubscribeTemplate = &value
	}
	if value, ok := _c.mutation.OutputFormat(); ok {
		_spec.SetField(proxysubscribeapplication.FieldOutputFormat, field.TypeString, value)
		_node.OutputFormat = value
	}
	if value, ok := _c.mutation.DownloadLink(); ok {
		_spec.SetField(proxysubscribeapplication.FieldDownloadLink, field.TypeString, value)
		_node.DownloadLink = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxysubscribeapplication.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxysubscribeapplication.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ProxySubscribeApplicationCreateBulk is the builder for creating many ProxySubscribeApplication entities in bulk.
type ProxySubscribeApplicationCreateBulk struct {
	config
	err      error
	builders []*ProxySubscribeApplicationCreate
}

// Save creates the ProxySubscribeApplication entities in the database.
func (_c *ProxySubscribeApplicationCreateBulk) Save(ctx context.Context) ([]*ProxySubscribeApplication, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxySubscribeApplication, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxySubscribeApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxySubscribeApplicationCreateBulk) SaveX(ctx context.Context) []*ProxySubscribeApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxySubscribeApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxySubscribeApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
