// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/ppanel-pro/ent/predicate"
	"github.com/OmnTeam/ppanel-pro/ent/proxyusersubscribe"
)

// ProxyUserSubscribeDelete is the builder for deleting a ProxyUserSubscribe entity.
type ProxyUserSubscribeDelete struct {
	config
	hooks    []Hook
	mutation *ProxyUserSubscribeMutation
}

// Where appends a list predicates to the ProxyUserSubscribeDelete builder.
func (_d *ProxyUserSubscribeDelete) Where(ps ...predicate.ProxyUserSubscribe) *ProxyUserSubscribeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProxyUserSubscribeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyUserSubscribeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProxyUserSubscribeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(proxyusersubscribe.Table, sqlgraph.NewFieldSpec(proxyusersubscribe.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProxyUserSubscribeDeleteOne is the builder for deleting a single ProxyUserSubscribe entity.
type ProxyUserSubscribeDeleteOne struct {
	_d *ProxyUserSubscribeDelete
}

// Where appends a list predicates to the ProxyUserSubscribeDelete builder.
func (_d *ProxyUserSubscribeDeleteOne) Where(ps ...predicate.ProxyUserSubscribe) *ProxyUserSubscribeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProxyUserSubscribeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{proxyusersubscribe.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyUserSubscribeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
