// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/ppanel-pro/ent/predicate"
	"github.com/OmnTeam/ppanel-pro/ent/proxyredemptioncode"
)

// ProxyRedemptionCodeDelete is the builder for deleting a ProxyRedemptionCode entity.
type ProxyRedemptionCodeDelete struct {
	config
	hooks    []Hook
	mutation *ProxyRedemptionCodeMutation
}

// Where appends a list predicates to the ProxyRedemptionCodeDelete builder.
func (_d *ProxyRedemptionCodeDelete) Where(ps ...predicate.ProxyRedemptionCode) *ProxyRedemptionCodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProxyRedemptionCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyRedemptionCodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProxyRedemptionCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(proxyredemptioncode.Table, sqlgraph.NewFieldSpec(proxyredemptioncode.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProxyRedemptionCodeDeleteOne is the builder for deleting a single ProxyRedemptionCode entity.
type ProxyRedemptionCodeDeleteOne struct {
	_d *ProxyRedemptionCodeDelete
}

// Where appends a list predicates to the ProxyRedemptionCodeDelete builder.
func (_d *ProxyRedemptionCodeDeleteOne) Where(ps ...predicate.ProxyRedemptionCode) *ProxyRedemptionCodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProxyRedemptionCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{proxyredemptioncode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyRedemptionCodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
