// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/ppanel-pro/ent/predicate"
	"github.com/OmnTeam/ppanel-pro/ent/proxyredemptionrecord"
	"github.com/OmnTeam/ppanel-pro/ent/proxyuser"
	"github.com/OmnTeam/ppanel-pro/ent/proxyuserwithdrawal"
)

// ProxyUserUpdate is the builder for updating ProxyUser entities.
type ProxyUserUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyUserMutation
}

// Where appends a list predicates to the ProxyUserUpdate builder.
func (_u *ProxyUserUpdate) Where(ps ...predicate.ProxyUser) *ProxyUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPassword sets the "password" field.
func (_u *ProxyUserUpdate) SetPassword(v string) *ProxyUserUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillablePassword(v *string) *ProxyUserUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetAlgo sets the "algo" field.
func (_u *ProxyUserUpdate) SetAlgo(v string) *ProxyUserUpdate {
	_u.mutation.SetAlgo(v)
	return _u
}

// SetNillableAlgo sets the "algo" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableAlgo(v *string) *ProxyUserUpdate {
	if v != nil {
		_u.SetAlgo(*v)
	}
	return _u
}

// SetSalt sets the "salt" field.
func (_u *ProxyUserUpdate) SetSalt(v string) *ProxyUserUpdate {
	_u.mutation.SetSalt(v)
	return _u
}

// SetNillableSalt sets the "salt" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableSalt(v *string) *ProxyUserUpdate {
	if v != nil {
		_u.SetSalt(*v)
	}
	return _u
}

// ClearSalt clears the value of the "salt" field.
func (_u *ProxyUserUpdate) ClearSalt() *ProxyUserUpdate {
	_u.mutation.ClearSalt()
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *ProxyUserUpdate) SetAvatar(v string) *ProxyUserUpdate {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableAvatar(v *string) *ProxyUserUpdate {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// ClearAvatar clears the value of the "avatar" field.
func (_u *ProxyUserUpdate) ClearAvatar() *ProxyUserUpdate {
	_u.mutation.ClearAvatar()
	return _u
}

// SetBalance sets the "balance" field.
func (_u *ProxyUserUpdate) SetBalance(v int64) *ProxyUserUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableBalance(v *int64) *ProxyUserUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *ProxyUserUpdate) AddBalance(v int64) *ProxyUserUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// ClearBalance clears the value of the "balance" field.
func (_u *ProxyUserUpdate) ClearBalance() *ProxyUserUpdate {
	_u.mutation.ClearBalance()
	return _u
}

// SetTelegram sets the "telegram" field.
func (_u *ProxyUserUpdate) SetTelegram(v int64) *ProxyUserUpdate {
	_u.mutation.ResetTelegram()
	_u.mutation.SetTelegram(v)
	return _u
}

// SetNillableTelegram sets the "telegram" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableTelegram(v *int64) *ProxyUserUpdate {
	if v != nil {
		_u.SetTelegram(*v)
	}
	return _u
}

// AddTelegram adds value to the "telegram" field.
func (_u *ProxyUserUpdate) AddTelegram(v int64) *ProxyUserUpdate {
	_u.mutation.AddTelegram(v)
	return _u
}

// ClearTelegram clears the value of the "telegram" field.
func (_u *ProxyUserUpdate) ClearTelegram() *ProxyUserUpdate {
	_u.mutation.ClearTelegram()
	return _u
}

// SetReferCode sets the "refer_code" field.
func (_u *ProxyUserUpdate) SetReferCode(v string) *ProxyUserUpdate {
	_u.mutation.SetReferCode(v)
	return _u
}

// SetNillableReferCode sets the "refer_code" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableReferCode(v *string) *ProxyUserUpdate {
	if v != nil {
		_u.SetReferCode(*v)
	}
	return _u
}

// ClearReferCode clears the value of the "refer_code" field.
func (_u *ProxyUserUpdate) ClearReferCode() *ProxyUserUpdate {
	_u.mutation.ClearReferCode()
	return _u
}

// SetRefererID sets the "referer_id" field.
func (_u *ProxyUserUpdate) SetRefererID(v int64) *ProxyUserUpdate {
	_u.mutation.ResetRefererID()
	_u.mutation.SetRefererID(v)
	return _u
}

// SetNillableRefererID sets the "referer_id" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableRefererID(v *int64) *ProxyUserUpdate {
	if v != nil {
		_u.SetRefererID(*v)
	}
	return _u
}

// AddRefererID adds value to the "referer_id" field.
func (_u *ProxyUserUpdate) AddRefererID(v int64) *ProxyUserUpdate {
	_u.mutation.AddRefererID(v)
	return _u
}

// ClearRefererID clears the value of the "referer_id" field.
func (_u *ProxyUserUpdate) ClearRefererID() *ProxyUserUpdate {
	_u.mutation.ClearRefererID()
	return _u
}

// SetCommission sets the "commission" field.
func (_u *ProxyUserUpdate) SetCommission(v int64) *ProxyUserUpdate {
	_u.mutation.ResetCommission()
	_u.mutation.SetCommission(v)
	return _u
}

// SetNillableCommission sets the "commission" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableCommission(v *int64) *ProxyUserUpdate {
	if v != nil {
		_u.SetCommission(*v)
	}
	return _u
}

// AddCommission adds value to the "commission" field.
func (_u *ProxyUserUpdate) AddCommission(v int64) *ProxyUserUpdate {
	_u.mutation.AddCommission(v)
	return _u
}

// ClearCommission clears the value of the "commission" field.
func (_u *ProxyUserUpdate) ClearCommission() *ProxyUserUpdate {
	_u.mutation.ClearCommission()
	return _u
}

// SetReferralPercentage sets the "referral_percentage" field.
func (_u *ProxyUserUpdate) SetReferralPercentage(v int8) *ProxyUserUpdate {
	_u.mutation.ResetReferralPercentage()
	_u.mutation.SetReferralPercentage(v)
	return _u
}

// SetNillableReferralPercentage sets the "referral_percentage" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableReferralPercentage(v *int8) *ProxyUserUpdate {
	if v != nil {
		_u.SetReferralPercentage(*v)
	}
	return _u
}

// AddReferralPercentage adds value to the "referral_percentage" field.
func (_u *ProxyUserUpdate) AddReferralPercentage(v int8) *ProxyUserUpdate {
	_u.mutation.AddReferralPercentage(v)
	return _u
}

// SetOnlyFirstPurchase sets the "only_first_purchase" field.
func (_u *ProxyUserUpdate) SetOnlyFirstPurchase(v bool) *ProxyUserUpdate {
	_u.mutation.SetOnlyFirstPurchase(v)
	return _u
}

// SetNillableOnlyFirstPurchase sets the "only_first_purchase" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableOnlyFirstPurchase(v *bool) *ProxyUserUpdate {
	if v != nil {
		_u.SetOnlyFirstPurchase(*v)
	}
	return _u
}

// SetGiftAmount sets the "gift_amount" field.
func (_u *ProxyUserUpdate) SetGiftAmount(v int64) *ProxyUserUpdate {
	_u.mutation.ResetGiftAmount()
	_u.mutation.SetGiftAmount(v)
	return _u
}

// SetNillableGiftAmount sets the "gift_amount" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableGiftAmount(v *int64) *ProxyUserUpdate {
	if v != nil {
		_u.SetGiftAmount(*v)
	}
	return _u
}

// AddGiftAmount adds value to the "gift_amount" field.
func (_u *ProxyUserUpdate) AddGiftAmount(v int64) *ProxyUserUpdate {
	_u.mutation.AddGiftAmount(v)
	return _u
}

// ClearGiftAmount clears the value of the "gift_amount" field.
func (_u *ProxyUserUpdate) ClearGiftAmount() *ProxyUserUpdate {
	_u.mutation.ClearGiftAmount()
	return _u
}

// SetEnable sets the "enable" field.
func (_u *ProxyUserUpdate) SetEnable(v bool) *ProxyUserUpdate {
	_u.mutation.SetEnable(v)
	return _u
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableEnable(v *bool) *ProxyUserUpdate {
	if v != nil {
		_u.SetEnable(*v)
	}
	return _u
}

// SetIsAdmin sets the "is_admin" field.
func (_u *ProxyUserUpdate) SetIsAdmin(v bool) *ProxyUserUpdate {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableIsAdmin(v *bool) *ProxyUserUpdate {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// SetValidEmail sets the "valid_email" field.
func (_u *ProxyUserUpdate) SetValidEmail(v bool) *ProxyUserUpdate {
	_u.mutation.SetValidEmail(v)
	return _u
}

// SetNillableValidEmail sets the "valid_email" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableValidEmail(v *bool) *ProxyUserUpdate {
	if v != nil {
		_u.SetValidEmail(*v)
	}
	return _u
}

// SetEnableEmailNotify sets the "enable_email_notify" field.
func (_u *ProxyUserUpdate) SetEnableEmailNotify(v bool) *ProxyUserUpdate {
	_u.mutation.SetEnableEmailNotify(v)
	return _u
}

// SetNillableEnableEmailNotify sets the "enable_email_notify" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableEnableEmailNotify(v *bool) *ProxyUserUpdate {
	if v != nil {
		_u.SetEnableEmailNotify(*v)
	}
	return _u
}

// SetEnableTelegramNotify sets the "enable_telegram_notify" field.
func (_u *ProxyUserUpdate) SetEnableTelegramNotify(v bool) *ProxyUserUpdate {
	_u.mutation.SetEnableTelegramNotify(v)
	return _u
}

// SetNillableEnableTelegramNotify sets the "enable_telegram_notify" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableEnableTelegramNotify(v *bool) *ProxyUserUpdate {
	if v != nil {
		_u.SetEnableTelegramNotify(*v)
	}
	return _u
}

// SetEnableBalanceNotify sets the "enable_balance_notify" field.
func (_u *ProxyUserUpdate) SetEnableBalanceNotify(v bool) *ProxyUserUpdate {
	_u.mutation.SetEnableBalanceNotify(v)
	return _u
}

// SetNillableEnableBalanceNotify sets the "enable_balance_notify" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableEnableBalanceNotify(v *bool) *ProxyUserUpdate {
	if v != nil {
		_u.SetEnableBalanceNotify(*v)
	}
	return _u
}

// SetEnableLoginNotify sets the "enable_login_notify" field.
func (_u *ProxyUserUpdate) SetEnableLoginNotify(v bool) *ProxyUserUpdate {
	_u.mutation.SetEnableLoginNotify(v)
	return _u
}

// SetNillableEnableLoginNotify sets the "enable_login_notify" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableEnableLoginNotify(v *bool) *ProxyUserUpdate {
	if v != nil {
		_u.SetEnableLoginNotify(*v)
	}
	return _u
}

// SetEnableSubscribeNotify sets the "enable_subscribe_notify" field.
func (_u *ProxyUserUpdate) SetEnableSubscribeNotify(v bool) *ProxyUserUpdate {
	_u.mutation.SetEnableSubscribeNotify(v)
	return _u
}

// SetNillableEnableSubscribeNotify sets the "enable_subscribe_notify" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableEnableSubscribeNotify(v *bool) *ProxyUserUpdate {
	if v != nil {
		_u.SetEnableSubscribeNotify(*v)
	}
	return _u
}

// SetEnableTradeNotify sets the "enable_trade_notify" field.
func (_u *ProxyUserUpdate) SetEnableTradeNotify(v bool) *ProxyUserUpdate {
	_u.mutation.SetEnableTradeNotify(v)
	return _u
}

// SetNillableEnableTradeNotify sets the "enable_trade_notify" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableEnableTradeNotify(v *bool) *ProxyUserUpdate {
	if v != nil {
		_u.SetEnableTradeNotify(*v)
	}
	return _u
}

// SetRules sets the "rules" field.
func (_u *ProxyUserUpdate) SetRules(v string) *ProxyUserUpdate {
	_u.mutation.SetRules(v)
	return _u
}

// SetNillableRules sets the "rules" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableRules(v *string) *ProxyUserUpdate {
	if v != nil {
		_u.SetRules(*v)
	}
	return _u
}

// ClearRules clears the value of the "rules" field.
func (_u *ProxyUserUpdate) ClearRules() *ProxyUserUpdate {
	_u.mutation.ClearRules()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUserUpdate) SetUpdatedAt(v time.Time) *ProxyUserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyUserUpdate) SetDeletedAt(v time.Time) *ProxyUserUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableDeletedAt(v *time.Time) *ProxyUserUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyUserUpdate) ClearDeletedAt() *ProxyUserUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetIsDel sets the "is_del" field.
func (_u *ProxyUserUpdate) SetIsDel(v uint64) *ProxyUserUpdate {
	_u.mutation.ResetIsDel()
	_u.mutation.SetIsDel(v)
	return _u
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (_u *ProxyUserUpdate) SetNillableIsDel(v *uint64) *ProxyUserUpdate {
	if v != nil {
		_u.SetIsDel(*v)
	}
	return _u
}

// AddIsDel adds value to the "is_del" field.
func (_u *ProxyUserUpdate) AddIsDel(v int64) *ProxyUserUpdate {
	_u.mutation.AddIsDel(v)
	return _u
}

// ClearIsDel clears the value of the "is_del" field.
func (_u *ProxyUserUpdate) ClearIsDel() *ProxyUserUpdate {
	_u.mutation.ClearIsDel()
	return _u
}

// AddRedemptionRecordIDs adds the "redemption_records" edge to the ProxyRedemptionRecord entity by IDs.
func (_u *ProxyUserUpdate) AddRedemptionRecordIDs(ids ...int64) *ProxyUserUpdate {
	_u.mutation.AddRedemptionRecordIDs(ids...)
	return _u
}

// AddRedemptionRecords adds the "redemption_records" edges to the ProxyRedemptionRecord entity.
func (_u *ProxyUserUpdate) AddRedemptionRecords(v ...*ProxyRedemptionRecord) *ProxyUserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedemptionRecordIDs(ids...)
}

// AddWithdrawalIDs adds the "withdrawals" edge to the ProxyUserWithdrawal entity by IDs.
func (_u *ProxyUserUpdate) AddWithdrawalIDs(ids ...int64) *ProxyUserUpdate {
	_u.mutation.AddWithdrawalIDs(ids...)
	return _u
}

// AddWithdrawals adds the "withdrawals" edges to the ProxyUserWithdrawal entity.
func (_u *ProxyUserUpdate) AddWithdrawals(v ...*ProxyUserWithdrawal) *ProxyUserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWithdrawalIDs(ids...)
}

// Mutation returns the ProxyUserMutation object of the builder.
func (_u *ProxyUserUpdate) Mutation() *ProxyUserMutation {
	return _u.mutation
}

// ClearRedemptionRecords clears all "redemption_records" edges to the ProxyRedemptionRecord entity.
func (_u *ProxyUserUpdate) ClearRedemptionRecords() *ProxyUserUpdate {
	_u.mutation.ClearRedemptionRecords()
	return _u
}

// RemoveRedemptionRecordIDs removes the "redemption_records" edge to ProxyRedemptionRecord entities by IDs.
func (_u *ProxyUserUpdate) RemoveRedemptionRecordIDs(ids ...int64) *ProxyUserUpdate {
	_u.mutation.RemoveRedemptionRecordIDs(ids...)
	return _u
}

// RemoveRedemptionRecords removes "redemption_records" edges to ProxyRedemptionRecord entities.
func (_u *ProxyUserUpdate) RemoveRedemptionRecords(v ...*ProxyRedemptionRecord) *ProxyUserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedemptionRecordIDs(ids...)
}

// ClearWithdrawals clears all "withdrawals" edges to the ProxyUserWithdrawal entity.
func (_u *ProxyUserUpdate) ClearWithdrawals() *ProxyUserUpdate {
	_u.mutation.ClearWithdrawals()
	return _u
}

// RemoveWithdrawalIDs removes the "withdrawals" edge to ProxyUserWithdrawal entities by IDs.
func (_u *ProxyUserUpdate) RemoveWithdrawalIDs(ids ...int64) *ProxyUserUpdate {
	_u.mutation.RemoveWithdrawalIDs(ids...)
	return _u
}

// RemoveWithdrawals removes "withdrawals" edges to ProxyUserWithdrawal entities.
func (_u *ProxyUserUpdate) RemoveWithdrawals(v ...*ProxyUserWithdrawal) *ProxyUserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWithdrawalIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyUserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyUserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUserUpdate) check() error {
	if v, ok := _u.mutation.Password(); ok {
		if err := proxyuser.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Algo(); ok {
		if err := proxyuser.AlgoValidator(v); err != nil {
			return &ValidationError{Name: "algo", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.algo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Salt(); ok {
		if err := proxyuser.SaltValidator(v); err != nil {
			return &ValidationError{Name: "salt", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.salt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReferCode(); ok {
		if err := proxyuser.ReferCodeValidator(v); err != nil {
			return &ValidationError{Name: "refer_code", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.refer_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyuser.Table, proxyuser.Columns, sqlgraph.NewFieldSpec(proxyuser.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(proxyuser.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Algo(); ok {
		_spec.SetField(proxyuser.FieldAlgo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Salt(); ok {
		_spec.SetField(proxyuser.FieldSalt, field.TypeString, value)
	}
	if _u.mutation.SaltCleared() {
		_spec.ClearField(proxyuser.FieldSalt, field.TypeString)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(proxyuser.FieldAvatar, field.TypeString, value)
	}
	if _u.mutation.AvatarCleared() {
		_spec.ClearField(proxyuser.FieldAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(proxyuser.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(proxyuser.FieldBalance, field.TypeInt64, value)
	}
	if _u.mutation.BalanceCleared() {
		_spec.ClearField(proxyuser.FieldBalance, field.TypeInt64)
	}
	if value, ok := _u.mutation.Telegram(); ok {
		_spec.SetField(proxyuser.FieldTelegram, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegram(); ok {
		_spec.AddField(proxyuser.FieldTelegram, field.TypeInt64, value)
	}
	if _u.mutation.TelegramCleared() {
		_spec.ClearField(proxyuser.FieldTelegram, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReferCode(); ok {
		_spec.SetField(proxyuser.FieldReferCode, field.TypeString, value)
	}
	if _u.mutation.ReferCodeCleared() {
		_spec.ClearField(proxyuser.FieldReferCode, field.TypeString)
	}
	if value, ok := _u.mutation.RefererID(); ok {
		_spec.SetField(proxyuser.FieldRefererID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefererID(); ok {
		_spec.AddField(proxyuser.FieldRefererID, field.TypeInt64, value)
	}
	if _u.mutation.RefererIDCleared() {
		_spec.ClearField(proxyuser.FieldRefererID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Commission(); ok {
		_spec.SetField(proxyuser.FieldCommission, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCommission(); ok {
		_spec.AddField(proxyuser.FieldCommission, field.TypeInt64, value)
	}
	if _u.mutation.CommissionCleared() {
		_spec.ClearField(proxyuser.FieldCommission, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReferralPercentage(); ok {
		_spec.SetField(proxyuser.FieldReferralPercentage, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedReferralPercentage(); ok {
		_spec.AddField(proxyuser.FieldReferralPercentage, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.OnlyFirstPurchase(); ok {
		_spec.SetField(proxyuser.FieldOnlyFirstPurchase, field.TypeBool, value)
	}
	if value, ok := _u.mutation.GiftAmount(); ok {
		_spec.SetField(proxyuser.FieldGiftAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGiftAmount(); ok {
		_spec.AddField(proxyuser.FieldGiftAmount, field.TypeInt64, value)
	}
	if _u.mutation.GiftAmountCleared() {
		_spec.ClearField(proxyuser.FieldGiftAmount, field.TypeInt64)
	}
	if value, ok := _u.mutation.Enable(); ok {
		_spec.SetField(proxyuser.FieldEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(proxyuser.FieldIsAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ValidEmail(); ok {
		_spec.SetField(proxyuser.FieldValidEmail, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableEmailNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableEmailNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableTelegramNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableTelegramNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableBalanceNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableBalanceNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableLoginNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableLoginNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableSubscribeNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableSubscribeNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableTradeNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableTradeNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Rules(); ok {
		_spec.SetField(proxyuser.FieldRules, field.TypeString, value)
	}
	if _u.mutation.RulesCleared() {
		_spec.ClearField(proxyuser.FieldRules, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxyuser.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxyuser.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsDel(); ok {
		_spec.SetField(proxyuser.FieldIsDel, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedIsDel(); ok {
		_spec.AddField(proxyuser.FieldIsDel, field.TypeUint64, value)
	}
	if _u.mutation.IsDelCleared() {
		_spec.ClearField(proxyuser.FieldIsDel, field.TypeUint64)
	}
	if _u.mutation.RedemptionRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.RedemptionRecordsTable,
			Columns: []string{proxyuser.RedemptionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyredemptionrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedemptionRecordsIDs(); len(nodes) > 0 && !_u.mutation.RedemptionRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.RedemptionRecordsTable,
			Columns: []string{proxyuser.RedemptionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyredemptionrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedemptionRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.RedemptionRecordsTable,
			Columns: []string{proxyuser.RedemptionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyredemptionrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.WithdrawalsTable,
			Columns: []string{proxyuser.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyuserwithdrawal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWithdrawalsIDs(); len(nodes) > 0 && !_u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.WithdrawalsTable,
			Columns: []string{proxyuser.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyuserwithdrawal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.WithdrawalsTable,
			Columns: []string{proxyuser.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyuserwithdrawal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyUserUpdateOne is the builder for updating a single ProxyUser entity.
type ProxyUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyUserMutation
}

// SetPassword sets the "password" field.
func (_u *ProxyUserUpdateOne) SetPassword(v string) *ProxyUserUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillablePassword(v *string) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetAlgo sets the "algo" field.
func (_u *ProxyUserUpdateOne) SetAlgo(v string) *ProxyUserUpdateOne {
	_u.mutation.SetAlgo(v)
	return _u
}

// SetNillableAlgo sets the "algo" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableAlgo(v *string) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetAlgo(*v)
	}
	return _u
}

// SetSalt sets the "salt" field.
func (_u *ProxyUserUpdateOne) SetSalt(v string) *ProxyUserUpdateOne {
	_u.mutation.SetSalt(v)
	return _u
}

// SetNillableSalt sets the "salt" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableSalt(v *string) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetSalt(*v)
	}
	return _u
}

// ClearSalt clears the value of the "salt" field.
func (_u *ProxyUserUpdateOne) ClearSalt() *ProxyUserUpdateOne {
	_u.mutation.ClearSalt()
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *ProxyUserUpdateOne) SetAvatar(v string) *ProxyUserUpdateOne {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableAvatar(v *string) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// ClearAvatar clears the value of the "avatar" field.
func (_u *ProxyUserUpdateOne) ClearAvatar() *ProxyUserUpdateOne {
	_u.mutation.ClearAvatar()
	return _u
}

// SetBalance sets the "balance" field.
func (_u *ProxyUserUpdateOne) SetBalance(v int64) *ProxyUserUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableBalance(v *int64) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *ProxyUserUpdateOne) AddBalance(v int64) *ProxyUserUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// ClearBalance clears the value of the "balance" field.
func (_u *ProxyUserUpdateOne) ClearBalance() *ProxyUserUpdateOne {
	_u.mutation.ClearBalance()
	return _u
}

// SetTelegram sets the "telegram" field.
func (_u *ProxyUserUpdateOne) SetTelegram(v int64) *ProxyUserUpdateOne {
	_u.mutation.ResetTelegram()
	_u.mutation.SetTelegram(v)
	return _u
}

// SetNillableTelegram sets the "telegram" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableTelegram(v *int64) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetTelegram(*v)
	}
	return _u
}

// AddTelegram adds value to the "telegram" field.
func (_u *ProxyUserUpdateOne) AddTelegram(v int64) *ProxyUserUpdateOne {
	_u.mutation.AddTelegram(v)
	return _u
}

// ClearTelegram clears the value of the "telegram" field.
func (_u *ProxyUserUpdateOne) ClearTelegram() *ProxyUserUpdateOne {
	_u.mutation.ClearTelegram()
	return _u
}

// SetReferCode sets the "refer_code" field.
func (_u *ProxyUserUpdateOne) SetReferCode(v string) *ProxyUserUpdateOne {
	_u.mutation.SetReferCode(v)
	return _u
}

// SetNillableReferCode sets the "refer_code" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableReferCode(v *string) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetReferCode(*v)
	}
	return _u
}

// ClearReferCode clears the value of the "refer_code" field.
func (_u *ProxyUserUpdateOne) ClearReferCode() *ProxyUserUpdateOne {
	_u.mutation.ClearReferCode()
	return _u
}

// SetRefererID sets the "referer_id" field.
func (_u *ProxyUserUpdateOne) SetRefererID(v int64) *ProxyUserUpdateOne {
	_u.mutation.ResetRefererID()
	_u.mutation.SetRefererID(v)
	return _u
}

// SetNillableRefererID sets the "referer_id" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableRefererID(v *int64) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetRefererID(*v)
	}
	return _u
}

// AddRefererID adds value to the "referer_id" field.
func (_u *ProxyUserUpdateOne) AddRefererID(v int64) *ProxyUserUpdateOne {
	_u.mutation.AddRefererID(v)
	return _u
}

// ClearRefererID clears the value of the "referer_id" field.
func (_u *ProxyUserUpdateOne) ClearRefererID() *ProxyUserUpdateOne {
	_u.mutation.ClearRefererID()
	return _u
}

// SetCommission sets the "commission" field.
func (_u *ProxyUserUpdateOne) SetCommission(v int64) *ProxyUserUpdateOne {
	_u.mutation.ResetCommission()
	_u.mutation.SetCommission(v)
	return _u
}

// SetNillableCommission sets the "commission" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableCommission(v *int64) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetCommission(*v)
	}
	return _u
}

// AddCommission adds value to the "commission" field.
func (_u *ProxyUserUpdateOne) AddCommission(v int64) *ProxyUserUpdateOne {
	_u.mutation.AddCommission(v)
	return _u
}

// ClearCommission clears the value of the "commission" field.
func (_u *ProxyUserUpdateOne) ClearCommission() *ProxyUserUpdateOne {
	_u.mutation.ClearCommission()
	return _u
}

// SetReferralPercentage sets the "referral_percentage" field.
func (_u *ProxyUserUpdateOne) SetReferralPercentage(v int8) *ProxyUserUpdateOne {
	_u.mutation.ResetReferralPercentage()
	_u.mutation.SetReferralPercentage(v)
	return _u
}

// SetNillableReferralPercentage sets the "referral_percentage" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableReferralPercentage(v *int8) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetReferralPercentage(*v)
	}
	return _u
}

// AddReferralPercentage adds value to the "referral_percentage" field.
func (_u *ProxyUserUpdateOne) AddReferralPercentage(v int8) *ProxyUserUpdateOne {
	_u.mutation.AddReferralPercentage(v)
	return _u
}

// SetOnlyFirstPurchase sets the "only_first_purchase" field.
func (_u *ProxyUserUpdateOne) SetOnlyFirstPurchase(v bool) *ProxyUserUpdateOne {
	_u.mutation.SetOnlyFirstPurchase(v)
	return _u
}

// SetNillableOnlyFirstPurchase sets the "only_first_purchase" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableOnlyFirstPurchase(v *bool) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetOnlyFirstPurchase(*v)
	}
	return _u
}

// SetGiftAmount sets the "gift_amount" field.
func (_u *ProxyUserUpdateOne) SetGiftAmount(v int64) *ProxyUserUpdateOne {
	_u.mutation.ResetGiftAmount()
	_u.mutation.SetGiftAmount(v)
	return _u
}

// SetNillableGiftAmount sets the "gift_amount" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableGiftAmount(v *int64) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetGiftAmount(*v)
	}
	return _u
}

// AddGiftAmount adds value to the "gift_amount" field.
func (_u *ProxyUserUpdateOne) AddGiftAmount(v int64) *ProxyUserUpdateOne {
	_u.mutation.AddGiftAmount(v)
	return _u
}

// ClearGiftAmount clears the value of the "gift_amount" field.
func (_u *ProxyUserUpdateOne) ClearGiftAmount() *ProxyUserUpdateOne {
	_u.mutation.ClearGiftAmount()
	return _u
}

// SetEnable sets the "enable" field.
func (_u *ProxyUserUpdateOne) SetEnable(v bool) *ProxyUserUpdateOne {
	_u.mutation.SetEnable(v)
	return _u
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableEnable(v *bool) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetEnable(*v)
	}
	return _u
}

// SetIsAdmin sets the "is_admin" field.
func (_u *ProxyUserUpdateOne) SetIsAdmin(v bool) *ProxyUserUpdateOne {
	_u.mutation.SetIsAdmin(v)
	return _u
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableIsAdmin(v *bool) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetIsAdmin(*v)
	}
	return _u
}

// SetValidEmail sets the "valid_email" field.
func (_u *ProxyUserUpdateOne) SetValidEmail(v bool) *ProxyUserUpdateOne {
	_u.mutation.SetValidEmail(v)
	return _u
}

// SetNillableValidEmail sets the "valid_email" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableValidEmail(v *bool) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetValidEmail(*v)
	}
	return _u
}

// SetEnableEmailNotify sets the "enable_email_notify" field.
func (_u *ProxyUserUpdateOne) SetEnableEmailNotify(v bool) *ProxyUserUpdateOne {
	_u.mutation.SetEnableEmailNotify(v)
	return _u
}

// SetNillableEnableEmailNotify sets the "enable_email_notify" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableEnableEmailNotify(v *bool) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetEnableEmailNotify(*v)
	}
	return _u
}

// SetEnableTelegramNotify sets the "enable_telegram_notify" field.
func (_u *ProxyUserUpdateOne) SetEnableTelegramNotify(v bool) *ProxyUserUpdateOne {
	_u.mutation.SetEnableTelegramNotify(v)
	return _u
}

// SetNillableEnableTelegramNotify sets the "enable_telegram_notify" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableEnableTelegramNotify(v *bool) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetEnableTelegramNotify(*v)
	}
	return _u
}

// SetEnableBalanceNotify sets the "enable_balance_notify" field.
func (_u *ProxyUserUpdateOne) SetEnableBalanceNotify(v bool) *ProxyUserUpdateOne {
	_u.mutation.SetEnableBalanceNotify(v)
	return _u
}

// SetNillableEnableBalanceNotify sets the "enable_balance_notify" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableEnableBalanceNotify(v *bool) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetEnableBalanceNotify(*v)
	}
	return _u
}

// SetEnableLoginNotify sets the "enable_login_notify" field.
func (_u *ProxyUserUpdateOne) SetEnableLoginNotify(v bool) *ProxyUserUpdateOne {
	_u.mutation.SetEnableLoginNotify(v)
	return _u
}

// SetNillableEnableLoginNotify sets the "enable_login_notify" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableEnableLoginNotify(v *bool) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetEnableLoginNotify(*v)
	}
	return _u
}

// SetEnableSubscribeNotify sets the "enable_subscribe_notify" field.
func (_u *ProxyUserUpdateOne) SetEnableSubscribeNotify(v bool) *ProxyUserUpdateOne {
	_u.mutation.SetEnableSubscribeNotify(v)
	return _u
}

// SetNillableEnableSubscribeNotify sets the "enable_subscribe_notify" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableEnableSubscribeNotify(v *bool) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetEnableSubscribeNotify(*v)
	}
	return _u
}

// SetEnableTradeNotify sets the "enable_trade_notify" field.
func (_u *ProxyUserUpdateOne) SetEnableTradeNotify(v bool) *ProxyUserUpdateOne {
	_u.mutation.SetEnableTradeNotify(v)
	return _u
}

// SetNillableEnableTradeNotify sets the "enable_trade_notify" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableEnableTradeNotify(v *bool) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetEnableTradeNotify(*v)
	}
	return _u
}

// SetRules sets the "rules" field.
func (_u *ProxyUserUpdateOne) SetRules(v string) *ProxyUserUpdateOne {
	_u.mutation.SetRules(v)
	return _u
}

// SetNillableRules sets the "rules" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableRules(v *string) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetRules(*v)
	}
	return _u
}

// ClearRules clears the value of the "rules" field.
func (_u *ProxyUserUpdateOne) ClearRules() *ProxyUserUpdateOne {
	_u.mutation.ClearRules()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUserUpdateOne) SetUpdatedAt(v time.Time) *ProxyUserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyUserUpdateOne) SetDeletedAt(v time.Time) *ProxyUserUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableDeletedAt(v *time.Time) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyUserUpdateOne) ClearDeletedAt() *ProxyUserUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetIsDel sets the "is_del" field.
func (_u *ProxyUserUpdateOne) SetIsDel(v uint64) *ProxyUserUpdateOne {
	_u.mutation.ResetIsDel()
	_u.mutation.SetIsDel(v)
	return _u
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (_u *ProxyUserUpdateOne) SetNillableIsDel(v *uint64) *ProxyUserUpdateOne {
	if v != nil {
		_u.SetIsDel(*v)
	}
	return _u
}

// AddIsDel adds value to the "is_del" field.
func (_u *ProxyUserUpdateOne) AddIsDel(v int64) *ProxyUserUpdateOne {
	_u.mutation.AddIsDel(v)
	return _u
}

// ClearIsDel clears the value of the "is_del" field.
func (_u *ProxyUserUpdateOne) ClearIsDel() *ProxyUserUpdateOne {
	_u.mutation.ClearIsDel()
	return _u
}

// AddRedemptionRecordIDs adds the "redemption_records" edge to the ProxyRedemptionRecord entity by IDs.
func (_u *ProxyUserUpdateOne) AddRedemptionRecordIDs(ids ...int64) *ProxyUserUpdateOne {
	_u.mutation.AddRedemptionRecordIDs(ids...)
	return _u
}

// AddRedemptionRecords adds the "redemption_records" edges to the ProxyRedemptionRecord entity.
func (_u *ProxyUserUpdateOne) AddRedemptionRecords(v ...*ProxyRedemptionRecord) *ProxyUserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedemptionRecordIDs(ids...)
}

// AddWithdrawalIDs adds the "withdrawals" edge to the ProxyUserWithdrawal entity by IDs.
func (_u *ProxyUserUpdateOne) AddWithdrawalIDs(ids ...int64) *ProxyUserUpdateOne {
	_u.mutation.AddWithdrawalIDs(ids...)
	return _u
}

// AddWithdrawals adds the "withdrawals" edges to the ProxyUserWithdrawal entity.
func (_u *ProxyUserUpdateOne) AddWithdrawals(v ...*ProxyUserWithdrawal) *ProxyUserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWithdrawalIDs(ids...)
}

// Mutation returns the ProxyUserMutation object of the builder.
func (_u *ProxyUserUpdateOne) Mutation() *ProxyUserMutation {
	return _u.mutation
}

// ClearRedemptionRecords clears all "redemption_records" edges to the ProxyRedemptionRecord entity.
func (_u *ProxyUserUpdateOne) ClearRedemptionRecords() *ProxyUserUpdateOne {
	_u.mutation.ClearRedemptionRecords()
	return _u
}

// RemoveRedemptionRecordIDs removes the "redemption_records" edge to ProxyRedemptionRecord entities by IDs.
func (_u *ProxyUserUpdateOne) RemoveRedemptionRecordIDs(ids ...int64) *ProxyUserUpdateOne {
	_u.mutation.RemoveRedemptionRecordIDs(ids...)
	return _u
}

// RemoveRedemptionRecords removes "redemption_records" edges to ProxyRedemptionRecord entities.
func (_u *ProxyUserUpdateOne) RemoveRedemptionRecords(v ...*ProxyRedemptionRecord) *ProxyUserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedemptionRecordIDs(ids...)
}

// ClearWithdrawals clears all "withdrawals" edges to the ProxyUserWithdrawal entity.
func (_u *ProxyUserUpdateOne) ClearWithdrawals() *ProxyUserUpdateOne {
	_u.mutation.ClearWithdrawals()
	return _u
}

// RemoveWithdrawalIDs removes the "withdrawals" edge to ProxyUserWithdrawal entities by IDs.
func (_u *ProxyUserUpdateOne) RemoveWithdrawalIDs(ids ...int64) *ProxyUserUpdateOne {
	_u.mutation.RemoveWithdrawalIDs(ids...)
	return _u
}

// RemoveWithdrawals removes "withdrawals" edges to ProxyUserWithdrawal entities.
func (_u *ProxyUserUpdateOne) RemoveWithdrawals(v ...*ProxyUserWithdrawal) *ProxyUserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWithdrawalIDs(ids...)
}

// Where appends a list predicates to the ProxyUserUpdate builder.
func (_u *ProxyUserUpdateOne) Where(ps ...predicate.ProxyUser) *ProxyUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyUserUpdateOne) Select(field string, fields ...string) *ProxyUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyUser entity.
func (_u *ProxyUserUpdateOne) Save(ctx context.Context) (*ProxyUser, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUserUpdateOne) SaveX(ctx context.Context) *ProxyUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyUserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUserUpdateOne) check() error {
	if v, ok := _u.mutation.Password(); ok {
		if err := proxyuser.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Algo(); ok {
		if err := proxyuser.AlgoValidator(v); err != nil {
			return &ValidationError{Name: "algo", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.algo": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Salt(); ok {
		if err := proxyuser.SaltValidator(v); err != nil {
			return &ValidationError{Name: "salt", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.salt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReferCode(); ok {
		if err := proxyuser.ReferCodeValidator(v); err != nil {
			return &ValidationError{Name: "refer_code", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.refer_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyUserUpdateOne) sqlSave(ctx context.Context) (_node *ProxyUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyuser.Table, proxyuser.Columns, sqlgraph.NewFieldSpec(proxyuser.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxyuser.FieldID)
		for _, f := range fields {
			if !proxyuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxyuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(proxyuser.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Algo(); ok {
		_spec.SetField(proxyuser.FieldAlgo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Salt(); ok {
		_spec.SetField(proxyuser.FieldSalt, field.TypeString, value)
	}
	if _u.mutation.SaltCleared() {
		_spec.ClearField(proxyuser.FieldSalt, field.TypeString)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(proxyuser.FieldAvatar, field.TypeString, value)
	}
	if _u.mutation.AvatarCleared() {
		_spec.ClearField(proxyuser.FieldAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(proxyuser.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(proxyuser.FieldBalance, field.TypeInt64, value)
	}
	if _u.mutation.BalanceCleared() {
		_spec.ClearField(proxyuser.FieldBalance, field.TypeInt64)
	}
	if value, ok := _u.mutation.Telegram(); ok {
		_spec.SetField(proxyuser.FieldTelegram, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegram(); ok {
		_spec.AddField(proxyuser.FieldTelegram, field.TypeInt64, value)
	}
	if _u.mutation.TelegramCleared() {
		_spec.ClearField(proxyuser.FieldTelegram, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReferCode(); ok {
		_spec.SetField(proxyuser.FieldReferCode, field.TypeString, value)
	}
	if _u.mutation.ReferCodeCleared() {
		_spec.ClearField(proxyuser.FieldReferCode, field.TypeString)
	}
	if value, ok := _u.mutation.RefererID(); ok {
		_spec.SetField(proxyuser.FieldRefererID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefererID(); ok {
		_spec.AddField(proxyuser.FieldRefererID, field.TypeInt64, value)
	}
	if _u.mutation.RefererIDCleared() {
		_spec.ClearField(proxyuser.FieldRefererID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Commission(); ok {
		_spec.SetField(proxyuser.FieldCommission, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCommission(); ok {
		_spec.AddField(proxyuser.FieldCommission, field.TypeInt64, value)
	}
	if _u.mutation.CommissionCleared() {
		_spec.ClearField(proxyuser.FieldCommission, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReferralPercentage(); ok {
		_spec.SetField(proxyuser.FieldReferralPercentage, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedReferralPercentage(); ok {
		_spec.AddField(proxyuser.FieldReferralPercentage, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.OnlyFirstPurchase(); ok {
		_spec.SetField(proxyuser.FieldOnlyFirstPurchase, field.TypeBool, value)
	}
	if value, ok := _u.mutation.GiftAmount(); ok {
		_spec.SetField(proxyuser.FieldGiftAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGiftAmount(); ok {
		_spec.AddField(proxyuser.FieldGiftAmount, field.TypeInt64, value)
	}
	if _u.mutation.GiftAmountCleared() {
		_spec.ClearField(proxyuser.FieldGiftAmount, field.TypeInt64)
	}
	if value, ok := _u.mutation.Enable(); ok {
		_spec.SetField(proxyuser.FieldEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsAdmin(); ok {
		_spec.SetField(proxyuser.FieldIsAdmin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ValidEmail(); ok {
		_spec.SetField(proxyuser.FieldValidEmail, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableEmailNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableEmailNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableTelegramNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableTelegramNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableBalanceNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableBalanceNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableLoginNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableLoginNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableSubscribeNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableSubscribeNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableTradeNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableTradeNotify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Rules(); ok {
		_spec.SetField(proxyuser.FieldRules, field.TypeString, value)
	}
	if _u.mutation.RulesCleared() {
		_spec.ClearField(proxyuser.FieldRules, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxyuser.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxyuser.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsDel(); ok {
		_spec.SetField(proxyuser.FieldIsDel, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedIsDel(); ok {
		_spec.AddField(proxyuser.FieldIsDel, field.TypeUint64, value)
	}
	if _u.mutation.IsDelCleared() {
		_spec.ClearField(proxyuser.FieldIsDel, field.TypeUint64)
	}
	if _u.mutation.RedemptionRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.RedemptionRecordsTable,
			Columns: []string{proxyuser.RedemptionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyredemptionrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedemptionRecordsIDs(); len(nodes) > 0 && !_u.mutation.RedemptionRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.RedemptionRecordsTable,
			Columns: []string{proxyuser.RedemptionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyredemptionrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedemptionRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.RedemptionRecordsTable,
			Columns: []string{proxyuser.RedemptionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyredemptionrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.WithdrawalsTable,
			Columns: []string{proxyuser.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyuserwithdrawal.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWithdrawalsIDs(); len(nodes) > 0 && !_u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.WithdrawalsTable,
			Columns: []string{proxyuser.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyuserwithdrawal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   proxyuser.WithdrawalsTable,
			Columns: []string{proxyuser.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxyuserwithdrawal.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProxyUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
