// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/npanel-pro/ent/predicate"
	"github.com/OmnTeam/npanel-pro/ent/proxyredemptioncode"
	"github.com/OmnTeam/npanel-pro/ent/proxyredemptionrecord"
	"github.com/OmnTeam/npanel-pro/ent/proxyuser"
)

// ProxyRedemptionRecordQuery is the builder for querying ProxyRedemptionRecord entities.
type ProxyRedemptionRecordQuery struct {
	config
	ctx                *QueryContext
	order              []proxyredemptionrecord.OrderOption
	inters             []Interceptor
	predicates         []predicate.ProxyRedemptionRecord
	withUser           *ProxyUserQuery
	withRedemptionCode *ProxyRedemptionCodeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProxyRedemptionRecordQuery builder.
func (_q *ProxyRedemptionRecordQuery) Where(ps ...predicate.ProxyRedemptionRecord) *ProxyRedemptionRecordQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProxyRedemptionRecordQuery) Limit(limit int) *ProxyRedemptionRecordQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProxyRedemptionRecordQuery) Offset(offset int) *ProxyRedemptionRecordQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProxyRedemptionRecordQuery) Unique(unique bool) *ProxyRedemptionRecordQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProxyRedemptionRecordQuery) Order(o ...proxyredemptionrecord.OrderOption) *ProxyRedemptionRecordQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *ProxyRedemptionRecordQuery) QueryUser() *ProxyUserQuery {
	query := (&ProxyUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(proxyredemptionrecord.Table, proxyredemptionrecord.FieldID, selector),
			sqlgraph.To(proxyuser.Table, proxyuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, proxyredemptionrecord.UserTable, proxyredemptionrecord.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRedemptionCode chains the current query on the "redemption_code" edge.
func (_q *ProxyRedemptionRecordQuery) QueryRedemptionCode() *ProxyRedemptionCodeQuery {
	query := (&ProxyRedemptionCodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(proxyredemptionrecord.Table, proxyredemptionrecord.FieldID, selector),
			sqlgraph.To(proxyredemptioncode.Table, proxyredemptioncode.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, proxyredemptionrecord.RedemptionCodeTable, proxyredemptionrecord.RedemptionCodeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProxyRedemptionRecord entity from the query.
// Returns a *NotFoundError when no ProxyRedemptionRecord was found.
func (_q *ProxyRedemptionRecordQuery) First(ctx context.Context) (*ProxyRedemptionRecord, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{proxyredemptionrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProxyRedemptionRecordQuery) FirstX(ctx context.Context) *ProxyRedemptionRecord {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProxyRedemptionRecord ID from the query.
// Returns a *NotFoundError when no ProxyRedemptionRecord ID was found.
func (_q *ProxyRedemptionRecordQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{proxyredemptionrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ProxyRedemptionRecordQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProxyRedemptionRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProxyRedemptionRecord entity is found.
// Returns a *NotFoundError when no ProxyRedemptionRecord entities are found.
func (_q *ProxyRedemptionRecordQuery) Only(ctx context.Context) (*ProxyRedemptionRecord, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{proxyredemptionrecord.Label}
	default:
		return nil, &NotSingularError{proxyredemptionrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProxyRedemptionRecordQuery) OnlyX(ctx context.Context) *ProxyRedemptionRecord {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProxyRedemptionRecord ID in the query.
// Returns a *NotSingularError when more than one ProxyRedemptionRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ProxyRedemptionRecordQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{proxyredemptionrecord.Label}
	default:
		err = &NotSingularError{proxyredemptionrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ProxyRedemptionRecordQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProxyRedemptionRecords.
func (_q *ProxyRedemptionRecordQuery) All(ctx context.Context) ([]*ProxyRedemptionRecord, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProxyRedemptionRecord, *ProxyRedemptionRecordQuery]()
	return withInterceptors[[]*ProxyRedemptionRecord](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProxyRedemptionRecordQuery) AllX(ctx context.Context) []*ProxyRedemptionRecord {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProxyRedemptionRecord IDs.
func (_q *ProxyRedemptionRecordQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(proxyredemptionrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ProxyRedemptionRecordQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ProxyRedemptionRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProxyRedemptionRecordQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProxyRedemptionRecordQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProxyRedemptionRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProxyRedemptionRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProxyRedemptionRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProxyRedemptionRecordQuery) Clone() *ProxyRedemptionRecordQuery {
	if _q == nil {
		return nil
	}
	return &ProxyRedemptionRecordQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]proxyredemptionrecord.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.ProxyRedemptionRecord{}, _q.predicates...),
		withUser:           _q.withUser.Clone(),
		withRedemptionCode: _q.withRedemptionCode.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProxyRedemptionRecordQuery) WithUser(opts ...func(*ProxyUserQuery)) *ProxyRedemptionRecordQuery {
	query := (&ProxyUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithRedemptionCode tells the query-builder to eager-load the nodes that are connected to
// the "redemption_code" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProxyRedemptionRecordQuery) WithRedemptionCode(opts ...func(*ProxyRedemptionCodeQuery)) *ProxyRedemptionRecordQuery {
	query := (&ProxyRedemptionCodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRedemptionCode = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RedemptionCodeID int64 `json:"redemption_code_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProxyRedemptionRecord.Query().
//		GroupBy(proxyredemptionrecord.FieldRedemptionCodeID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ProxyRedemptionRecordQuery) GroupBy(field string, fields ...string) *ProxyRedemptionRecordGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProxyRedemptionRecordGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = proxyredemptionrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RedemptionCodeID int64 `json:"redemption_code_id,omitempty"`
//	}
//
//	client.ProxyRedemptionRecord.Query().
//		Select(proxyredemptionrecord.FieldRedemptionCodeID).
//		Scan(ctx, &v)
func (_q *ProxyRedemptionRecordQuery) Select(fields ...string) *ProxyRedemptionRecordSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProxyRedemptionRecordSelect{ProxyRedemptionRecordQuery: _q}
	sbuild.label = proxyredemptionrecord.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProxyRedemptionRecordSelect configured with the given aggregations.
func (_q *ProxyRedemptionRecordQuery) Aggregate(fns ...AggregateFunc) *ProxyRedemptionRecordSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProxyRedemptionRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !proxyredemptionrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProxyRedemptionRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProxyRedemptionRecord, error) {
	var (
		nodes       = []*ProxyRedemptionRecord{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withUser != nil,
			_q.withRedemptionCode != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProxyRedemptionRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProxyRedemptionRecord{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *ProxyRedemptionRecord, e *ProxyUser) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRedemptionCode; query != nil {
		if err := _q.loadRedemptionCode(ctx, query, nodes, nil,
			func(n *ProxyRedemptionRecord, e *ProxyRedemptionCode) { n.Edges.RedemptionCode = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProxyRedemptionRecordQuery) loadUser(ctx context.Context, query *ProxyUserQuery, nodes []*ProxyRedemptionRecord, init func(*ProxyRedemptionRecord), assign func(*ProxyRedemptionRecord, *ProxyUser)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ProxyRedemptionRecord)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(proxyuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProxyRedemptionRecordQuery) loadRedemptionCode(ctx context.Context, query *ProxyRedemptionCodeQuery, nodes []*ProxyRedemptionRecord, init func(*ProxyRedemptionRecord), assign func(*ProxyRedemptionRecord, *ProxyRedemptionCode)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*ProxyRedemptionRecord)
	for i := range nodes {
		fk := nodes[i].RedemptionCodeID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(proxyredemptioncode.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "redemption_code_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ProxyRedemptionRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProxyRedemptionRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(proxyredemptionrecord.Table, proxyredemptionrecord.Columns, sqlgraph.NewFieldSpec(proxyredemptionrecord.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxyredemptionrecord.FieldID)
		for i := range fields {
			if fields[i] != proxyredemptionrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(proxyredemptionrecord.FieldUserID)
		}
		if _q.withRedemptionCode != nil {
			_spec.Node.AddColumnOnce(proxyredemptionrecord.FieldRedemptionCodeID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProxyRedemptionRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(proxyredemptionrecord.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = proxyredemptionrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProxyRedemptionRecordGroupBy is the group-by builder for ProxyRedemptionRecord entities.
type ProxyRedemptionRecordGroupBy struct {
	selector
	build *ProxyRedemptionRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProxyRedemptionRecordGroupBy) Aggregate(fns ...AggregateFunc) *ProxyRedemptionRecordGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProxyRedemptionRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProxyRedemptionRecordQuery, *ProxyRedemptionRecordGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProxyRedemptionRecordGroupBy) sqlScan(ctx context.Context, root *ProxyRedemptionRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProxyRedemptionRecordSelect is the builder for selecting fields of ProxyRedemptionRecord entities.
type ProxyRedemptionRecordSelect struct {
	*ProxyRedemptionRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProxyRedemptionRecordSelect) Aggregate(fns ...AggregateFunc) *ProxyRedemptionRecordSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProxyRedemptionRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProxyRedemptionRecordQuery, *ProxyRedemptionRecordSelect](ctx, _s.ProxyRedemptionRecordQuery, _s, _s.inters, v)
}

func (_s *ProxyRedemptionRecordSelect) sqlScan(ctx context.Context, root *ProxyRedemptionRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
