// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/ppanel-pro/ent/proxyuser"
)

// ProxyUserCreate is the builder for creating a ProxyUser entity.
type ProxyUserCreate struct {
	config
	mutation *ProxyUserMutation
	hooks    []Hook
}

// SetPassword sets the "password" field.
func (_c *ProxyUserCreate) SetPassword(v string) *ProxyUserCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetAlgo sets the "algo" field.
func (_c *ProxyUserCreate) SetAlgo(v string) *ProxyUserCreate {
	_c.mutation.SetAlgo(v)
	return _c
}

// SetNillableAlgo sets the "algo" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableAlgo(v *string) *ProxyUserCreate {
	if v != nil {
		_c.SetAlgo(*v)
	}
	return _c
}

// SetSalt sets the "salt" field.
func (_c *ProxyUserCreate) SetSalt(v string) *ProxyUserCreate {
	_c.mutation.SetSalt(v)
	return _c
}

// SetNillableSalt sets the "salt" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableSalt(v *string) *ProxyUserCreate {
	if v != nil {
		_c.SetSalt(*v)
	}
	return _c
}

// SetAvatar sets the "avatar" field.
func (_c *ProxyUserCreate) SetAvatar(v string) *ProxyUserCreate {
	_c.mutation.SetAvatar(v)
	return _c
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableAvatar(v *string) *ProxyUserCreate {
	if v != nil {
		_c.SetAvatar(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ProxyUserCreate) SetTenantID(v int64) *ProxyUserCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableTenantID(v *int64) *ProxyUserCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetBalance sets the "balance" field.
func (_c *ProxyUserCreate) SetBalance(v int64) *ProxyUserCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableBalance(v *int64) *ProxyUserCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetTelegram sets the "telegram" field.
func (_c *ProxyUserCreate) SetTelegram(v int64) *ProxyUserCreate {
	_c.mutation.SetTelegram(v)
	return _c
}

// SetNillableTelegram sets the "telegram" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableTelegram(v *int64) *ProxyUserCreate {
	if v != nil {
		_c.SetTelegram(*v)
	}
	return _c
}

// SetReferCode sets the "refer_code" field.
func (_c *ProxyUserCreate) SetReferCode(v string) *ProxyUserCreate {
	_c.mutation.SetReferCode(v)
	return _c
}

// SetNillableReferCode sets the "refer_code" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableReferCode(v *string) *ProxyUserCreate {
	if v != nil {
		_c.SetReferCode(*v)
	}
	return _c
}

// SetRefererID sets the "referer_id" field.
func (_c *ProxyUserCreate) SetRefererID(v int) *ProxyUserCreate {
	_c.mutation.SetRefererID(v)
	return _c
}

// SetNillableRefererID sets the "referer_id" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableRefererID(v *int) *ProxyUserCreate {
	if v != nil {
		_c.SetRefererID(*v)
	}
	return _c
}

// SetCommission sets the "commission" field.
func (_c *ProxyUserCreate) SetCommission(v int64) *ProxyUserCreate {
	_c.mutation.SetCommission(v)
	return _c
}

// SetNillableCommission sets the "commission" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableCommission(v *int64) *ProxyUserCreate {
	if v != nil {
		_c.SetCommission(*v)
	}
	return _c
}

// SetReferralPercentage sets the "referral_percentage" field.
func (_c *ProxyUserCreate) SetReferralPercentage(v int) *ProxyUserCreate {
	_c.mutation.SetReferralPercentage(v)
	return _c
}

// SetNillableReferralPercentage sets the "referral_percentage" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableReferralPercentage(v *int) *ProxyUserCreate {
	if v != nil {
		_c.SetReferralPercentage(*v)
	}
	return _c
}

// SetOnlyFirstPurchase sets the "only_first_purchase" field.
func (_c *ProxyUserCreate) SetOnlyFirstPurchase(v bool) *ProxyUserCreate {
	_c.mutation.SetOnlyFirstPurchase(v)
	return _c
}

// SetNillableOnlyFirstPurchase sets the "only_first_purchase" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableOnlyFirstPurchase(v *bool) *ProxyUserCreate {
	if v != nil {
		_c.SetOnlyFirstPurchase(*v)
	}
	return _c
}

// SetGiftAmount sets the "gift_amount" field.
func (_c *ProxyUserCreate) SetGiftAmount(v int64) *ProxyUserCreate {
	_c.mutation.SetGiftAmount(v)
	return _c
}

// SetNillableGiftAmount sets the "gift_amount" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableGiftAmount(v *int64) *ProxyUserCreate {
	if v != nil {
		_c.SetGiftAmount(*v)
	}
	return _c
}

// SetEnable sets the "enable" field.
func (_c *ProxyUserCreate) SetEnable(v bool) *ProxyUserCreate {
	_c.mutation.SetEnable(v)
	return _c
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableEnable(v *bool) *ProxyUserCreate {
	if v != nil {
		_c.SetEnable(*v)
	}
	return _c
}

// SetIsAdmin sets the "is_admin" field.
func (_c *ProxyUserCreate) SetIsAdmin(v bool) *ProxyUserCreate {
	_c.mutation.SetIsAdmin(v)
	return _c
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableIsAdmin(v *bool) *ProxyUserCreate {
	if v != nil {
		_c.SetIsAdmin(*v)
	}
	return _c
}

// SetValidEmail sets the "valid_email" field.
func (_c *ProxyUserCreate) SetValidEmail(v bool) *ProxyUserCreate {
	_c.mutation.SetValidEmail(v)
	return _c
}

// SetNillableValidEmail sets the "valid_email" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableValidEmail(v *bool) *ProxyUserCreate {
	if v != nil {
		_c.SetValidEmail(*v)
	}
	return _c
}

// SetEnableEmailNotify sets the "enable_email_notify" field.
func (_c *ProxyUserCreate) SetEnableEmailNotify(v bool) *ProxyUserCreate {
	_c.mutation.SetEnableEmailNotify(v)
	return _c
}

// SetNillableEnableEmailNotify sets the "enable_email_notify" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableEnableEmailNotify(v *bool) *ProxyUserCreate {
	if v != nil {
		_c.SetEnableEmailNotify(*v)
	}
	return _c
}

// SetEnableTelegramNotify sets the "enable_telegram_notify" field.
func (_c *ProxyUserCreate) SetEnableTelegramNotify(v bool) *ProxyUserCreate {
	_c.mutation.SetEnableTelegramNotify(v)
	return _c
}

// SetNillableEnableTelegramNotify sets the "enable_telegram_notify" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableEnableTelegramNotify(v *bool) *ProxyUserCreate {
	if v != nil {
		_c.SetEnableTelegramNotify(*v)
	}
	return _c
}

// SetEnableBalanceNotify sets the "enable_balance_notify" field.
func (_c *ProxyUserCreate) SetEnableBalanceNotify(v bool) *ProxyUserCreate {
	_c.mutation.SetEnableBalanceNotify(v)
	return _c
}

// SetNillableEnableBalanceNotify sets the "enable_balance_notify" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableEnableBalanceNotify(v *bool) *ProxyUserCreate {
	if v != nil {
		_c.SetEnableBalanceNotify(*v)
	}
	return _c
}

// SetEnableLoginNotify sets the "enable_login_notify" field.
func (_c *ProxyUserCreate) SetEnableLoginNotify(v bool) *ProxyUserCreate {
	_c.mutation.SetEnableLoginNotify(v)
	return _c
}

// SetNillableEnableLoginNotify sets the "enable_login_notify" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableEnableLoginNotify(v *bool) *ProxyUserCreate {
	if v != nil {
		_c.SetEnableLoginNotify(*v)
	}
	return _c
}

// SetEnableSubscribeNotify sets the "enable_subscribe_notify" field.
func (_c *ProxyUserCreate) SetEnableSubscribeNotify(v bool) *ProxyUserCreate {
	_c.mutation.SetEnableSubscribeNotify(v)
	return _c
}

// SetNillableEnableSubscribeNotify sets the "enable_subscribe_notify" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableEnableSubscribeNotify(v *bool) *ProxyUserCreate {
	if v != nil {
		_c.SetEnableSubscribeNotify(*v)
	}
	return _c
}

// SetEnableTradeNotify sets the "enable_trade_notify" field.
func (_c *ProxyUserCreate) SetEnableTradeNotify(v bool) *ProxyUserCreate {
	_c.mutation.SetEnableTradeNotify(v)
	return _c
}

// SetNillableEnableTradeNotify sets the "enable_trade_notify" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableEnableTradeNotify(v *bool) *ProxyUserCreate {
	if v != nil {
		_c.SetEnableTradeNotify(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProxyUserCreate) SetCreatedAt(v time.Time) *ProxyUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableCreatedAt(v *time.Time) *ProxyUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProxyUserCreate) SetUpdatedAt(v time.Time) *ProxyUserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableUpdatedAt(v *time.Time) *ProxyUserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ProxyUserCreate) SetDeletedAt(v time.Time) *ProxyUserCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableDeletedAt(v *time.Time) *ProxyUserCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetIsDel sets the "is_del" field.
func (_c *ProxyUserCreate) SetIsDel(v bool) *ProxyUserCreate {
	_c.mutation.SetIsDel(v)
	return _c
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (_c *ProxyUserCreate) SetNillableIsDel(v *bool) *ProxyUserCreate {
	if v != nil {
		_c.SetIsDel(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProxyUserCreate) SetID(v int) *ProxyUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ProxyUserMutation object of the builder.
func (_c *ProxyUserCreate) Mutation() *ProxyUserMutation {
	return _c.mutation
}

// Save creates the ProxyUser in the database.
func (_c *ProxyUserCreate) Save(ctx context.Context) (*ProxyUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProxyUserCreate) SaveX(ctx context.Context) *ProxyUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProxyUserCreate) defaults() {
	if _, ok := _c.mutation.Algo(); !ok {
		v := proxyuser.DefaultAlgo
		_c.mutation.SetAlgo(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := proxyuser.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Balance(); !ok {
		v := proxyuser.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	if _, ok := _c.mutation.Commission(); !ok {
		v := proxyuser.DefaultCommission
		_c.mutation.SetCommission(v)
	}
	if _, ok := _c.mutation.ReferralPercentage(); !ok {
		v := proxyuser.DefaultReferralPercentage
		_c.mutation.SetReferralPercentage(v)
	}
	if _, ok := _c.mutation.OnlyFirstPurchase(); !ok {
		v := proxyuser.DefaultOnlyFirstPurchase
		_c.mutation.SetOnlyFirstPurchase(v)
	}
	if _, ok := _c.mutation.GiftAmount(); !ok {
		v := proxyuser.DefaultGiftAmount
		_c.mutation.SetGiftAmount(v)
	}
	if _, ok := _c.mutation.Enable(); !ok {
		v := proxyuser.DefaultEnable
		_c.mutation.SetEnable(v)
	}
	if _, ok := _c.mutation.IsAdmin(); !ok {
		v := proxyuser.DefaultIsAdmin
		_c.mutation.SetIsAdmin(v)
	}
	if _, ok := _c.mutation.ValidEmail(); !ok {
		v := proxyuser.DefaultValidEmail
		_c.mutation.SetValidEmail(v)
	}
	if _, ok := _c.mutation.EnableEmailNotify(); !ok {
		v := proxyuser.DefaultEnableEmailNotify
		_c.mutation.SetEnableEmailNotify(v)
	}
	if _, ok := _c.mutation.EnableTelegramNotify(); !ok {
		v := proxyuser.DefaultEnableTelegramNotify
		_c.mutation.SetEnableTelegramNotify(v)
	}
	if _, ok := _c.mutation.EnableBalanceNotify(); !ok {
		v := proxyuser.DefaultEnableBalanceNotify
		_c.mutation.SetEnableBalanceNotify(v)
	}
	if _, ok := _c.mutation.EnableLoginNotify(); !ok {
		v := proxyuser.DefaultEnableLoginNotify
		_c.mutation.SetEnableLoginNotify(v)
	}
	if _, ok := _c.mutation.EnableSubscribeNotify(); !ok {
		v := proxyuser.DefaultEnableSubscribeNotify
		_c.mutation.SetEnableSubscribeNotify(v)
	}
	if _, ok := _c.mutation.EnableTradeNotify(); !ok {
		v := proxyuser.DefaultEnableTradeNotify
		_c.mutation.SetEnableTradeNotify(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := proxyuser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := proxyuser.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsDel(); !ok {
		v := proxyuser.DefaultIsDel
		_c.mutation.SetIsDel(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProxyUserCreate) check() error {
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "ProxyUser.password"`)}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := proxyuser.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Algo(); !ok {
		return &ValidationError{Name: "algo", err: errors.New(`ent: missing required field "ProxyUser.algo"`)}
	}
	if v, ok := _c.mutation.Algo(); ok {
		if err := proxyuser.AlgoValidator(v); err != nil {
			return &ValidationError{Name: "algo", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.algo": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Salt(); ok {
		if err := proxyuser.SaltValidator(v); err != nil {
			return &ValidationError{Name: "salt", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.salt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ProxyUser.tenant_id"`)}
	}
	if v, ok := _c.mutation.ReferCode(); ok {
		if err := proxyuser.ReferCodeValidator(v); err != nil {
			return &ValidationError{Name: "refer_code", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.refer_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReferralPercentage(); !ok {
		return &ValidationError{Name: "referral_percentage", err: errors.New(`ent: missing required field "ProxyUser.referral_percentage"`)}
	}
	if _, ok := _c.mutation.OnlyFirstPurchase(); !ok {
		return &ValidationError{Name: "only_first_purchase", err: errors.New(`ent: missing required field "ProxyUser.only_first_purchase"`)}
	}
	if _, ok := _c.mutation.Enable(); !ok {
		return &ValidationError{Name: "enable", err: errors.New(`ent: missing required field "ProxyUser.enable"`)}
	}
	if _, ok := _c.mutation.IsAdmin(); !ok {
		return &ValidationError{Name: "is_admin", err: errors.New(`ent: missing required field "ProxyUser.is_admin"`)}
	}
	if _, ok := _c.mutation.ValidEmail(); !ok {
		return &ValidationError{Name: "valid_email", err: errors.New(`ent: missing required field "ProxyUser.valid_email"`)}
	}
	if _, ok := _c.mutation.EnableEmailNotify(); !ok {
		return &ValidationError{Name: "enable_email_notify", err: errors.New(`ent: missing required field "ProxyUser.enable_email_notify"`)}
	}
	if _, ok := _c.mutation.EnableTelegramNotify(); !ok {
		return &ValidationError{Name: "enable_telegram_notify", err: errors.New(`ent: missing required field "ProxyUser.enable_telegram_notify"`)}
	}
	if _, ok := _c.mutation.EnableBalanceNotify(); !ok {
		return &ValidationError{Name: "enable_balance_notify", err: errors.New(`ent: missing required field "ProxyUser.enable_balance_notify"`)}
	}
	if _, ok := _c.mutation.EnableLoginNotify(); !ok {
		return &ValidationError{Name: "enable_login_notify", err: errors.New(`ent: missing required field "ProxyUser.enable_login_notify"`)}
	}
	if _, ok := _c.mutation.EnableSubscribeNotify(); !ok {
		return &ValidationError{Name: "enable_subscribe_notify", err: errors.New(`ent: missing required field "ProxyUser.enable_subscribe_notify"`)}
	}
	if _, ok := _c.mutation.EnableTradeNotify(); !ok {
		return &ValidationError{Name: "enable_trade_notify", err: errors.New(`ent: missing required field "ProxyUser.enable_trade_notify"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProxyUser.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProxyUser.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := proxyuser.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ProxyUser.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ProxyUserCreate) sqlSave(ctx context.Context) (*ProxyUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProxyUserCreate) createSpec() (*ProxyUser, *sqlgraph.CreateSpec) {
	var (
		_node = &ProxyUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(proxyuser.Table, sqlgraph.NewFieldSpec(proxyuser.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(proxyuser.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.Algo(); ok {
		_spec.SetField(proxyuser.FieldAlgo, field.TypeString, value)
		_node.Algo = value
	}
	if value, ok := _c.mutation.Salt(); ok {
		_spec.SetField(proxyuser.FieldSalt, field.TypeString, value)
		_node.Salt = &value
	}
	if value, ok := _c.mutation.Avatar(); ok {
		_spec.SetField(proxyuser.FieldAvatar, field.TypeString, value)
		_node.Avatar = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(proxyuser.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(proxyuser.FieldBalance, field.TypeInt64, value)
		_node.Balance = &value
	}
	if value, ok := _c.mutation.Telegram(); ok {
		_spec.SetField(proxyuser.FieldTelegram, field.TypeInt64, value)
		_node.Telegram = &value
	}
	if value, ok := _c.mutation.ReferCode(); ok {
		_spec.SetField(proxyuser.FieldReferCode, field.TypeString, value)
		_node.ReferCode = &value
	}
	if value, ok := _c.mutation.RefererID(); ok {
		_spec.SetField(proxyuser.FieldRefererID, field.TypeInt, value)
		_node.RefererID = &value
	}
	if value, ok := _c.mutation.Commission(); ok {
		_spec.SetField(proxyuser.FieldCommission, field.TypeInt64, value)
		_node.Commission = &value
	}
	if value, ok := _c.mutation.ReferralPercentage(); ok {
		_spec.SetField(proxyuser.FieldReferralPercentage, field.TypeInt, value)
		_node.ReferralPercentage = value
	}
	if value, ok := _c.mutation.OnlyFirstPurchase(); ok {
		_spec.SetField(proxyuser.FieldOnlyFirstPurchase, field.TypeBool, value)
		_node.OnlyFirstPurchase = value
	}
	if value, ok := _c.mutation.GiftAmount(); ok {
		_spec.SetField(proxyuser.FieldGiftAmount, field.TypeInt64, value)
		_node.GiftAmount = &value
	}
	if value, ok := _c.mutation.Enable(); ok {
		_spec.SetField(proxyuser.FieldEnable, field.TypeBool, value)
		_node.Enable = value
	}
	if value, ok := _c.mutation.IsAdmin(); ok {
		_spec.SetField(proxyuser.FieldIsAdmin, field.TypeBool, value)
		_node.IsAdmin = value
	}
	if value, ok := _c.mutation.ValidEmail(); ok {
		_spec.SetField(proxyuser.FieldValidEmail, field.TypeBool, value)
		_node.ValidEmail = value
	}
	if value, ok := _c.mutation.EnableEmailNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableEmailNotify, field.TypeBool, value)
		_node.EnableEmailNotify = value
	}
	if value, ok := _c.mutation.EnableTelegramNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableTelegramNotify, field.TypeBool, value)
		_node.EnableTelegramNotify = value
	}
	if value, ok := _c.mutation.EnableBalanceNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableBalanceNotify, field.TypeBool, value)
		_node.EnableBalanceNotify = value
	}
	if value, ok := _c.mutation.EnableLoginNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableLoginNotify, field.TypeBool, value)
		_node.EnableLoginNotify = value
	}
	if value, ok := _c.mutation.EnableSubscribeNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableSubscribeNotify, field.TypeBool, value)
		_node.EnableSubscribeNotify = value
	}
	if value, ok := _c.mutation.EnableTradeNotify(); ok {
		_spec.SetField(proxyuser.FieldEnableTradeNotify, field.TypeBool, value)
		_node.EnableTradeNotify = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(proxyuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyuser.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(proxyuser.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.IsDel(); ok {
		_spec.SetField(proxyuser.FieldIsDel, field.TypeBool, value)
		_node.IsDel = &value
	}
	return _node, _spec
}

// ProxyUserCreateBulk is the builder for creating many ProxyUser entities in bulk.
type ProxyUserCreateBulk struct {
	config
	err      error
	builders []*ProxyUserCreate
}

// Save creates the ProxyUser entities in the database.
func (_c *ProxyUserCreateBulk) Save(ctx context.Context) ([]*ProxyUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProxyUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProxyUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProxyUserCreateBulk) SaveX(ctx context.Context) []*ProxyUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProxyUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProxyUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
