// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/npanel-pro/ent/predicate"
	"github.com/OmnTeam/npanel-pro/ent/proxyticket"
)

// ProxyTicketDelete is the builder for deleting a ProxyTicket entity.
type ProxyTicketDelete struct {
	config
	hooks    []Hook
	mutation *ProxyTicketMutation
}

// Where appends a list predicates to the ProxyTicketDelete builder.
func (_d *ProxyTicketDelete) Where(ps ...predicate.ProxyTicket) *ProxyTicketDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ProxyTicketDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyTicketDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ProxyTicketDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(proxyticket.Table, sqlgraph.NewFieldSpec(proxyticket.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ProxyTicketDeleteOne is the builder for deleting a single ProxyTicket entity.
type ProxyTicketDeleteOne struct {
	_d *ProxyTicketDelete
}

// Where appends a list predicates to the ProxyTicketDelete builder.
func (_d *ProxyTicketDeleteOne) Where(ps ...predicate.ProxyTicket) *ProxyTicketDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ProxyTicketDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{proxyticket.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ProxyTicketDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
