// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OmnTeam/ppanel-pro/ent/predicate"
	"github.com/OmnTeam/ppanel-pro/ent/proxyannouncement"
)

// ProxyAnnouncementUpdate is the builder for updating ProxyAnnouncement entities.
type ProxyAnnouncementUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyAnnouncementMutation
}

// Where appends a list predicates to the ProxyAnnouncementUpdate builder.
func (_u *ProxyAnnouncementUpdate) Where(ps ...predicate.ProxyAnnouncement) *ProxyAnnouncementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProxyAnnouncementUpdate) SetTitle(v string) *ProxyAnnouncementUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProxyAnnouncementUpdate) SetNillableTitle(v *string) *ProxyAnnouncementUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ProxyAnnouncementUpdate) SetContent(v string) *ProxyAnnouncementUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ProxyAnnouncementUpdate) SetNillableContent(v *string) *ProxyAnnouncementUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ProxyAnnouncementUpdate) ClearContent() *ProxyAnnouncementUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetShow sets the "show" field.
func (_u *ProxyAnnouncementUpdate) SetShow(v bool) *ProxyAnnouncementUpdate {
	_u.mutation.SetShow(v)
	return _u
}

// SetNillableShow sets the "show" field if the given value is not nil.
func (_u *ProxyAnnouncementUpdate) SetNillableShow(v *bool) *ProxyAnnouncementUpdate {
	if v != nil {
		_u.SetShow(*v)
	}
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *ProxyAnnouncementUpdate) SetPinned(v bool) *ProxyAnnouncementUpdate {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *ProxyAnnouncementUpdate) SetNillablePinned(v *bool) *ProxyAnnouncementUpdate {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetPopup sets the "popup" field.
func (_u *ProxyAnnouncementUpdate) SetPopup(v bool) *ProxyAnnouncementUpdate {
	_u.mutation.SetPopup(v)
	return _u
}

// SetNillablePopup sets the "popup" field if the given value is not nil.
func (_u *ProxyAnnouncementUpdate) SetNillablePopup(v *bool) *ProxyAnnouncementUpdate {
	if v != nil {
		_u.SetPopup(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyAnnouncementUpdate) SetUpdatedAt(v time.Time) *ProxyAnnouncementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxyAnnouncementMutation object of the builder.
func (_u *ProxyAnnouncementUpdate) Mutation() *ProxyAnnouncementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyAnnouncementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyAnnouncementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyAnnouncementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyAnnouncementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyAnnouncementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyannouncement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyAnnouncementUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := proxyannouncement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ProxyAnnouncement.title": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyAnnouncementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyannouncement.Table, proxyannouncement.Columns, sqlgraph.NewFieldSpec(proxyannouncement.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(proxyannouncement.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(proxyannouncement.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(proxyannouncement.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Show(); ok {
		_spec.SetField(proxyannouncement.FieldShow, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(proxyannouncement.FieldPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Popup(); ok {
		_spec.SetField(proxyannouncement.FieldPopup, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyannouncement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyannouncement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyAnnouncementUpdateOne is the builder for updating a single ProxyAnnouncement entity.
type ProxyAnnouncementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyAnnouncementMutation
}

// SetTitle sets the "title" field.
func (_u *ProxyAnnouncementUpdateOne) SetTitle(v string) *ProxyAnnouncementUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProxyAnnouncementUpdateOne) SetNillableTitle(v *string) *ProxyAnnouncementUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ProxyAnnouncementUpdateOne) SetContent(v string) *ProxyAnnouncementUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ProxyAnnouncementUpdateOne) SetNillableContent(v *string) *ProxyAnnouncementUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ProxyAnnouncementUpdateOne) ClearContent() *ProxyAnnouncementUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetShow sets the "show" field.
func (_u *ProxyAnnouncementUpdateOne) SetShow(v bool) *ProxyAnnouncementUpdateOne {
	_u.mutation.SetShow(v)
	return _u
}

// SetNillableShow sets the "show" field if the given value is not nil.
func (_u *ProxyAnnouncementUpdateOne) SetNillableShow(v *bool) *ProxyAnnouncementUpdateOne {
	if v != nil {
		_u.SetShow(*v)
	}
	return _u
}

// SetPinned sets the "pinned" field.
func (_u *ProxyAnnouncementUpdateOne) SetPinned(v bool) *ProxyAnnouncementUpdateOne {
	_u.mutation.SetPinned(v)
	return _u
}

// SetNillablePinned sets the "pinned" field if the given value is not nil.
func (_u *ProxyAnnouncementUpdateOne) SetNillablePinned(v *bool) *ProxyAnnouncementUpdateOne {
	if v != nil {
		_u.SetPinned(*v)
	}
	return _u
}

// SetPopup sets the "popup" field.
func (_u *ProxyAnnouncementUpdateOne) SetPopup(v bool) *ProxyAnnouncementUpdateOne {
	_u.mutation.SetPopup(v)
	return _u
}

// SetNillablePopup sets the "popup" field if the given value is not nil.
func (_u *ProxyAnnouncementUpdateOne) SetNillablePopup(v *bool) *ProxyAnnouncementUpdateOne {
	if v != nil {
		_u.SetPopup(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyAnnouncementUpdateOne) SetUpdatedAt(v time.Time) *ProxyAnnouncementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ProxyAnnouncementMutation object of the builder.
func (_u *ProxyAnnouncementUpdateOne) Mutation() *ProxyAnnouncementMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProxyAnnouncementUpdate builder.
func (_u *ProxyAnnouncementUpdateOne) Where(ps ...predicate.ProxyAnnouncement) *ProxyAnnouncementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyAnnouncementUpdateOne) Select(field string, fields ...string) *ProxyAnnouncementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProxyAnnouncement entity.
func (_u *ProxyAnnouncementUpdateOne) Save(ctx context.Context) (*ProxyAnnouncement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyAnnouncementUpdateOne) SaveX(ctx context.Context) *ProxyAnnouncement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyAnnouncementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyAnnouncementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyAnnouncementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := proxyannouncement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyAnnouncementUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := proxyannouncement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ProxyAnnouncement.title": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyAnnouncementUpdateOne) sqlSave(ctx context.Context) (_node *ProxyAnnouncement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxyannouncement.Table, proxyannouncement.Columns, sqlgraph.NewFieldSpec(proxyannouncement.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProxyAnnouncement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxyannouncement.FieldID)
		for _, f := range fields {
			if !proxyannouncement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxyannouncement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(proxyannouncement.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(proxyannouncement.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(proxyannouncement.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Show(); ok {
		_spec.SetField(proxyannouncement.FieldShow, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Pinned(); ok {
		_spec.SetField(proxyannouncement.FieldPinned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Popup(); ok {
		_spec.SetField(proxyannouncement.FieldPopup, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxyannouncement.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ProxyAnnouncement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxyannouncement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
