// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: admin/user/v1/auth_method.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserAuthMethodRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthType       string                 `protobuf:"bytes,2,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`                   // apple, google, github, facebook, telegram, email, mobile
	AuthIdentifier string                 `protobuf:"bytes,3,opt,name=auth_identifier,json=authIdentifier,proto3" json:"auth_identifier,omitempty"` // 认证标识（邮箱、手机号、OpenID等）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserAuthMethodRequest) Reset() {
	*x = CreateUserAuthMethodRequest{}
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserAuthMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserAuthMethodRequest) ProtoMessage() {}

func (x *CreateUserAuthMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserAuthMethodRequest.ProtoReflect.Descriptor instead.
func (*CreateUserAuthMethodRequest) Descriptor() ([]byte, []int) {
	return file_admin_user_v1_auth_method_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserAuthMethodRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserAuthMethodRequest) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *CreateUserAuthMethodRequest) GetAuthIdentifier() string {
	if x != nil {
		return x.AuthIdentifier
	}
	return ""
}

type CreateUserAuthMethodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserAuthMethodReply) Reset() {
	*x = CreateUserAuthMethodReply{}
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserAuthMethodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserAuthMethodReply) ProtoMessage() {}

func (x *CreateUserAuthMethodReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserAuthMethodReply.ProtoReflect.Descriptor instead.
func (*CreateUserAuthMethodReply) Descriptor() ([]byte, []int) {
	return file_admin_user_v1_auth_method_proto_rawDescGZIP(), []int{1}
}

type UpdateUserAuthMethodRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 用户ID
	AuthType       string                 `protobuf:"bytes,2,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`                   // 认证类型
	AuthIdentifier string                 `protobuf:"bytes,3,opt,name=auth_identifier,json=authIdentifier,proto3" json:"auth_identifier,omitempty"` // 认证标识
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserAuthMethodRequest) Reset() {
	*x = UpdateUserAuthMethodRequest{}
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserAuthMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAuthMethodRequest) ProtoMessage() {}

func (x *UpdateUserAuthMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAuthMethodRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserAuthMethodRequest) Descriptor() ([]byte, []int) {
	return file_admin_user_v1_auth_method_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserAuthMethodRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserAuthMethodRequest) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *UpdateUserAuthMethodRequest) GetAuthIdentifier() string {
	if x != nil {
		return x.AuthIdentifier
	}
	return ""
}

type UpdateUserAuthMethodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserAuthMethodReply) Reset() {
	*x = UpdateUserAuthMethodReply{}
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserAuthMethodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAuthMethodReply) ProtoMessage() {}

func (x *UpdateUserAuthMethodReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAuthMethodReply.ProtoReflect.Descriptor instead.
func (*UpdateUserAuthMethodReply) Descriptor() ([]byte, []int) {
	return file_admin_user_v1_auth_method_proto_rawDescGZIP(), []int{3}
}

type DeleteUserAuthMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户ID
	AuthType      string                 `protobuf:"bytes,2,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"` // 认证类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserAuthMethodRequest) Reset() {
	*x = DeleteUserAuthMethodRequest{}
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserAuthMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserAuthMethodRequest) ProtoMessage() {}

func (x *DeleteUserAuthMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserAuthMethodRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserAuthMethodRequest) Descriptor() ([]byte, []int) {
	return file_admin_user_v1_auth_method_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserAuthMethodRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserAuthMethodRequest) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

type DeleteUserAuthMethodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserAuthMethodReply) Reset() {
	*x = DeleteUserAuthMethodReply{}
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserAuthMethodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserAuthMethodReply) ProtoMessage() {}

func (x *DeleteUserAuthMethodReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserAuthMethodReply.ProtoReflect.Descriptor instead.
func (*DeleteUserAuthMethodReply) Descriptor() ([]byte, []int) {
	return file_admin_user_v1_auth_method_proto_rawDescGZIP(), []int{5}
}

type GetUserAuthMethodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthMethodRequest) Reset() {
	*x = GetUserAuthMethodRequest{}
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthMethodRequest) ProtoMessage() {}

func (x *GetUserAuthMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthMethodRequest.ProtoReflect.Descriptor instead.
func (*GetUserAuthMethodRequest) Descriptor() ([]byte, []int) {
	return file_admin_user_v1_auth_method_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserAuthMethodRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserAuthMethodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthMethods   []*UserAuthMethod      `protobuf:"bytes,1,rep,name=auth_methods,json=authMethods,proto3" json:"auth_methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAuthMethodReply) Reset() {
	*x = GetUserAuthMethodReply{}
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAuthMethodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAuthMethodReply) ProtoMessage() {}

func (x *GetUserAuthMethodReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAuthMethodReply.ProtoReflect.Descriptor instead.
func (*GetUserAuthMethodReply) Descriptor() ([]byte, []int) {
	return file_admin_user_v1_auth_method_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserAuthMethodReply) GetAuthMethods() []*UserAuthMethod {
	if x != nil {
		return x.AuthMethods
	}
	return nil
}

// UserAuthMethod 用户认证方法
type UserAuthMethod struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthType       string                 `protobuf:"bytes,1,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`                   // apple, google, github, facebook, telegram, email, mobile
	AuthIdentifier string                 `protobuf:"bytes,2,opt,name=auth_identifier,json=authIdentifier,proto3" json:"auth_identifier,omitempty"` // 认证标识
	Verified       bool                   `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`                                  // 是否已验证
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserAuthMethod) Reset() {
	*x = UserAuthMethod{}
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthMethod) ProtoMessage() {}

func (x *UserAuthMethod) ProtoReflect() protoreflect.Message {
	mi := &file_admin_user_v1_auth_method_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthMethod.ProtoReflect.Descriptor instead.
func (*UserAuthMethod) Descriptor() ([]byte, []int) {
	return file_admin_user_v1_auth_method_proto_rawDescGZIP(), []int{8}
}

func (x *UserAuthMethod) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *UserAuthMethod) GetAuthIdentifier() string {
	if x != nil {
		return x.AuthIdentifier
	}
	return ""
}

func (x *UserAuthMethod) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

var File_admin_user_v1_auth_method_proto protoreflect.FileDescriptor

const file_admin_user_v1_auth_method_proto_rawDesc = "" +
	"\n" +
	"\x1fadmin/user/v1/auth_method.proto\x12\x11api.admin.user.v1\x1a\x1cgoogle/api/annotations.proto\"|\n" +
	"\x1bCreateUserAuthMethodRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tauth_type\x18\x02 \x01(\tR\bauthType\x12'\n" +
	"\x0fauth_identifier\x18\x03 \x01(\tR\x0eauthIdentifier\"\x1b\n" +
	"\x19CreateUserAuthMethodReply\"|\n" +
	"\x1bUpdateUserAuthMethodRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tauth_type\x18\x02 \x01(\tR\bauthType\x12'\n" +
	"\x0fauth_identifier\x18\x03 \x01(\tR\x0eauthIdentifier\"\x1b\n" +
	"\x19UpdateUserAuthMethodReply\"S\n" +
	"\x1bDeleteUserAuthMethodRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tauth_type\x18\x02 \x01(\tR\bauthType\"\x1b\n" +
	"\x19DeleteUserAuthMethodReply\"3\n" +
	"\x18GetUserAuthMethodRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"\x16GetUserAuthMethodReply\x12D\n" +
	"\fauth_methods\x18\x01 \x03(\v2!.api.admin.user.v1.UserAuthMethodR\vauthMethods\"r\n" +
	"\x0eUserAuthMethod\x12\x1b\n" +
	"\tauth_type\x18\x01 \x01(\tR\bauthType\x12'\n" +
	"\x0fauth_identifier\x18\x02 \x01(\tR\x0eauthIdentifier\x12\x1a\n" +
	"\bverified\x18\x03 \x01(\bR\bverified2\x80\x05\n" +
	"\x15UserAuthMethodService\x12\x9b\x01\n" +
	"\x14CreateUserAuthMethod\x12..api.admin.user.v1.CreateUserAuthMethodRequest\x1a,.api.admin.user.v1.CreateUserAuthMethodReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/admin/user/auth_method\x12\x9b\x01\n" +
	"\x14UpdateUserAuthMethod\x12..api.admin.user.v1.UpdateUserAuthMethodRequest\x1a,.api.admin.user.v1.UpdateUserAuthMethodReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/v1/admin/user/auth_method\x12\x98\x01\n" +
	"\x14DeleteUserAuthMethod\x12..api.admin.user.v1.DeleteUserAuthMethodRequest\x1a,.api.admin.user.v1.DeleteUserAuthMethodReply\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/admin/user/auth_method\x12\x8f\x01\n" +
	"\x11GetUserAuthMethod\x12+.api.admin.user.v1.GetUserAuthMethodRequest\x1a).api.admin.user.v1.GetUserAuthMethodReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/admin/user/auth_methodB4Z2github.com/OmnTeam/ppanel-pro/api/admin/user/v1;v1b\x06proto3"

var (
	file_admin_user_v1_auth_method_proto_rawDescOnce sync.Once
	file_admin_user_v1_auth_method_proto_rawDescData []byte
)

func file_admin_user_v1_auth_method_proto_rawDescGZIP() []byte {
	file_admin_user_v1_auth_method_proto_rawDescOnce.Do(func() {
		file_admin_user_v1_auth_method_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_user_v1_auth_method_proto_rawDesc), len(file_admin_user_v1_auth_method_proto_rawDesc)))
	})
	return file_admin_user_v1_auth_method_proto_rawDescData
}

var file_admin_user_v1_auth_method_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_admin_user_v1_auth_method_proto_goTypes = []any{
	(*CreateUserAuthMethodRequest)(nil), // 0: api.admin.user.v1.CreateUserAuthMethodRequest
	(*CreateUserAuthMethodReply)(nil),   // 1: api.admin.user.v1.CreateUserAuthMethodReply
	(*UpdateUserAuthMethodRequest)(nil), // 2: api.admin.user.v1.UpdateUserAuthMethodRequest
	(*UpdateUserAuthMethodReply)(nil),   // 3: api.admin.user.v1.UpdateUserAuthMethodReply
	(*DeleteUserAuthMethodRequest)(nil), // 4: api.admin.user.v1.DeleteUserAuthMethodRequest
	(*DeleteUserAuthMethodReply)(nil),   // 5: api.admin.user.v1.DeleteUserAuthMethodReply
	(*GetUserAuthMethodRequest)(nil),    // 6: api.admin.user.v1.GetUserAuthMethodRequest
	(*GetUserAuthMethodReply)(nil),      // 7: api.admin.user.v1.GetUserAuthMethodReply
	(*UserAuthMethod)(nil),              // 8: api.admin.user.v1.UserAuthMethod
}
var file_admin_user_v1_auth_method_proto_depIdxs = []int32{
	8, // 0: api.admin.user.v1.GetUserAuthMethodReply.auth_methods:type_name -> api.admin.user.v1.UserAuthMethod
	0, // 1: api.admin.user.v1.UserAuthMethodService.CreateUserAuthMethod:input_type -> api.admin.user.v1.CreateUserAuthMethodRequest
	2, // 2: api.admin.user.v1.UserAuthMethodService.UpdateUserAuthMethod:input_type -> api.admin.user.v1.UpdateUserAuthMethodRequest
	4, // 3: api.admin.user.v1.UserAuthMethodService.DeleteUserAuthMethod:input_type -> api.admin.user.v1.DeleteUserAuthMethodRequest
	6, // 4: api.admin.user.v1.UserAuthMethodService.GetUserAuthMethod:input_type -> api.admin.user.v1.GetUserAuthMethodRequest
	1, // 5: api.admin.user.v1.UserAuthMethodService.CreateUserAuthMethod:output_type -> api.admin.user.v1.CreateUserAuthMethodReply
	3, // 6: api.admin.user.v1.UserAuthMethodService.UpdateUserAuthMethod:output_type -> api.admin.user.v1.UpdateUserAuthMethodReply
	5, // 7: api.admin.user.v1.UserAuthMethodService.DeleteUserAuthMethod:output_type -> api.admin.user.v1.DeleteUserAuthMethodReply
	7, // 8: api.admin.user.v1.UserAuthMethodService.GetUserAuthMethod:output_type -> api.admin.user.v1.GetUserAuthMethodReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admin_user_v1_auth_method_proto_init() }
func file_admin_user_v1_auth_method_proto_init() {
	if File_admin_user_v1_auth_method_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_user_v1_auth_method_proto_rawDesc), len(file_admin_user_v1_auth_method_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_user_v1_auth_method_proto_goTypes,
		DependencyIndexes: file_admin_user_v1_auth_method_proto_depIdxs,
		MessageInfos:      file_admin_user_v1_auth_method_proto_msgTypes,
	}.Build()
	File_admin_user_v1_auth_method_proto = out.File
	file_admin_user_v1_auth_method_proto_goTypes = nil
	file_admin_user_v1_auth_method_proto_depIdxs = nil
}
