syntax = "proto3";

package api.admin.user.v1;

option go_package = "github.com/OmnTeam/ppanel-pro/api/admin/user/v1;v1";

import "google/api/annotations.proto";
import "api/admin/user/v1/device.proto";

// UserSubscribeService 用户订阅管理服务
service UserSubscribeService {
  rpc GetUserSubscribe(GetUserSubscribeRequest) returns (GetUserSubscribeReply) {
    option (google.api.http) = {
      get: "/v1/admin/user/subscribe"
    };
  }

  rpc CreateUserSubscribe(CreateUserSubscribeRequest) returns (CreateUserSubscribeReply) {
    option (google.api.http) = {
      post: "/v1/admin/user/subscribe"
      body: "*"
    };
  }

  rpc UpdateUserSubscribe(UpdateUserSubscribeRequest) returns (UpdateUserSubscribeReply) {
    option (google.api.http) = {
      put: "/v1/admin/user/subscribe"
      body: "*"
    };
  }

  rpc DeleteUserSubscribe(DeleteUserSubscribeRequest) returns (DeleteUserSubscribeReply) {
    option (google.api.http) = {
      delete: "/v1/admin/user/subscribe"
    };
  }

  rpc GetUserSubscribeById(GetUserSubscribeByIdRequest) returns (GetUserSubscribeByIdReply) {
    option (google.api.http) = {
      get: "/v1/admin/user/subscribe/detail"
    };
  }

  rpc GetUserSubscribeDevices(GetUserSubscribeDevicesRequest) returns (GetUserSubscribeDevicesReply) {
    option (google.api.http) = {
      get: "/v1/admin/user/subscribe/device"
    };
  }

  rpc GetUserSubscribeLogs(GetUserSubscribeLogsRequest) returns (GetUserSubscribeLogsReply) {
    option (google.api.http) = {
      get: "/v1/admin/user/subscribe/logs"
    };
  }

  rpc GetUserSubscribeResetTrafficLogs(GetUserSubscribeResetTrafficLogsRequest) returns (GetUserSubscribeResetTrafficLogsReply) {
    option (google.api.http) = {
      get: "/v1/admin/user/subscribe/reset/logs"
    };
  }

  rpc GetUserSubscribeTrafficLogs(GetUserSubscribeTrafficLogsRequest) returns (GetUserSubscribeTrafficLogsReply) {
    option (google.api.http) = {
      get: "/v1/admin/user/subscribe/traffic_logs"
    };
  }

  rpc ResetUserSubscribeToken(ResetUserSubscribeTokenRequest) returns (ResetUserSubscribeTokenReply) {
    option (google.api.http) = {
      post: "/v1/admin/user/subscribe/reset/token"
      body: "*"
    };
  }

  rpc ToggleUserSubscribeStatus(ToggleUserSubscribeStatusRequest) returns (ToggleUserSubscribeStatusReply) {
    option (google.api.http) = {
      post: "/v1/admin/user/subscribe/toggle"
      body: "*"
    };
  }

  rpc ResetUserSubscribeTraffic(ResetUserSubscribeTrafficRequest) returns (ResetUserSubscribeTrafficReply) {
    option (google.api.http) = {
      post: "/v1/admin/user/subscribe/reset/traffic"
      body: "*"
    };
  }
}

message GetUserSubscribeRequest {
  int32 page = 1;
  int32 size = 2;
  string user_id = 3;
  string subscribe_id = 4;
  int32 status = 5;
}

message GetUserSubscribeReply {
  string total = 1;
  repeated UserSubscribe list = 2;
}

message CreateUserSubscribeRequest {
  string user_id = 1;
  string order_id = 2;
  string subscribe_id = 3;
  string start_time = 4;
  string expire_time = 5;
  string traffic = 6;
  int32 status = 7;
}

message CreateUserSubscribeReply {
  string id = 1;
  string token = 2;
  string uuid = 3;
}

message UpdateUserSubscribeRequest {
  string id = 1;
  string start_time = 2;
  string expire_time = 3;
  string traffic = 4;
  string download = 5;
  string upload = 6;
  int32 status = 7;
}

message UpdateUserSubscribeReply {}

message DeleteUserSubscribeRequest {
  string id = 1;
}

message DeleteUserSubscribeReply {}

message GetUserSubscribeByIdRequest {
  string id = 1;
}

message GetUserSubscribeByIdReply {
  UserSubscribe subscribe = 1;
}

message GetUserSubscribeDevicesRequest {
  string user_subscribe_id = 1;
}

message GetUserSubscribeDevicesReply {
  repeated UserDevice devices = 1;
}

message GetUserSubscribeLogsRequest {
  int32 page = 1;
  int32 size = 2;
  string user_id = 3;
  string user_subscribe_id = 4;
  string date = 5;
}

message GetUserSubscribeLogsReply {
  string total = 1;
  repeated SubscribeLog list = 2;
}

message GetUserSubscribeResetTrafficLogsRequest {
  int32 page = 1;
  int32 size = 2;
  string user_id = 3;
  string user_subscribe_id = 4;
  string date = 5;
}

message GetUserSubscribeResetTrafficLogsReply {
  string total = 1;
  repeated ResetTrafficLog list = 2;
}

message GetUserSubscribeTrafficLogsRequest {
  int32 page = 1;
  int32 size = 2;
  string user_id = 3;
  string user_subscribe_id = 4;
  string date = 5;
}

message GetUserSubscribeTrafficLogsReply {
  string total = 1;
  repeated SubscribeTrafficLog list = 2;
}

message UserSubscribe {
  string id = 1;
  string user_id = 2;
  string order_id = 3;
  string subscribe_id = 4;
  string start_time = 5;
  string expire_time = 6;
  string finished_at = 7;
  string traffic = 8;
  string download = 9;
  string upload = 10;
  string token = 11;
  string uuid = 12;
  int32 status = 13;
  string created_at = 14;
  string updated_at = 15;
}

message SubscribeLog {
  string id = 1;
  string user_id = 2;
  string user_subscribe_id = 3;
  string content = 4;
  string timestamp = 5;
}

message ResetTrafficLog {
  string id = 1;
  string user_id = 2;
  string user_subscribe_id = 3;
  string content = 4;
  string timestamp = 5;
}

message SubscribeTrafficLog {
  string id = 1;
  string user_id = 2;
  string user_subscribe_id = 3;
  string content = 4;
  string timestamp = 5;
}

message ResetUserSubscribeTokenRequest {
  string id = 1;
}

message ResetUserSubscribeTokenReply {
  string token = 1;
}

message ToggleUserSubscribeStatusRequest {
  string id = 1;
}

message ToggleUserSubscribeStatusReply {
  int32 status = 1;
}

message ResetUserSubscribeTrafficRequest {
  string id = 1;
}

message ResetUserSubscribeTrafficReply {
  string traffic = 1;
}
