// Code generated by ent, DO NOT EDIT.

package proxyredemptionrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the proxyredemptionrecord type in the database.
	Label = "proxy_redemption_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRedemptionCodeID holds the string denoting the redemption_code_id field in the database.
	FieldRedemptionCodeID = "redemption_code_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSubscribeID holds the string denoting the subscribe_id field in the database.
	FieldSubscribeID = "subscribe_id"
	// FieldUnitTime holds the string denoting the unit_time field in the database.
	FieldUnitTime = "unit_time"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldRedeemedAt holds the string denoting the redeemed_at field in the database.
	FieldRedeemedAt = "redeemed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeRedemptionCode holds the string denoting the redemption_code edge name in mutations.
	EdgeRedemptionCode = "redemption_code"
	// Table holds the table name of the proxyredemptionrecord in the database.
	Table = "redemption_record"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "redemption_record"
	// UserInverseTable is the table name for the ProxyUser entity.
	// It exists in this package in order to avoid circular dependency with the "proxyuser" package.
	UserInverseTable = "user"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// RedemptionCodeTable is the table that holds the redemption_code relation/edge.
	RedemptionCodeTable = "redemption_record"
	// RedemptionCodeInverseTable is the table name for the ProxyRedemptionCode entity.
	// It exists in this package in order to avoid circular dependency with the "proxyredemptioncode" package.
	RedemptionCodeInverseTable = "redemption_code"
	// RedemptionCodeColumn is the table column denoting the redemption_code relation/edge.
	RedemptionCodeColumn = "redemption_code_id"
)

// Columns holds all SQL columns for proxyredemptionrecord fields.
var Columns = []string{
	FieldID,
	FieldRedemptionCodeID,
	FieldUserID,
	FieldSubscribeID,
	FieldUnitTime,
	FieldQuantity,
	FieldRedeemedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUnitTime holds the default value on creation for the "unit_time" field.
	DefaultUnitTime string
	// UnitTimeValidator is a validator for the "unit_time" field. It is called by the builders before save.
	UnitTimeValidator func(string) error
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity int32
	// DefaultRedeemedAt holds the default value on creation for the "redeemed_at" field.
	DefaultRedeemedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the ProxyRedemptionRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRedemptionCodeID orders the results by the redemption_code_id field.
func ByRedemptionCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedemptionCodeID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// BySubscribeID orders the results by the subscribe_id field.
func BySubscribeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscribeID, opts...).ToFunc()
}

// ByUnitTime orders the results by the unit_time field.
func ByUnitTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitTime, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByRedeemedAt orders the results by the redeemed_at field.
func ByRedeemedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByRedemptionCodeField orders the results by redemption_code field.
func ByRedemptionCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRedemptionCodeStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newRedemptionCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RedemptionCodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RedemptionCodeTable, RedemptionCodeColumn),
	)
}
