// Code generated by ent, DO NOT EDIT.

package proxyschemamigrations

import (
	"entgo.io/ent/dialect/sql"
	"github.com/OmnTeam/npanel-pro/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldLTE(FieldID, id))
}

// Dirty applies equality check predicate on the "dirty" field. It's identical to DirtyEQ.
func Dirty(v bool) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldEQ(FieldDirty, v))
}

// DirtyEQ applies the EQ predicate on the "dirty" field.
func DirtyEQ(v bool) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldEQ(FieldDirty, v))
}

// DirtyNEQ applies the NEQ predicate on the "dirty" field.
func DirtyNEQ(v bool) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.FieldNEQ(FieldDirty, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxySchemaMigrations) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxySchemaMigrations) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxySchemaMigrations) predicate.ProxySchemaMigrations {
	return predicate.ProxySchemaMigrations(sql.NotPredicates(p))
}
