// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: auth/v1/auth.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Auth_CheckUser_FullMethodName              = "/api.auth.v1.Auth/CheckUser"
	Auth_CheckUserTelephone_FullMethodName     = "/api.auth.v1.Auth/CheckUserTelephone"
	Auth_UserLogin_FullMethodName              = "/api.auth.v1.Auth/UserLogin"
	Auth_UserRegister_FullMethodName           = "/api.auth.v1.Auth/UserRegister"
	Auth_TelephoneUserRegister_FullMethodName  = "/api.auth.v1.Auth/TelephoneUserRegister"
	Auth_TelephoneLogin_FullMethodName         = "/api.auth.v1.Auth/TelephoneLogin"
	Auth_ResetPassword_FullMethodName          = "/api.auth.v1.Auth/ResetPassword"
	Auth_TelephoneResetPassword_FullMethodName = "/api.auth.v1.Auth/TelephoneResetPassword"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Auth service for user authentication
type AuthClient interface {
	// Check if user exists by email
	CheckUser(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*CheckUserReply, error)
	// Check if user exists by telephone
	CheckUserTelephone(ctx context.Context, in *CheckUserTelephoneRequest, opts ...grpc.CallOption) (*CheckUserTelephoneReply, error)
	// User login with email and password
	UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginReply, error)
	// User register with email and password
	UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterReply, error)
	// User register with telephone and password
	TelephoneUserRegister(ctx context.Context, in *TelephoneUserRegisterRequest, opts ...grpc.CallOption) (*TelephoneUserRegisterReply, error)
	// User login with telephone and password
	TelephoneLogin(ctx context.Context, in *TelephoneLoginRequest, opts ...grpc.CallOption) (*TelephoneLoginReply, error)
	// Reset password with email
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordReply, error)
	// Reset password with telephone
	TelephoneResetPassword(ctx context.Context, in *TelephoneResetPasswordRequest, opts ...grpc.CallOption) (*TelephoneResetPasswordReply, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) CheckUser(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*CheckUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserReply)
	err := c.cc.Invoke(ctx, Auth_CheckUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) CheckUserTelephone(ctx context.Context, in *CheckUserTelephoneRequest, opts ...grpc.CallOption) (*CheckUserTelephoneReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserTelephoneReply)
	err := c.cc.Invoke(ctx, Auth_CheckUserTelephone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLoginReply)
	err := c.cc.Invoke(ctx, Auth_UserLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserRegisterReply)
	err := c.cc.Invoke(ctx, Auth_UserRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) TelephoneUserRegister(ctx context.Context, in *TelephoneUserRegisterRequest, opts ...grpc.CallOption) (*TelephoneUserRegisterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelephoneUserRegisterReply)
	err := c.cc.Invoke(ctx, Auth_TelephoneUserRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) TelephoneLogin(ctx context.Context, in *TelephoneLoginRequest, opts ...grpc.CallOption) (*TelephoneLoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelephoneLoginReply)
	err := c.cc.Invoke(ctx, Auth_TelephoneLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetPasswordReply)
	err := c.cc.Invoke(ctx, Auth_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) TelephoneResetPassword(ctx context.Context, in *TelephoneResetPasswordRequest, opts ...grpc.CallOption) (*TelephoneResetPasswordReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelephoneResetPasswordReply)
	err := c.cc.Invoke(ctx, Auth_TelephoneResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility.
//
// Auth service for user authentication
type AuthServer interface {
	// Check if user exists by email
	CheckUser(context.Context, *CheckUserRequest) (*CheckUserReply, error)
	// Check if user exists by telephone
	CheckUserTelephone(context.Context, *CheckUserTelephoneRequest) (*CheckUserTelephoneReply, error)
	// User login with email and password
	UserLogin(context.Context, *UserLoginRequest) (*UserLoginReply, error)
	// User register with email and password
	UserRegister(context.Context, *UserRegisterRequest) (*UserRegisterReply, error)
	// User register with telephone and password
	TelephoneUserRegister(context.Context, *TelephoneUserRegisterRequest) (*TelephoneUserRegisterReply, error)
	// User login with telephone and password
	TelephoneLogin(context.Context, *TelephoneLoginRequest) (*TelephoneLoginReply, error)
	// Reset password with email
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordReply, error)
	// Reset password with telephone
	TelephoneResetPassword(context.Context, *TelephoneResetPasswordRequest) (*TelephoneResetPasswordReply, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServer struct{}

func (UnimplementedAuthServer) CheckUser(context.Context, *CheckUserRequest) (*CheckUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUser not implemented")
}
func (UnimplementedAuthServer) CheckUserTelephone(context.Context, *CheckUserTelephoneRequest) (*CheckUserTelephoneReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserTelephone not implemented")
}
func (UnimplementedAuthServer) UserLogin(context.Context, *UserLoginRequest) (*UserLoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (UnimplementedAuthServer) UserRegister(context.Context, *UserRegisterRequest) (*UserRegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegister not implemented")
}
func (UnimplementedAuthServer) TelephoneUserRegister(context.Context, *TelephoneUserRegisterRequest) (*TelephoneUserRegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TelephoneUserRegister not implemented")
}
func (UnimplementedAuthServer) TelephoneLogin(context.Context, *TelephoneLoginRequest) (*TelephoneLoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TelephoneLogin not implemented")
}
func (UnimplementedAuthServer) ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedAuthServer) TelephoneResetPassword(context.Context, *TelephoneResetPasswordRequest) (*TelephoneResetPasswordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TelephoneResetPassword not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}
func (UnimplementedAuthServer) testEmbeddedByValue()              {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	// If the following call pancis, it indicates UnimplementedAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_CheckUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CheckUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_CheckUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CheckUser(ctx, req.(*CheckUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_CheckUserTelephone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserTelephoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CheckUserTelephone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_CheckUserTelephone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CheckUserTelephone(ctx, req.(*CheckUserTelephoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_UserLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).UserLogin(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_UserRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).UserRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_UserRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).UserRegister(ctx, req.(*UserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_TelephoneUserRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelephoneUserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).TelephoneUserRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_TelephoneUserRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).TelephoneUserRegister(ctx, req.(*TelephoneUserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_TelephoneLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelephoneLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).TelephoneLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_TelephoneLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).TelephoneLogin(ctx, req.(*TelephoneLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_TelephoneResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelephoneResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).TelephoneResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_TelephoneResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).TelephoneResetPassword(ctx, req.(*TelephoneResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.auth.v1.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUser",
			Handler:    _Auth_CheckUser_Handler,
		},
		{
			MethodName: "CheckUserTelephone",
			Handler:    _Auth_CheckUserTelephone_Handler,
		},
		{
			MethodName: "UserLogin",
			Handler:    _Auth_UserLogin_Handler,
		},
		{
			MethodName: "UserRegister",
			Handler:    _Auth_UserRegister_Handler,
		},
		{
			MethodName: "TelephoneUserRegister",
			Handler:    _Auth_TelephoneUserRegister_Handler,
		},
		{
			MethodName: "TelephoneLogin",
			Handler:    _Auth_TelephoneLogin_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _Auth_ResetPassword_Handler,
		},
		{
			MethodName: "TelephoneResetPassword",
			Handler:    _Auth_TelephoneResetPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/auth.proto",
}
