// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: public/ticket/v1/ticket.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateUserTicketRequest is the request to create a ticket
type CreateUserTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`             // Ticket title
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Ticket description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserTicketRequest) Reset() {
	*x = CreateUserTicketRequest{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserTicketRequest) ProtoMessage() {}

func (x *CreateUserTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateUserTicketRequest) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserTicketRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateUserTicketRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// TicketCreateReply 创建工单响应
type TicketCreateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketCreateReply) Reset() {
	*x = TicketCreateReply{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCreateReply) ProtoMessage() {}

func (x *TicketCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCreateReply.ProtoReflect.Descriptor instead.
func (*TicketCreateReply) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *TicketCreateReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TicketCreateReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetUserTicketListRequest is the request to get ticket list
type GetUserTicketListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`           // Page number (starts from 1)
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`           // Page size
	Status        *int32                 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"` // Filter by status (1=Pending, 2=Waiting, 3=Processed, 4=Closed)
	Search        *string                `protobuf:"bytes,4,opt,name=search,proto3,oneof" json:"search,omitempty"`  // Search keyword
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTicketListRequest) Reset() {
	*x = GetUserTicketListRequest{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTicketListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTicketListRequest) ProtoMessage() {}

func (x *GetUserTicketListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTicketListRequest.ProtoReflect.Descriptor instead.
func (*GetUserTicketListRequest) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserTicketListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserTicketListRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetUserTicketListRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *GetUserTicketListRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

// TicketListData 工单列表数据
type TicketListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // Total count
	List          []*TicketInfo          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`    // Ticket list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketListData) Reset() {
	*x = TicketListData{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketListData) ProtoMessage() {}

func (x *TicketListData) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketListData.ProtoReflect.Descriptor instead.
func (*TicketListData) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *TicketListData) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TicketListData) GetList() []*TicketInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// TicketListReply 工单列表响应
type TicketListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息内容
	Data          *TicketListData        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`       // 响应数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketListReply) Reset() {
	*x = TicketListReply{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketListReply) ProtoMessage() {}

func (x *TicketListReply) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketListReply.ProtoReflect.Descriptor instead.
func (*TicketListReply) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{4}
}

func (x *TicketListReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TicketListReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TicketListReply) GetData() *TicketListData {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetUserTicketDetailsRequest is the request to get ticket details
type GetUserTicketDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Ticket ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTicketDetailsRequest) Reset() {
	*x = GetUserTicketDetailsRequest{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTicketDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTicketDetailsRequest) ProtoMessage() {}

func (x *GetUserTicketDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTicketDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetUserTicketDetailsRequest) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserTicketDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// TicketDetailReply 工单详情响应
type TicketDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息内容
	Data          *TicketInfo            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`       // 响应数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketDetailReply) Reset() {
	*x = TicketDetailReply{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketDetailReply) ProtoMessage() {}

func (x *TicketDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketDetailReply.ProtoReflect.Descriptor instead.
func (*TicketDetailReply) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{6}
}

func (x *TicketDetailReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TicketDetailReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TicketDetailReply) GetData() *TicketInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpdateUserTicketStatusRequest is the request to update ticket status
type UpdateUserTicketStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`          // Ticket ID
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // New status (1=Pending, 2=Waiting, 3=Processed, 4=Closed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserTicketStatusRequest) Reset() {
	*x = UpdateUserTicketStatusRequest{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserTicketStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserTicketStatusRequest) ProtoMessage() {}

func (x *UpdateUserTicketStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserTicketStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserTicketStatusRequest) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserTicketStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserTicketStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// TicketStatusReply 更新工单状态响应
type TicketStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketStatusReply) Reset() {
	*x = TicketStatusReply{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketStatusReply) ProtoMessage() {}

func (x *TicketStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketStatusReply.ProtoReflect.Descriptor instead.
func (*TicketStatusReply) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{8}
}

func (x *TicketStatusReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TicketStatusReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CreateUserTicketFollowRequest is the request to create a follow-up
type CreateUserTicketFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"` // Ticket ID
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`                         // Who created this follow-up
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                        // Type: 1=text, 2=image
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                   // Follow-up content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserTicketFollowRequest) Reset() {
	*x = CreateUserTicketFollowRequest{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserTicketFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserTicketFollowRequest) ProtoMessage() {}

func (x *CreateUserTicketFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserTicketFollowRequest.ProtoReflect.Descriptor instead.
func (*CreateUserTicketFollowRequest) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{9}
}

func (x *CreateUserTicketFollowRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *CreateUserTicketFollowRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CreateUserTicketFollowRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateUserTicketFollowRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// TicketFollowReply 创建工单跟进响应
type TicketFollowReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketFollowReply) Reset() {
	*x = TicketFollowReply{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketFollowReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketFollowReply) ProtoMessage() {}

func (x *TicketFollowReply) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketFollowReply.ProtoReflect.Descriptor instead.
func (*TicketFollowReply) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{10}
}

func (x *TicketFollowReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TicketFollowReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TicketInfo represents a ticket with follow-ups
type TicketInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // Ticket ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                          // Title
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`              // Description
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // User ID
	Follow        []*TicketFollow        `protobuf:"bytes,5,rep,name=follow,proto3" json:"follow,omitempty"`                        // Follow-up records
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                       // Status
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Created time (Unix timestamp milliseconds)
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Updated time (Unix timestamp milliseconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketInfo) Reset() {
	*x = TicketInfo{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketInfo) ProtoMessage() {}

func (x *TicketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketInfo.ProtoReflect.Descriptor instead.
func (*TicketInfo) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{11}
}

func (x *TicketInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TicketInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TicketInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TicketInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TicketInfo) GetFollow() []*TicketFollow {
	if x != nil {
		return x.Follow
	}
	return nil
}

func (x *TicketInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TicketInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TicketInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// TicketFollow represents a follow-up record
type TicketFollow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // Follow ID
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`    // Ticket ID
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`                            // Who created this
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`                           // Type
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                      // Content
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Created time (Unix timestamp milliseconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketFollow) Reset() {
	*x = TicketFollow{}
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketFollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketFollow) ProtoMessage() {}

func (x *TicketFollow) ProtoReflect() protoreflect.Message {
	mi := &file_public_ticket_v1_ticket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketFollow.ProtoReflect.Descriptor instead.
func (*TicketFollow) Descriptor() ([]byte, []int) {
	return file_public_ticket_v1_ticket_proto_rawDescGZIP(), []int{12}
}

func (x *TicketFollow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TicketFollow) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *TicketFollow) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TicketFollow) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TicketFollow) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TicketFollow) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_public_ticket_v1_ticket_proto protoreflect.FileDescriptor

const file_public_ticket_v1_ticket_proto_rawDesc = "" +
	"\n" +
	"\x1dpublic/ticket/v1/ticket.proto\x12\x14api.public.ticket.v1\x1a\x1cgoogle/api/annotations.proto\"Q\n" +
	"\x17CreateUserTicketRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"A\n" +
	"\x11TicketCreateReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x92\x01\n" +
	"\x18GetUserTicketListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x00R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x04 \x01(\tH\x01R\x06search\x88\x01\x01B\t\n" +
	"\a_statusB\t\n" +
	"\a_search\"\\\n" +
	"\x0eTicketListData\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x124\n" +
	"\x04list\x18\x02 \x03(\v2 .api.public.ticket.v1.TicketInfoR\x04list\"y\n" +
	"\x0fTicketListReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\x04data\x18\x03 \x01(\v2$.api.public.ticket.v1.TicketListDataR\x04data\"-\n" +
	"\x1bGetUserTicketDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"w\n" +
	"\x11TicketDetailReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x04data\x18\x03 \x01(\v2 .api.public.ticket.v1.TicketInfoR\x04data\"G\n" +
	"\x1dUpdateUserTicketStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"A\n" +
	"\x11TicketStatusReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"~\n" +
	"\x1dCreateUserTicketFollowRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"A\n" +
	"\x11TicketFollowReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xff\x01\n" +
	"\n" +
	"TicketInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12:\n" +
	"\x06follow\x18\x05 \x03(\v2\".api.public.ticket.v1.TicketFollowR\x06follow\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x9c\x01\n" +
	"\fTicketFollow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt2\xec\x05\n" +
	"\x06Ticket\x12\x88\x01\n" +
	"\x10CreateUserTicket\x12-.api.public.ticket.v1.CreateUserTicketRequest\x1a'.api.public.ticket.v1.TicketCreateReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/public/ticket\x12\x8a\x01\n" +
	"\x11GetUserTicketList\x12..api.public.ticket.v1.GetUserTicketListRequest\x1a%.api.public.ticket.v1.TicketListReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/public/ticket/list\x12\x94\x01\n" +
	"\x14GetUserTicketDetails\x121.api.public.ticket.v1.GetUserTicketDetailsRequest\x1a'.api.public.ticket.v1.TicketDetailReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/public/ticket/detail\x12\x94\x01\n" +
	"\x16UpdateUserTicketStatus\x123.api.public.ticket.v1.UpdateUserTicketStatusRequest\x1a'.api.public.ticket.v1.TicketStatusReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/public/ticket\x12\x9b\x01\n" +
	"\x16CreateUserTicketFollow\x123.api.public.ticket.v1.CreateUserTicketFollowRequest\x1a'.api.public.ticket.v1.TicketFollowReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/public/ticket/followBO\n" +
	"\x14api.public.ticket.v1P\x01Z5github.com/OmnTeam/ppanel-pro/api/public/ticket/v1;v1b\x06proto3"

var (
	file_public_ticket_v1_ticket_proto_rawDescOnce sync.Once
	file_public_ticket_v1_ticket_proto_rawDescData []byte
)

func file_public_ticket_v1_ticket_proto_rawDescGZIP() []byte {
	file_public_ticket_v1_ticket_proto_rawDescOnce.Do(func() {
		file_public_ticket_v1_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_ticket_v1_ticket_proto_rawDesc), len(file_public_ticket_v1_ticket_proto_rawDesc)))
	})
	return file_public_ticket_v1_ticket_proto_rawDescData
}

var file_public_ticket_v1_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_public_ticket_v1_ticket_proto_goTypes = []any{
	(*CreateUserTicketRequest)(nil),       // 0: api.public.ticket.v1.CreateUserTicketRequest
	(*TicketCreateReply)(nil),             // 1: api.public.ticket.v1.TicketCreateReply
	(*GetUserTicketListRequest)(nil),      // 2: api.public.ticket.v1.GetUserTicketListRequest
	(*TicketListData)(nil),                // 3: api.public.ticket.v1.TicketListData
	(*TicketListReply)(nil),               // 4: api.public.ticket.v1.TicketListReply
	(*GetUserTicketDetailsRequest)(nil),   // 5: api.public.ticket.v1.GetUserTicketDetailsRequest
	(*TicketDetailReply)(nil),             // 6: api.public.ticket.v1.TicketDetailReply
	(*UpdateUserTicketStatusRequest)(nil), // 7: api.public.ticket.v1.UpdateUserTicketStatusRequest
	(*TicketStatusReply)(nil),             // 8: api.public.ticket.v1.TicketStatusReply
	(*CreateUserTicketFollowRequest)(nil), // 9: api.public.ticket.v1.CreateUserTicketFollowRequest
	(*TicketFollowReply)(nil),             // 10: api.public.ticket.v1.TicketFollowReply
	(*TicketInfo)(nil),                    // 11: api.public.ticket.v1.TicketInfo
	(*TicketFollow)(nil),                  // 12: api.public.ticket.v1.TicketFollow
}
var file_public_ticket_v1_ticket_proto_depIdxs = []int32{
	11, // 0: api.public.ticket.v1.TicketListData.list:type_name -> api.public.ticket.v1.TicketInfo
	3,  // 1: api.public.ticket.v1.TicketListReply.data:type_name -> api.public.ticket.v1.TicketListData
	11, // 2: api.public.ticket.v1.TicketDetailReply.data:type_name -> api.public.ticket.v1.TicketInfo
	12, // 3: api.public.ticket.v1.TicketInfo.follow:type_name -> api.public.ticket.v1.TicketFollow
	0,  // 4: api.public.ticket.v1.Ticket.CreateUserTicket:input_type -> api.public.ticket.v1.CreateUserTicketRequest
	2,  // 5: api.public.ticket.v1.Ticket.GetUserTicketList:input_type -> api.public.ticket.v1.GetUserTicketListRequest
	5,  // 6: api.public.ticket.v1.Ticket.GetUserTicketDetails:input_type -> api.public.ticket.v1.GetUserTicketDetailsRequest
	7,  // 7: api.public.ticket.v1.Ticket.UpdateUserTicketStatus:input_type -> api.public.ticket.v1.UpdateUserTicketStatusRequest
	9,  // 8: api.public.ticket.v1.Ticket.CreateUserTicketFollow:input_type -> api.public.ticket.v1.CreateUserTicketFollowRequest
	1,  // 9: api.public.ticket.v1.Ticket.CreateUserTicket:output_type -> api.public.ticket.v1.TicketCreateReply
	4,  // 10: api.public.ticket.v1.Ticket.GetUserTicketList:output_type -> api.public.ticket.v1.TicketListReply
	6,  // 11: api.public.ticket.v1.Ticket.GetUserTicketDetails:output_type -> api.public.ticket.v1.TicketDetailReply
	8,  // 12: api.public.ticket.v1.Ticket.UpdateUserTicketStatus:output_type -> api.public.ticket.v1.TicketStatusReply
	10, // 13: api.public.ticket.v1.Ticket.CreateUserTicketFollow:output_type -> api.public.ticket.v1.TicketFollowReply
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_public_ticket_v1_ticket_proto_init() }
func file_public_ticket_v1_ticket_proto_init() {
	if File_public_ticket_v1_ticket_proto != nil {
		return
	}
	file_public_ticket_v1_ticket_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_ticket_v1_ticket_proto_rawDesc), len(file_public_ticket_v1_ticket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_ticket_v1_ticket_proto_goTypes,
		DependencyIndexes: file_public_ticket_v1_ticket_proto_depIdxs,
		MessageInfos:      file_public_ticket_v1_ticket_proto_msgTypes,
	}.Build()
	File_public_ticket_v1_ticket_proto = out.File
	file_public_ticket_v1_ticket_proto_goTypes = nil
	file_public_ticket_v1_ticket_proto_depIdxs = nil
}
